### ISSUE TITLE
Publishing a fork

### ISSUE THREAD

**Issue by Randgalt** [square/javapoet#1003]
AFAIK I can publish an artifact based on Javapoet. I'm planning on doing that to incorporate new Java features. @JakeWharton and/or Square, please let me know if you have any objections to my doing this. I've taken care to add proper licenses and notices.

https://github.com/Randgalt/java-composer

**Comment by JakeWharton** [comment]
You are free to fork and release in accordance with the license. Thanks!

**Comment by Randgalt** [comment]
Java Composer 1.0: https://github.com/Randgalt/java-composer
