### ISSUE TITLE
Thoughtful ordering of members

### ISSUE THREAD

**Issue by JakeWharton** [square/javapoet#112]
Right now static methods are emitted below constructors.

Seems like the only logical grouping we should make. There are other one's in practice (public static methods before lesser scoped static methods, public instance methods before lesser scoped instance methods, etc.) but I don't think they should be addressed at this time (if ever).

**Comment by swankjesse** [comment]
For 3.0, I propose this ordering:

static fields
instance fields
constructors
methods
types

Within each group, the caller's declaration order is honored. We can make this fancier as necessary.
