### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by JakeWharton** [square/javapoet#136]
This would be really easy if `TypeName` was an `abstract class`...

Examples:
```java
@NonNull List<String>
List<@NonNull String>
new @Thing Foo();
new Foo.@Thing Bar();
foo.new @Thing Bar();
<? super @NonNull String>
<T extends @Thing Foo>
```

**Comment by sormuras** [comment]
Why is `PrimitiveName` a blocker?
Actually, I looking here http://stackoverflow.com/questions/33055732/compare-javapoet-parameterspec-type-with-java-8-annotatedtype for an `AnnotatedTypeName`-related answer. May be, a solution to this issue will pop up.

**Comment by tbroyer** [comment]
@sormuras There used to be a `PrimitiveName` that was an `enum` (see PR #138); it was in JavaWriter though, and has been removed in JavaPoet.

**Comment by sormuras** [comment]
What do you prefer?
* Add a `public final List<AnnotationSpec> annotations` to `TypeName`, evolve the getter and emit code of all *`Name` classes and remove annotations lists from `FieldSpec`, `ParameterSpec`
* or introduce an extra class named `AnnotatedTypeName` that extends `TypeName` and collects the anntations? Like:
```java
package com.squareup.javapoet;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;

/** A tuple of any type name and a collection of annotations. */
@SuppressWarnings("javadoc")
public final class AnnotatedTypeName extends TypeName {

  public static AnnotatedTypeName get(TypeName type, List<AnnotationSpec> annotations) {
    return new AnnotatedTypeName(type, annotations);
  }

  public static AnnotatedTypeName get(TypeMirror mirror) {
    TypeMirror annotatedMirror = mirror;
    if (mirror.getKind() == TypeKind.ARRAY) {
      annotatedMirror = ((ArrayType) mirror).getComponentType();
    }
    return get(mirror, annotatedMirror.getAnnotationMirrors());
  }

  public static AnnotatedTypeName get(TypeMirror mirror, List<? extends AnnotationMirror> mirrors) {
    TypeName type = TypeName.get(mirror);
    List<AnnotationSpec> annotations = new ArrayList<>();
    for (AnnotationMirror annotation : mirrors) {
      annotations.add(AnnotationSpec.get(annotation));
    }
    return new AnnotatedTypeName(type, annotations);
  }

  public final TypeName type;
  public final List<AnnotationSpec> annotations;

  private AnnotatedTypeName(TypeName type, List<AnnotationSpec> annotations) {
    this.type = type;
    this.annotations = Util.immutableList(annotations);
  }

  @Override
  CodeWriter emit(CodeWriter out) throws IOException {
    if (!annotations.isEmpty()) {
      for (AnnotationSpec annotation : annotations) {
        annotation.emit(out, true);
        out.emit(" ");
      }
    }
    return type.emit(out);
  }
}
```

**Comment by swankjesse** [comment]
It's got to be composition, not inheritance.

**Comment by swankjesse** [comment]
Otherwise `String` and `@Nullable String` need to be equal or not, and either way we're hosed.

**Comment by sormuras** [comment]
Alright, preparing the PR later today with the second propsal.

**Comment by sormuras** [comment]
Composition like above w/o the `extends`?

**Comment by swankjesse** [comment]
Maybe this:
```
class TypeName {
  ...
  AnnotatedTypeName annotated(...);
}
```
I think we use $T for both.

**Comment by sormuras** [comment]
Ja, another keen way to get a *ATN* handle.

One more thought concering inheritance - what's the difference here in respect to equality and `List` and `List<String>`? They're *not* equal in terms of JavaPoet-model classes, one is a `TypeName` and one is a `ParameterizedTypeName`, right?

**Comment by sormuras** [comment]
Ah - maybe, you didn't see the composition in the code snippet above. It's actually both: extending `TypeName` for the model integration and holding a reference to an underlying `TypeName`. Just like `ParameterizedTypeName` does.

**Comment by sormuras** [comment]
Removed the static getters - as they use Java 8 `TypeMirror` interface. It doesn't extends `javax.lang.model.AnnotatedConstruct` in 7 and lower.

**Comment by sormuras** [comment]
Are sure, this is legal syntax?
```java
new @Thing Foo();
new Foo.@Thing Bar();
foo.new @Thing Bar();
```
Keep getting `Syntax error, type annotations are illegal here` issues.

**Comment by JakeWharton** [comment]
I don't remember! I had thought I ran it through a compiler when I created them, but it was so long ago.

**Comment by sormuras** [comment]
Will add them to the tests, as soon they compile.

**Comment by sormuras** [comment]
PR #355 is stable and squashed. Should have been in the initial PR, as the tests show, that composition and inheritance is mandatory for `AnnotatedTypeName`.

**Comment by sormuras** [comment]
* First step, add `List<AnnotationSpec>` to `TypeName`
* Next, add stripping methods: #358 
* Finally, remove `List<AnnotationSpec>` from `FieldSpec`, `ParameterSpec`?

**Comment by JakeWharton** [comment]
No to the last bullet. Fields and parameters are still annotation targets
and type annotations are different things.

**Comment by sormuras** [comment]
Fields/parameters have exactly one type. A type can be annotated, soon `TypeName` will be.
```java
@A @B String field;
```
Is `@A` part of `String` type, or part of the `field` annotation list? What's with `@B`? Are both part of the type or both part of the field?

Does it not matter?

**Comment by JakeWharton** [comment]
As far as the generated code goes, they'll end up being the same output. But they're semantically very different. I don't think we should force someone to do type annotations when they actually just want to annotate the field or parameter regardless of the actual type.

As to your question, there are rules which resolve it in a deterministic way that came with Java 8. Probably somewhere in the JLS. At the very least, if one is `@Target(TYPE)` and the other is `@Target(FIELD)` it becomes unambiguous as far as a processing perspective.

**Comment by sormuras** [comment]
Thanks for clarification.

At least one more question regarding the first step "*add `List<AnnotationSpec>` to `TypeName`*":
* extend all static name-related getters with `AnnotationSpec...`, goes for 6 types.
* or should I introduce an `annotated(AnnotationSpec...)` and `annotated(List<AnnotationSpec>)` to `TypeName`?

**Comment by sormuras** [comment]
See https://github.com/square/javapoet/compare/square:master...sormuras:annotype for work in progress proposals.
