### ISSUE TITLE
Code Block Objects

### ISSUE THREAD

**Issue by swankjesse** [square/javapoet#171]
From https://github.com/square/javawriter/issues/51 :

> Objects which represents pieces of code lend themselves naturally to writing emission code in Java. The wins should hopefully be fairly obvious.
> 
> There is a potential for API explosion here to cover the diversity of the Java language. A potential also exists for adding an unacceptable amount of boilerplate to the API.

That issue has further discussion & API examples.

**Comment by JakeWharton** [comment]
https://github.com/square/javapoet/pull/178
