### ISSUE TITLE
Where can I find the maven repository for this?

### ISSUE THREAD

**Issue by s4ke** [square/javapoet#189]
I can't find the location of the maven repository and I don't want to rely on a SNAPSHOT in my project. Can you give me a link to a functional maven repo?

**Comment by tbroyer** [comment]
JavaPoet hasn't been released yet, so there are only snapshots for now: https://oss.sonatype.org/content/repositories/snapshots/com/squareup/javapoet/

You can find JavaWriter releases in Central though: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.squareup%22%20AND%20a%3A%22javawriter%22

**Comment by wokkaflokka** [comment]
Can I pose a follow up: is there any ballpark estimate as to when v1 will be released? I'm trying to assess if it will be necessary to backport the code I prototyped using javapoet to javawriter.

**Comment by JakeWharton** [comment]
Before the end of this month.

**Comment by wokkaflokka** [comment]
Awesome, thanks for the quick response.

**Comment by s4ke** [comment]
thanks for the response :)
