### ISSUE TITLE
Native methods and GWT JSNI

### ISSUE THREAD

**Issue by nmorel** [square/javapoet#190]
Hi, 

I am testing javapoet to maybe use it on a GWT project. I need to write a few [JSNI methods](http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJSNI.html) and I can't find a way to do it.

An example of the desired output : 
```java
public static native void alert(String msg) /*-{
  $wnd.alert(msg);
}-*/;
```

For now, if I add the `Modifier.NATIVE` to my method without code, I obtain this which do not compile because native method cannot have a body : 
```java
public static native void alert(String msg) {
}
```

For that, it would be simple to add a case like `Modifier.ABSTRACT` in the `MethodSpec.emit` method.

But for JSNI methods, I need to add a `CodeBlock` between the parameters and `;`. The `CodeBlock` is easy to write and I don't mind writing the indentation manually like that :
```java
CodeBlock.builder()
    .add("/*-{\n")
    .indent()
    .addStatement("$$wnd.alert(msg)")
    .unindent()
    .add("}-*/")
    .build()
```

But I can't find a way to override the default braces that are added. And since all the builders or *Spec are final, I can't override the behaviour too.

Would it be a good solution for you if I modify the `MethodSpec.emit` method to add these just after the exceptions : 
```java
    if (hasModifier(Modifier.NATIVE)) {
      codeWriter.emit(code);
      codeWriter.emit(";\n");
      return;
    }  
```
I can make a PR.

Note: Is that normal that you return before writing the exceptions with an abstract method ?

**Comment by tbroyer** [comment]
IIRC we had decided last year that for GWT JSNI support you'd fork JavaWriter.
That said, I'd quite obviously welcome such an addition. However, GWT will soon (2.8?) have _JSNI 2_ removing the need for the `native` + `/-*{ }-*/` hack.

**Comment by swankjesse** [comment]
Supporting JSNI natively seems easy enough. Send a PR that includes a test!

**Comment by nmorel** [comment]
Done :)
