### ISSUE TITLE
Support TypeBuilder#addMethods

### ISSUE THREAD

**Issue by fbiville** [square/javapoet#211]
As of 1.0.0 of JavaPoets and as it was already the case with JavaWriter, there is no way to add several methods at once.

My usecase here is that I iterate over a collection to generate several similar methods. 
Because of the absence of `addMethods`, I gotta break the call chaining, thus ruining imo the point of a fluent API.

WDYT?

**Comment by swankjesse** [comment]
Works for me. For symmetry, wanna also add the other bulk operations:
```
TypeSpec.Builder.addMethods(List<MethodSpec>)
TypeSpec.Builder.addAnnotations(List<AnnotationSpec>)
TypeSpec.Builder.addTypeVariables(List<TypeVariableName>)
TypeSpec.Builder.addSuperinterfaces(List<TypeName>)
TypeSpec.Builder.addFields(List<FieldSpec>)
TypeSpec.Builder.addTypes(List<TypeSpec>)
MethodSpec.Builder.addTypeVariables(List<TypeVariableName>)
MethodSpec.Builder.addParameters(List<ParameterSpec>)
MethodSpec.Builder.addExceptions(List<TypeName>)
MethodSpec.Builder.addAnnotations(List<AnnotationSpec>)
FieldSpec.Builder.addAnnotations(List<AnnotationSpec>)
ParameterSpec.Builder.addAnnotations(List<AnnotationSpec>)
```

Wanna send a pull request?

**Comment by tbroyer** [comment]
Maybe use `Iterable` instead, and also support varargs?

**Comment by JakeWharton** [comment]
Having to support single, iterable, and varargs for every method was one of the things I hated most about the JavaWriter 3 API. I think there's no reason to do varargs when you can just make multiple successive calls to the `addFoo` method.

**Comment by swankjesse** [comment]
Proposal: bulk op that takes `Collection` for the 12 ops above:
```
TypeSpec.Builder.addMethods(Collection<MethodSpec>)
```
No varargs, 'cause repeated `addXxx()` calls are sufficient. I slightly prefer `Collection` over `Iterable` 'cause it's easier to implement. (And I rarely have an `Iterable` that isn't a `Collection`).

**Comment by fbiville** [comment]
OK, preparing the PR and sending :)
