### ISSUE TITLE
Fail on multiple FieldSpec.initializer() calls

### ISSUE THREAD

**Issue by ben-manes** [square/javapoet#212]
Instead of generating invalid Java code, a precondition should fail if the user accidentally calls `initializer` multiple times. This might occur when refactoring and accidentally leaving the old with the new initializer during a test cycle.

**Comment by JakeWharton** [comment]
What about this case?

```java
ParameterizedTypeName stringSet = ParameterizedTypeName.get(Set.class, String.class);
FieldSpec.Builder builder = FieldSpec.builder(stringSet, "names");
builder.initializer("$T.builder()$>$>", ImmutableSet.class);
for (String name : Arrays.asList("One", "Two", "Three")) {
  builder.initializer("\n.add($L)", name);
}
builder.initializer("\n.build()$<$<");

TypeSpec taco = TypeSpec.classBuilder("Taco").addField(builder.build()).build();
assertThat(toString(taco)).isEqualTo(""
    + "package com.squareup.tacos;\n"
    + "\n"
    + "import com.google.common.collect.ImmutableSet;\n"
    + "import java.lang.String;\n"
    + "import java.util.Set;\n"
    + "\n"
    + "class Taco {\n"
    + "  Set<String> names = ImmutableSet.builder()\n"
    + "      .add(One)\n"
    + "      .add(Two)\n"
    + "      .add(Three)\n"
    + "      .build();\n"
    + "}\n");
```

**Comment by ben-manes** [comment]
good point, I missed that test case.

**Comment by JakeWharton** [comment]
I just created it! The other thing we can do is to add an `initializer` overload which accepts a `CodeBlock` and we force your to create the multi-line initializer yourself and pass it to a single `initializer` call.

I actually agree with you that calling `initializer` multiple times is probably an error.

**Comment by JakeWharton** [comment]
Re-opening to get some discussion.

**Comment by ben-manes** [comment]
A `CodeBlock` seems more natural. The change wouldn't truly reduce error prone usage since accidentally calling `initializer` multiple times will hopefully be caught during compilation or tests. That happened in my case, so without JavaDoc it looked like a precondition oversight than intended behavior.

**Comment by swankjesse** [comment]
I like enforcing that `initializer()` is called either 0 or 1 times, and adding an overload that accepts a CodeBlock. Let's do that.

Ben, wanna send a PR ?

**Comment by ben-manes** [comment]
Sure, I can't sleep and its only 5am. =)
