### ISSUE TITLE
Exclude java.lang classes from generated imports

### ISSUE THREAD

**Issue by fbiville** [square/javapoet#217]
This is a new behaviour afaik, JavaPoet does not exclude java.lang classes from imports.

I cannot see a valid reason to keep them, even custom classes created in this package would trigger a SecurityException during classloading.

**Comment by kenzierocks** [comment]
#206?

**Comment by eamonnmcmanus** [comment]
I think the idea is that if you reference java.lang.String, it imports java.lang.String in case you might also have a class called String in the same package as the class being written. To my mind, defaulting to doing that is wrong. There are other cases that lead to ambiguity and that can't be fixed the same way. For example, if a parent class has a nested class called String, then a reference to plain String refers to that, even with the explicit import. So given that you can't protect people against all of the horrible consequences of reusing class names from java.lang, I think the default should be not to try to protect against any.

**Comment by fbiville** [comment]
That's right, there's actually a TODO for that (see `CodeWriter`):

```
// TODO(jwilson): omit imports from java.lang, unless their simple names is also present in the
//     current class's package. (Yuck.)
```

**Comment by fbiville** [comment]
Thanks @kenzierocks for pointing out the duplication, that configuration option suits my usecase well.

**Comment by eamonnmcmanus** [comment]
Regarding the TODO, I don't see how that can possibly be done. How does JavaPoet know what names will be present in the current package when the code being written is compiled? Some of them might not have been written yet.

This is unfortunately a Hard Problem, which applies to much more than java.lang. The option to handle java.lang specifically seems like a band-aid.

**Comment by fbiville** [comment]
You

**Comment by swankjesse** [comment]
There's an option to suppress 'em if you like. The reason I've chosen to _include_ `java.lang` imports by default is that it's a safer choice.

Suppose you're using a  generating code from a source dataset named `application.proto`. If that `.proto` gains a message named `System`, your build breaks if your generated code references `java.lang.System`.

(My team sees this giant headache all the time with the awful `.proto` compiler we're using for C++ and Objective C. We'll add a field name that makes perfect sense for our application, and our Java program will work fine. But the Objective C folks will suffer a build break because of a keyword collision, and we need to roll back the Java changes.)

**Comment by eamonnmcmanus** [comment]
I continue to think that this is a half-measure. I think it would make more sense for the API to provide some way of controlling what gets imported explicitly. Perhaps an interface like
```java
public interface ImportControl {
  boolean useImport(String pkg, String cls);
}
```
and a default implementation of it that users can delegate to from their own, say this:
```java
public class DefaultImportControl implements ImportControl {
  private final String currentPackage;
  public DefaultImportControl(String currentPackage) {
    this.currentPackage = currentPackage;
  }
  @Override
  public boolean useImport(String pkg, String cls) {
    return !pkg.equals("java.lang") && !pkg.equals(currentPackage);
  }
}
```

This would not be called if we had already determined that a given name was ambiguous, of course.

Meanwhile I still think the current default is not good. Most users are going to be working in an environment where they can expect that people won't be doing stupid things like reusing names from java.lang. And even when that is not the case, we are still not protecting them from the other cases I mentioned.

A simpler alternative would be an option never to use imports at all, for when it is not clear that they will be safe. That is guaranteed to work, even if the resultant code will be ugly.

[Well, you can still get grief if the generated code has parameters or variables called `java` or `com` or whatever, but maybe we can handle those the same as reserved words.]

**Comment by swankjesse** [comment]
Yup. Just so I'm clear, the other case is when an enclosing superclass has a nested class, right?

```
package gov.tsa;

import java.util.Map;
import gov.homelandsecurity.Entry;

interface VisitedCountriesMap extends Map {
  Entry lastUsEntry(); // resolves to java.util.Map.Entry
}
```

**Comment by eamonnmcmanus** [comment]
Yes. We had to change the AutoValue code to detect that case, which was possible because that code has its own import management logic. I don't see how it would be possible for JavaPoet to do it in general. For example, the superclass might not exist yet.

**Comment by swankjesse** [comment]
Gotcha.

For the AutoValue case, the superclass is in `Types`, so in theory we could consult that in the importer. That would be nice behavior, though currently a `JavaFile` being emitted doesn't have access to the `Types` instance.

An alternative to `ImportControl` for the general case is to give the application the option to describe the classes-being-extended. If you're generating them in the same pass, we can also do the right thing given just a little context.
