### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by justjacksonn** [square/javapoet#223]
I know this should be easy enough to figure out, but your README should include some basic build instructions. I did git clone the project, and when I run mvn install or mvn clean compile, etc.. I keep getting told artifact for google.truth can't be found. We have an internal maven repository... I am no expert in maven, do you need to specify an external repository perhaps in the pom file? It seems to try to hit our internal repository only, not sure how to get around that.

**Comment by wokkaflokka** [comment]
Throwing in my $0.02...I did not have that issue when building this library -- neither at v1, nor when it was in snapshot.

Other people might comment further, but here's some output showing me clone this repo again, build locally, and succeed.

http://puu.sh/fKVlD/0d7fa5742c.png
and
http://puu.sh/fKVt3/156e05eda9.png
(apologies for multiple screenshots, it didn't all fit on one)

**Comment by justjacksonn** [comment]
Oddly enough, I went to the Releases tab, grabbed the 1.0 zip, and that built fine. Not sure, I'll try again when I am not at the office... maybe corporate firewall blocked something.

**Comment by JakeWharton** [comment]
We pointed at 0.25 of Truth for the 1.0 release. There's no reason to be
pointing at a snapshot as far as I can see.

**Comment by justjacksonn** [comment]
Hmm.. that may be worthy Jake.. I just downloaded the zip file from main page, and get the same problem again.. cant find Truth dependency. Maybe the fix is to point that dependency to something other than the snapshot?

**Comment by JakeWharton** [comment]
Yes. Will fix.
