### ISSUE TITLE
Create an annotation type

### ISSUE THREAD

**Issue by petitpre** [square/javapoet#232]
I want to generate a new java annotation type, something like :

```
TypeSpec.annotationBuilder("MyAnnotation")
            .addModifiers(Modifier.PUBLIC)
            .addMethod(
                        MethodSpec.methodBuilder("test")
                        .addModifiers(Modifier.PUBLIC)
                        .defaultValue("0")
                        .returns(int.class).
            );
```

It should generate :
```
public @interface MyAnnotation {
    public int test() default 0;
}
```

**Comment by swankjesse** [comment]
Neat. Wanna send a pull request? Start with a test in TypeSpecTest!

**Comment by petitpre** [comment]
Great!

Thanks to this PR, we now have a working version of "spooet" (<https://github.com/SpoonLabs/spooet>)

Spooet is a bridge between javapoet and Spoon (<https://github.com/INRIA/spoon>).
Spoon is a java library for analyzing and transforming Java source code.
Spooet pretty-prints a Spoon AST using the javapoet fluent API.

What do you think?

**Comment by swankjesse** [comment]
Neat!
