### ISSUE TITLE
`nextControlFlow` produces `else` without space before bracket

### ISSUE THREAD

**Issue by ben-manes** [square/javapoet#234]
This is a minor formatting bug that isn't covered by a test. It produces correct code, but was a surprise when looking at the generated output.

I didn't test the sample below, but simplifies from a [usage](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/CacheSelectorCode.java).
```java
CodeBlock block = CodeBlock.builder()
    .beginControlFlow("if (true)")
        .addStatement("int x = 1")
    .nextControlFlow("else")
        .addStatement("int x = 2")
    .endControlFlow()
    .build();
```

Produces an output like,
```java
if (true) {
  int x = 1;
else{
  int x = 2;
}
```

**Comment by eamonnmcmanus** [comment]
Isn't this the same as #224? Are you using the latest version?

**Comment by JakeWharton** [comment]
I do not see this behavior: https://github.com/square/javapoet/pull/235

**Comment by ben-manes** [comment]
Okay, sounds like its been fixed in the snapshot (using 1.0)

**Comment by JakeWharton** [comment]
Ah, gotcha. We'll get a release out soon then!

**Comment by ben-manes** [comment]
Just ran into a bug with `nextControlFlow` that is fixed in master, so a new release would be nice to avoid SNAPSHOT dependencies.
