### ISSUE TITLE
Argument index

### ISSUE THREAD

**Issue by svenjacobs** [square/javapoet#238]
`beginControlFlow()`, `addStatement()` etc. should support `String.format()` like argument indices so that reoccurring arguments don't have to be added multiple times. For example:

```java
.beginControlFlow("if (%1$L == null || %1$L == %2$S)", varName, someValue)
```

**Comment by eamonnmcmanus** [comment]
I've also felt the need for this, though I think a syntax like `$1L` might be better than `%1$L`.

**Comment by swankjesse** [comment]
Agreed. `$1L` looks good. And that's what we'll do unless anyone has other ideas!

**Comment by svenjacobs** [comment]
Great, I'm fine with that! :)

**Comment by sormuras** [comment]
No other idea. Would be a great feature. +1 for `$1L`

**Comment by swankjesse** [comment]
(Pull requests welcome.)
