### ISSUE TITLE
Easier enum adding for AnnotationSpec

### ISSUE THREAD

**Issue by kenzierocks** [square/javapoet#239]
Right now you have to do `addMember("value", "$T.$N", ElementType.class, ElementType.ANNOTATION_TYPE.name())` or similar (`addMember("value", "$T.$N", ElementType.class, "ANNOTATION_TYPE")`), both of which are either very clunky or not easily written. If possible, I would like a `addMember("value", ElementType.ANNOTATION_TYPE)` or similar. Perhaps CodeBlock could also take in enums via `$E` or something.

**Comment by swankjesse** [comment]
I think our current API, while clunky, is pretty obvious and fits well with the rest of JavaPoet. No action to take here.
