### ISSUE TITLE
Converting Specs to Builders

### ISSUE THREAD

**Issue by kenzierocks** [square/javapoet#240]
Right now, you have to recreate the Builder from the spec manually, which is not easy for more complex things like `MethodSpec` and requires static utility functions for maintaining. A simple fix would be to add a new `*Spec.builder()` instance method that converts that Spec instance to the respective builder type.

**Comment by swankjesse** [comment]
Yes, definitely. If you'd like to send a PR, we'll accept it! Otherwise it'll show up, but not urgently.

**Comment by kenzierocks** [comment]
Attempting to write a PR, unfortunately m2e isn't working it seems, failing the dependency resolution . `Missing artifact com.sun:tools:jar:1.8.0_31`.

**Comment by kenzierocks** [comment]
Managed to convince eclipse. Working on PR.

**Comment by kenzierocks** [comment]
I've discovered a conflict with the static builder methods that take no arguments, should I chose a different name like `toBuilder`?

**Comment by JakeWharton** [comment]
Could also be buildUpon as another candidate. This is used by Android's Uri
class.
