### ISSUE TITLE
Extract interfaces for the fluent API

### ISSUE THREAD

**Issue by petitpre** [square/javapoet#245]
We develop Spoon (<https://github.com/INRIA/spoon>), a java library for analyzing and transforming Java source code.

We would like to write Spoon transformations using the javapoet fluent interface. For this, it would be interesting to extract interfaces of the javapoet API. We would implement those interfaces on top of Spoon.

Then we could write generative code that is can be emitted with javapoet *and* that can produce a Spoon AST.

**Comment by swankjesse** [comment]
Interesting! Would you parse the code blocks?

**Comment by petitpre** [comment]
Spoon already offers some mechanisms to parse and analyse code blocks.

We would add a simple mechanism to generate new AST elements, and we think using Javapoet fluent API could be a good choose.

**Comment by swankjesse** [comment]
Not going to take action here. If you'd like to try it, please fork!
