### ISSUE TITLE
support of not-yet-existing types

### ISSUE THREAD

**Issue by tomaszalusky** [square/javapoet#246]
Hi,

I need to generate class `Foo` and class `Hoo` whose field is of type `Foo`. Seems to me that only existing types are possible to use in `FieldSpec` since only `Type` or `TypeName` can be passed to `FieldSpec.builder` (or directly into `addField`). AFAIK, neither `Type` nor `TypeName` can be constructed for nonexisting types.

If I'm not missing something, it would be great if JavaPoet made possible to define type just as `String`. In other words, it would trust user to pass something which he believes will be compilable in the future and let user be responsible for it.

I am aware this request can go pretty deeply (parsing generics, Java8 type annotations, automatic adding into set of imports), so I am interested if it is in compliance with JavaPoet philosophy.

(Currently, there's possible workaround to reflectively instantiate `TypeName` and abuse it's `keyword` field, which is awkward, fragile and doesn't handle imports or complicated types.)

Thanks for your opinion!

**Comment by kenzierocks** [comment]
Does ClassName work for you?

**Comment by tomaszalusky** [comment]
Yes, I missed overload `ClassName.get(String,String,String...)`. I finally found it also in [documentation](https://github.com/square/javapoet#t-for-types). Sorry for issue, my mistake. Thanks for hint and feel free to close.
