### ISSUE TITLE
API for annotation construction

### ISSUE THREAD

**Issue by vbauer** [square/javapoet#247]
I faced with critical issue in my project: it is necessary to construct annotation classes, but as I can see it is impossible to do.. `TypeSpec` class does not have this feature:

* TypeSpec.interfaceBuilder
* TypeSpec.classBuilder
* TypeSpec.enumBuilder
* TypeSpec.anonymousClassBuilder

It will be great to have something like `TypeSpec.annotationBuilder` or an additional flag for `TypeSpec.interfaceBuilder`.

**Comment by tbroyer** [comment]
It was recently added (#232) but not yet released.

**Comment by vbauer** [comment]
Thank you for information!
