### ISSUE TITLE
How can I add generic Parameter?

### ISSUE THREAD

**Issue by jiqimaogou** [square/javapoet#250]
addParameter method must accept a class, but generic Parameter has not class, what can I do?

**Comment by JakeWharton** [comment]
Can you ask this question on StackOverflow and paste the link here?

**Comment by pieterdegraeuwe** [comment]
I have (i think) the same question.
I've added it to StackOverfloxw: http://stackoverflow.com/questions/29117410/how-to-add-the-any-type-questionmark-in-javapoet

Thanks
