### ISSUE TITLE
How do I add an annotation to an enum value

### ISSUE THREAD

**Issue by inder123** [square/javapoet#253]
For Json2Java project, I need to define Gson SerializedName annotation on Enum values. How do I do that? I only see addEnumConstant() method

**Comment by swankjesse** [comment]
Not currently possible. I think what we probably want is to change it so you can use this overload:

 ```
    public Builder addEnumConstant(String name, TypeSpec typeSpec) {
```

And the typeSpec there can carry annotations that get attached to the enum. The one catch is that right now we forbid annotations on anonymous types; we could just relax that now that we have a use case for it.

Wanna send a pull request? You can copy+paste `TypeSpecTest#enumWithSubclassing` as a starting point!

**Comment by inder123** [comment]
I ran into a bunch of other issues trying to use JavaPoet. 
For example, to define a field, you require me to specify a Type. I don't have a type, only a name.

**Comment by JakeWharton** [comment]
We require a `Type` or `TypeName`, the latter of which doesn't require the actual type to be available yet but serves as a reference to everything needed to refer to it.

**Comment by kenzierocks** [comment]
This project does need much more documenting, I might PR a bunch of javadocs.

**Comment by swankjesse** [comment]
@kenzierocks please don't send Javadocs that don't add value.
https://publicobject.com/2007/08/stop-writing-redundant-javadoc.html

What was missing? I tried to make our README comprehensive.

**Comment by kenzierocks** [comment]
Oh, I just don't like swapping between the README and my IDE, plus it's not instantly clear where to get some things, like ClassName for TypeName parameters.

**Comment by swankjesse** [comment]
Example?

**Comment by swankjesse** [comment]
(or just send a pull request actually!)
