### ISSUE TITLE
Redundant import for not-yet-existent class causes compilation error

### ISSUE THREAD

**Issue by jenzz** [square/javapoet#255]
Hi there!

The following snippet (static imports omitted):

```
TypeSpec classA = classBuilder("ClassA").build();
JavaFile javaFileA = builder(packageName, classA).build();
javaFileA.writeTo(processingEnv.getFiler());

TypeSpec classB = classBuilder("ClassB")
        .addMethod(
            methodBuilder("methodB")
            .addParameter(ClassName.bestGuess("ClassA"), "classA")
            .build())
        .build();

JavaFile javaFileB = builder(packageName, classB).build();
javaFileB.writeTo(processingEnv.getFiler());
```

generates the following two classes:

```
class ClassA {
}
```

and

```
import ClassA;

class ClassB {
  void methodB(ClassA classA) {
  }
}
```

The import in `ClassB` is obviously redundant since both classes are being generated in the same package. It cannot be resolved.

Is this a bug or am I misusing the `MethodSpec.Builder`?

**Comment by kenzierocks** [comment]
Next time this should probably be on SO, but to answer it quickly you want `ClassName.get(packageName, "ClassA")` so that it knows the package.

**Comment by jenzz** [comment]
Thanks @kenzierocks!

Using `ClassName.get()` instead of `ClassName.bestGuess()` solves the problem.
