### ISSUE TITLE
Compile library using Java 6

### ISSUE THREAD

**Issue by vbauer** [square/javapoet#256]
The most part of Java projects are still based on the Java 6, so it will be great to change `java.version` to 1.6.

**Comment by JakeWharton** [comment]
You can still emit Java 6-compatible code, but I don't see why we would need to support Java 6 since it's long EOL.

**Comment by swankjesse** [comment]
Agreed! We want to push forward!

**Comment by vbauer** [comment]
Actually, almost all JEE projects work on Java 6. It's great that you want to be in trend, but it will be useful to add information about Java version in the README file. Now it looks like, that I have to remove javapoet from my project and completely rewrite it.

**Comment by JakeWharton** [comment]
But you still run JDK 8, right? JavaPoet is most likely to be run in static tooling or annotation processors inside of the java compiler. Even if you are compiling code for Java 6 VMs you can run JDK 8.

**Comment by JakeWharton** [comment]
Run JDK 8 locally, I mean.

**Comment by JakeWharton** [comment]
(Android is basically Java 6 but everyone still runs JDK 8)

**Comment by vbauer** [comment]
Yes, I'm thinking about it. It's impossible to change JVM on production servers, but probably we can try to update JDK on build agents. I hope there are no usage of some internal SUN API...

**Comment by swankjesse** [comment]
@vbauer Retro! I remember installing Java 6 on my Tandy using a stack of eleven floppy disks. 💾
