### ISSUE TITLE
no way to get the generated class name

### ISSUE THREAD

**Issue by panfayang** [square/javapoet#258]
When generating AutoValue code for Foo.java, I need a method with header "public static Foo create()". Since "Foo" is the class name, there's no way to get it using MethodSpec.returns().

**Comment by JakeWharton** [comment]
This sounds like a dupe of #197.

You can use `ClassName` to create arbitrary `TypeName` instances, even for those which do not exist yet.

**Comment by panfayang** [comment]
Thank you! dupe indeed.

**Comment by panfayang** [comment]
But still, why allowing users to create arbitrary classes, when you guys went through so, so much to make sure people don't do that...

**Comment by JakeWharton** [comment]
I don't understand the question.

**Comment by panfayang** [comment]
Sorry, bad phrasing on my part, and a similar complaint was filed in #227. Look forward to "something to ease this"!
