### ISSUE TITLE
Escaping $$ in CodeBlock.Builder.add()

### ISSUE THREAD

**Issue by T-Spoon** [square/javapoet#260]
I'm generating some classes with $$ in the class name, but it seems the second '$' is being stripped.

Code:
```
.addStatement("...new $T())", ClassName.get("kickflip", "Event$$KickflipAdapter"));
```
Expected Result:  
```
 ... new kickflip.Event$$KickflipAdapter();
```
Actual Result:  
```
... new kickflip.Event$KickflipAdapter();
```

Is there some way to escape the second $ symbol?  Or is there another way of getting the expected result?

**Comment by kenzierocks** [comment]
This appears to be a bug, `$` should be untouched in `CodeBlock` arguments.

**Comment by kenzierocks** [comment]
Can't reproduce:
```
public class BugTest {

	@Test
	public void test() {
		CodeBlock c = CodeBlock
				.builder()
				.addStatement("new $T()",
						ClassName.get("a.simple", "Test$$Class")).build();
		assertEquals("new a.simple.Test$$Class();\n", c.toString());
	}

}
```

**Comment by T-Spoon** [comment]
@kenzierocks Ah, it seems I can reproduce it using the code as an initializer for a FieldSpec.  The code below should reproduce the issue.
```
String c = CodeBlock
                .builder()
                .addStatement("new $T()", ClassName.get("a.simple", "Test$$Class"))
                .build()
                .toString();

        TypeSpec spec = TypeSpec.classBuilder("Test")
                .addField(
                        FieldSpec.builder(Integer.class, "Test")
                                .initializer(c)
                                .build()
                )
                .build();

        JavaFile.builder("test", spec)
                .build()
                .writeTo(System.out);
```

**Comment by JakeWharton** [comment]
`$$` is an escape sequence for `$` to prevent the custom string formatter from interpreting it (e.g., as `$T`, `$S`, etc.)

If you want two successive `$` characters then you need to use `$$$$` (four instances).

**Comment by T-Spoon** [comment]
Damn, that should have occurred to me.

Maybe it's worth including a small sample like that in the docs?  Since a lot of generated classes use the `$$` format.

Cheers for the help anyway!

**Comment by JakeWharton** [comment]
Yep. A sample is a good idea.
