### ISSUE TITLE
Annotation with type member from TypeName does not add ".class"

### ISSUE THREAD

**Issue by lukaspili** [square/javapoet#263]
Hi,

I'm using JavaPoet within my annotation processor.
I have a simple annotation that declares a `Class value()`
I get that annotation in the annotation processor, and get the class contained in its value().
Because of the annotation processor, I can't get the actual Class but only a TypeMirror.

Next, I want to declare a new annotation with JavaPoet, that contains the previous retrieved class (or TypeMirror). 

```java
TypeMirror typeMirror = // get the TypeMirror
TypeName typeName = ClassName.get(typeMirror); // convert it to TypeName

TypeSpec typeSpec = TypeSpec.interfaceBuilder("MyInterface")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)

                // Add the generated annotation
                .addAnnotation(AnnotationSpec.builder(MyAnnotation.class)
                        .addMember("dependencies", "$T", typeName)
                        .build())
                .build();
```

The expected result is:

```java
@MyAnnotation(
      dependencies = MyClass.class
)
public interface MyInterface {
}
```

However the actual result is missing the ".class"

```java
@MyAnnotation(
      dependencies = MyClass
)
public interface MyInterface {
}
```

The current workaround I found is to provide a CodeBlock directly, but I guess it's not the right way to do it.

```java
AnnotationSpec.builder(MyInterface.class)
    .addMember("dependencies", CodeBlock.builder().add("$T.class", typeName).build())
```

Thanks

**Comment by kenzierocks** [comment]
For the first one you probably want `$T.class`. `$T` only handles importing the type.

**Comment by swankjesse** [comment]
Actually, explicitly adding `.class` is exactly the way to do it!

**Comment by lukaspili** [comment]
Ok thanks!
