### ISSUE TITLE
Javadoc output inconsistency

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/javapoet#264]
Sample code with JavaPoet

```java
something
  .addJavadoc("JavaPoet is ***ing awesome!") // this is true
```

Actual output:

```java
/**
* JavaPoet is ***ing awesome! */
```

Expected output, variant 1:

```java
/** JavaPoet is ***ing awesome! */
```

Expected output, variant 2:

```java
/**
 * JavaPoet is ***ing awesome! 
 */
```
Variant 1 more flexible because it allows one-lined javadocs, but it'll also require additional `\n`s for result equals to variant 2.

**Comment by swankjesse** [comment]
Yes, we require trailing `\n` characters on Javadoc. This is annoying.

**Comment by artem-zinnatullin** [comment]
@swankjesse so, do you want to switch to one of suggested variants? I can prepare PR for this

**Comment by swankjesse** [comment]
Line wrapping is a hard problem.

For example, if you provide a 300 character string to the Javadoc, we aren't going to break that line at word boundaries. Instead, we expect the application developer to do all the line wrapping.

How about this: if the input Javadoc has no line breaks, then the output Javadoc should also have no line breaks. It's a single line comment as per your variant 1. Otherwise we retain the current behavior, and require the developer to provide the trailing `\n` character.

The hard part is detecting whether the input Javadoc has no line breaks. This is nontrivial because of `$L` placeholders which could contain `\n` characters.

**Comment by artem-zinnatullin** [comment]
May be it's better to provide one expected behavior, for example variant 1 and leave formatting up to application developer?

> How about this: if the input Javadoc has no line breaks, then the output Javadoc should also have no line breaks. It's a single line comment as per your variant 1. Otherwise we retain the current behavior, and require the developer to provide the trailing \n character.

It's tricky not only for JavaPoet but also for application developer who has to keep in mind that if he used `\n` in Javadoc -> first new line will be added automatically but he also has to provide the trailing `\n` character.

Example: Javadoc itself does not contain `\n` characters, but formatting arguments can be passed from some source, like user input and application developer would not know how Javadoc will be generated, he would has to add some conditions for adding `\n` in the beginning.

Personally, I'd prefer simple, fully customizable and obvious behavior — variant 1

**Comment by JakeWharton** [comment]
Obvious behavior is variant 2, not 1. Explicitly provide the leading and trailing newlines and strip any first-item leading and last-item trailing newlines in the actual Javadoc.

**Comment by artem-zinnatullin** [comment]
50/50, it's formatting thing, like indend which is often 4 spaces but default in JavaPoet and used in most of Squares's projects — 2 spaces.

Variant 2 used more often, but how would it be possible to generate variant 1 if variant 2 will be default? Overload or something like `addRawJavadoc()`?

**Comment by JakeWharton** [comment]
Simple: you can't. There's all kinds of formatting things that I dislike in Javapoet's output but it's simple and deterministic. The principle of least surprise comes in here, and it's consistent with JavaWriter's behavior.

**Comment by artem-zinnatullin** [comment]
Okay, playing devil's advocate done :)

I can prepare PR for variant 2 in my free time if you don't mind, @swankjesse any additions?

**Comment by swankjesse** [comment]
I actually don't think we want variant 2. I like the trailing newlines in the caller's code. I think if we get input that doesn't have any newlines, then we can generate a single-line Javadoc block.

**Comment by swankjesse** [comment]
No action to take here.
