### ISSUE TITLE
Is it possible to create static block initializers for a class?

### ISSUE THREAD

**Issue by jaikiran** [square/javapoet#266]
I had a look at the javapoet code and even some documentation, but I haven't been able to find a way where I can add a static initializer block to a class. Something like this:

       public class Foo {
           private static Map<String, String> bar = new HashMap();
           // creation of this block through javapoet is what I'm interested in
           static {
                   bar.put("blah", "hello world");
           }
           .....
       }

P.S: Not sure if github issues is the right place to ask these questions. Couldn't find any other forum. Feel free to direct me to a relevant forum/group, if there's one.

**Comment by tomxor** [comment]
There is a pending PR for that #257

**Comment by jaikiran** [comment]
Thanks for pointing me to that PR! That feature indeed is going to be useful.
