### ISSUE TITLE
JavaFile.toJavaFileObject()

### ISSUE THREAD

**Issue by jgustie** [square/javapoet#267]
I have been working on some tests using [Compile Testing](https://github.com/google/compile-testing) which will accept a `javax.tools.JavaFileObject`; it occurred to me that it might be nice if there were a `JavaFile.toJavaFileObject()` method that could be used to pass generated code into the `java.tools.JavaCompiler`.

This would simplify using JavaPoet for generating the code being input to the compilation process (which otherwise might be done using Compile Testing's `JavaFileObjects.forSourceLines(...)`). It may also simplify isolating the tests from code formatting changes in JavaPoet: an annotation processor using JavaPoet could be validated using Compile Testing's `generatesSources(...)` method with input also backed by JavaPoet.

The obvious work around is just using something like `JavaFileObjects.forSourceLines(javaFile.packageName + '.' + javaFile.typeSpec.name, Splitter.on('\n').split(javaFile.toString()))` in the tests; but that assumes you have Compile Testing (in theory this does not need to be restricted to test environments). Looking at `JavaFileObjects`, just subclassing `javax.tools.SimpleJavaFileObject` to wrap a `JavaFile` would be relatively straight forward (I can try to get a pull request in if there is any interest).

**Comment by swankjesse** [comment]
Not sure how actionable this is.

If you're using Compile Testing, the workaround is pretty good, right? Maybe that project could add a method like `JavaFileObjects.forSource(String, String)`.

If you aren't using Compile Testing, I don't know why you'd want to get a `JavaFileObject` instead of going through `Filer`. What's the use case?

**Comment by jgustie** [comment]
I suppose the `Splitter` part of the workaround isn't necessary, the `forSourceLines` method in question takes a varargs.

A `toJavaFileObject()` would be kind of like the opposite of what you currently get from a `Filer`: the `JavaFile.writeTo(Filer)` method uses the `Writer` of the `JavaFileObject` as opposed to the `Reader`/character content that you would need to pass a `JavaFile` _into_ the compiler:

```
JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
DiagnosticCollector<JavaFileObject> diagnosticCollector = new DiagnosticCollector<>();
JavaFileManager fileManager = compiler.getStandardFileManager(diagnosticCollector, Locale.getDefault(), StandardCharsets.UTF_8);
CompilationTask task = compiler.getTask(null, 
    fileManager, diagnosticCollector,
    Collections.emptySet(), Collections.emptySet(),
    Collections.singleton(javaFile.toJavaFileObject()));
task.call();
```

**Comment by swankjesse** [comment]
Sorry for being slow: what's the use case? Typically we expect these APIs to be used by annotation processors and other build tools.

**Comment by jgustie** [comment]
No apologies needed, sometimes I get so buried in context when I finally come up for air I forget everyone else wasn't there with me :)

My primary use case is writing integration tests for an annotation processor I wrote using JavaPoet: imagine an annotation processor that uses JavaPoet to generate an enum with all of the public method names from a class; taking the code above a little bit further I would like to have something like:

```
// Compiler input
MethodSpec foo = MethodSpec.methodBuilder("foo").addModifiers(Modifier.PUBLIC).build();
TypeSpec fooBar = TypeSpec.classBuilder("FooBar").addModifiers(Modifier.PUBLIC).addMethod(foo).build();
JavaFile javaFile = JavaFile.builder("com.example.test", fooBar);

// Expected generated output
TypeSpec fooBarMethods = TypeSpec.enumBuilder("FooBarMethods")
    .addModifiers(Modifier.PUBLIC)
    .addEnumConstant("FOO")
    .build();
JavaFile generatedJavaFile = JavaFile.builder("com.example.test", fooBarMethods);

// <Insert snippet from previous comment here> ...but assume StandardJavaFileManager
JavaFileObject generated = fileManager.getJavaFileObjects("com/example/test/FooBarMethods.java").next();

// Make this guy a little more smart then just comparing full strings, because that could get painful
assertJavaFileEquals(generated, generatedJavaFile.toJavaFileObject());
```

So I used `toJavaFileObject()` both to generate the compiler input and to create a like-typed object for verification on output. The nice part about this is that since the `FooBarMethods` enum code was also generated by JavaPoet (in it's more conventional role from within an annotation processor), the tests would be less susceptible to failing due to code formatting changes and things of that nature.

In this example, the use of JavaPoet is decidedly static: i.e. "here is the input; here is the output". I would like to start exploring more data driven tests: e.g. "given the method names x, y and z and the expected enum constant names x', y' and z', generate the input and output code to test".

For my annotation processors that are more tightly tied to the compiler model and the processing environment, I am also investigating a similar mechanism for functional tests of shared code, in those cases the JavaPoet usage is much more about generating more dynamic code with the expectation of producing specific `javax.lang.model` models (which would otherwise be a huge pain to mock up).

**Comment by swankjesse** [comment]
Gotcha. I think this is a good idea, but I think it goes in the compile-testing project. JavaPoet makes it easy to get a string for a source file; compile-testing knows how to make assertions about that string.

**Comment by jgustie** [comment]
I definitely agree that assertions about source can stay in a separate test project. The piece that I feel is missing is that there is currently no way to get a `JavaFile` into a `javax.tools.JavaCompiler` without having to write your own `javax.tools.JavaFileObject` (or borrowing the one from compiler-testing which does take a string). The built-in compiler APIs do not have anything for accepting Java source code as a string and JavaPoet does not have anything for producing the `JavaFileObject` required as input by the built-in compiler APIs. This isn't a problem when the source code is generated by an annotation processor initiated by the compiler (as you said: use the `Filer` and it gets picked up in the next round), it is only a problem when you want to kick off the compilation with generated code.

Here is some code that I believe would allow `JavaFile` instances to be passed into a `JavaCompiler.getTask` call (imports from `javax.tools`, `java.io` and `java.net`):

```java
  public JavaFileObject toJavaFileObject() {
    URI uri = URI.create((packageName.isEmpty()
        ? typeSpec.name
        : packageName.replace('.', '/') + '/' + typeSpec.name)
        + Kind.SOURCE.extension);
    return new SimpleJavaFileObject(uri, Kind.SOURCE) {
      private final long lastModified = System.currentTimeMillis();
      @Override public String getCharContent(boolean ignoreEncodingErrors) {
        return JavaFile.this.toString();
      }
      @Override public InputStream openInputStream() throws IOException {
        return new ByteArrayInputStream(getCharContent(true).getBytes());
      }
      @Override public long getLastModified() {
        return lastModified;
      }
    };
  }
```

If you would like I can turn this into a pull request, if not, I think I've given this horse a good enough beating :)

**Comment by swankjesse** [comment]
@jgustie make it so. Pull request welcome.
