### ISSUE TITLE
How to create Typename from a String?

### ISSUE THREAD

**Issue by jiqimaogou** [square/javapoet#270]

**Comment by kenzierocks** [comment]
[`ClassName.bestGuess(String)`](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/ClassName.java#L122)

**Comment by JakeWharton** [comment]
Also `ClassName.get` and static methods on `ParameterizedTypeName` and `WildcardTypeName`. Look at the tests for examples of these.
