### ISSUE TITLE
How do I convert AnnotationMirror to AnnoationSpec? and convert ExecutableElement to MethodSpec?

### ISSUE THREAD

**Issue by jiqimaogou** [square/javapoet#273]

**Comment by sormuras** [comment]
Have a look  at [AnnotationSpec.java#L101](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/AnnotationSpec.java#L101) in current master HEAD and [MethodSpec.java#L172](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/MethodSpec.java#L172) for an example of the second one - or here [Poetry](https://github.com/sormuras/javapoet/blob/poetry/src/main/java/com/squareup/javapoet/Poetry.java).

**Comment by jiqimaogou** [comment]
thank you, but if I just want to copy not overriding the method, (overriding exception @override annotation).

**Comment by sormuras** [comment]
Then you just copy the fields 1:1 from the source ExecuteElement/ExecutableType into the MethodSpec.Builder instance.

**Comment by swankjesse** [comment]
Would it be sufficient to offer a method to remove the offending `@Override` annotation?

**Comment by sormuras** [comment]
What about `MethodSpec.get(...)` implementation that just copies all attributes from ExecutableElement et al and returns a Builder. And convenient `MethodSpec.getOverriding(...)` that adds the `@Override` annotation if needed?

**Comment by swankjesse** [comment]
Like this?

```
public static Builder MethodSpec.methodBuilder(String name)
public static Builder MethodSpec.methodBuilder(ExecutableElement copyFrom)
public static Builder MethodSpec.overriding(ExecutableElement method)
```

**Comment by sormuras** [comment]
Ja-in.

With `MethodSpec.overriding(ExecutableElement method)` only calling `MethodSpec.methodBuilder(ExecutableElement copyFrom)` and add the `@Override` annotation. And then, add a `MethodSpec.implementing(ExecutableElement abstractMethod)` as well. ;-)

All those not-so-trivial methods yield for an own class, don't they? Especially, when it comes to helper functions around `javax.lang.model` utilities like `getPackageOfElement()` and others. Add some references to Types/Elements and you'll end up with large amount of code in JavaPoet core classes, that does parsing work.

So, I'm actually talking about moving all(!) javax.lang.model-related code out off XyzSpec classes into JavaxModelUtil-thing. Codename: **Poetry**. That would leave the XyzSpec-API clean for the uses-cases shown at the [README.md]( https://github.com/square/javapoet/blob/master/README.md). Annotation processors would use the help of Poetry and if I understand https://github.com/square/javapoet/issues/277 correctly, there's some need for a reflecting parser as well. Without type-safety here.

**Comment by swankjesse** [comment]
Would the new classes be public? As far as the public API goes, it's easier if everything that will give you a `MethodSpec` is in `MethodSpec`, even if internally there's a helper class to do the `javax.lang.model` heavy lifting.

**Comment by sormuras** [comment]
Fair enough point. Feels like having short-cuts for the big parsing tasks.

But, sometimes, they won't feel lightweight: calling `public MethodSpec.Builder overriding(ExecutableElement method, DeclaredType containing, Elements elements, Types types) {...}` with 4 parameters is imho not so clean as a user controllable Poetry tool that collects common references in the constructor and provides simple 1:1 `builder` methods for each Spec and a lot of convenient functions like overriding(), implementing(), ...
```java
  @Test public void overrideEverything() {
    Poetry poetry = new Poetry(compilation.getElements(), compilation.getTypes());
    TypeElement classElement = getElement(Everything.class);
    DeclaredType classType = (DeclaredType) classElement.asType();
    ExecutableElement methodElement = getOnlyElement(methodsIn(classElement.getEnclosedElements()));
    MethodSpec method = poetry.overriding(methodElement, classType).build();
    assertThat(method.toString()).isEqualTo(
        ""
            + "@java.lang.Override\n"
            + "@java.lang.Deprecated\n"
            + "protected <T extends java.lang.Runnable & java.io.Closeable> "
            + "java.lang.Runnable everything("
            + "@com.squareup.javapoet.PoetryTest.Nullable java.lang.String arg0, "
            + "java.util.List<? extends T> arg1) "
            + "throws java.io.IOException, java.lang.SecurityException {\n"
            + "}\n");
  }
```

I'll start a branch, that initially starts with a package-private `JavaxLangModelUtil`. Further Poetry discussion over there?

**Comment by swankjesse** [comment]
Not sure we want to take any action here.
