### ISSUE TITLE
Support for StatementSpec

### ISSUE THREAD

**Issue by frko** [square/javapoet#275]
AS I've been building abstractions on top of JavaPoet I feel the need for an StatementSpec so I can precompose a statement and pass it around only to later apply it to a method spec;

**Comment by tbroyer** [comment]
Can't you just use a `CodeBlock`?

**Comment by frko** [comment]
Seems about right indeed. The wiki docs do not contain a reference to a separate codeblock instance so I assumed that it worked identical to statement - with direct evaluation. Will evaluate the working, thanks for the swift response.
