### ISSUE TITLE
Inverse generation (Generating javapoet code from classes )

### ISSUE THREAD

**Issue by cemo** [square/javapoet#277]
It would be nice to inverse code generation for debugging and learning purposes. Sometimes starting from scratch is really cumbersome and having a starting implementation would be awesome. 

BTW new implementation is very nice and readable. Thanks for sharing.

**Comment by sormuras** [comment]
Do you mean something like:
```java
TypeSpec parse(Class<?> type) {
    String name = type.getSimpleName();
    TypeSpec.Builder builder = type.isInterface() ? 
        TypeSpec.interfaceBuilder(name) : type.isEnum() ? 
        TypeSpec.enumBuilder(name) : TypeSpec.classBuilder(name);
    Arrays.asList(type.getAnnotations()).forEach(a -> builder.addAnnotation(parse(a)));
    ...
    return builder.build();
```
or that you have a `TypeSpec` object and want to see what JavaPoet-API calls could have produced that TypeSpec?

**Comment by cemo** [comment]
I want to see what JavaPoet-API calls could have produced that TypeSpec.

**Comment by swankjesse** [comment]
Sounds like an interesting project, but not one we're going to include. No action to take here.
