### ISSUE TITLE
TypeVariableName doesn't support super

### ISSUE THREAD

**Issue by kenzierocks** [square/javapoet#283]
Type variables can use `super`, like `T super String` will accept anything that's a superclass of String. This is necessary for writing some methods.

**Comment by JakeWharton** [comment]
A wildcard can have lower bounds (and `WildcardTypeName` supports it) but from what I remember a type variable cannot (and thus `TypeVariableName` does not support it).

**Comment by JakeWharton** [comment]
Good read on it: http://www.angelikalanger.com/GenericsFAQ/FAQSections/TypeParameters.html#FAQ107

**Comment by tbroyer** [comment]
And for the reference spec: https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.4
