### ISSUE TITLE
FieldSpecs in CodeBlock

### ISSUE THREAD

**Issue by kenzierocks** [square/javapoet#288]
I think it would be nice for `CodeBlock` to emit `FieldSpecs` correctly for local variables. Currently you can do `block.add("$L", fieldSpec)` and it partially works, everything is fine except for types, which are always fully qualified (due to the call to `fieldSpec.toString()` returning fully qualified types). My two solutions are:

 - Adding a new `add` method that handles `FieldSpec` (`addLocalVariable`?)
 - Changing `$L` to handle a `FieldSpec` and import the types

I think the first would be easier to implement, but I might be wrong. If I have time, I'll write a PR for whichever one is preferred.

**Comment by swankjesse** [comment]
Why would you have a `FieldSpec` in a `CodeBlock`?

**Comment by kenzierocks** [comment]
Local variables.

**Comment by swankjesse** [comment]
Ahh. Local variables aren't fields. Don't do that.

**Comment by kenzierocks** [comment]
What's the recommended way to add annotations on local variables then?

```
@SupressWarnings("unchecked")
List<T> list = (List<T>) someObject;
```

**Comment by swankjesse** [comment]
You could probably use `$L` for the AnnotationSpec, and then `$T` for the type.

**Comment by kenzierocks** [comment]
Ok, will do that.

**Comment by saikrishnaeranti** [comment]
Is there any way by which we can keep track for local variable to avoid conflicts like repeated initialization?

**Comment by sormuras** [comment]
`CodeBlock`s are user/your realms. Keeping local variable names in a set is probably a solution.

**Comment by sormuras** [comment]
Maybe the [NameAllocator](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/NameAllocator.java) can help, too. See it's javadoc for usage example.
