### ISSUE TITLE
MethodSpec.Builder.returns(): Type or TypeName can not be applied if return type is the generated class itself

### ISSUE THREAD

**Issue by sockeqwe** [square/javapoet#294]
Hi,
if I want to generate a Builder like this:

```java
class FooBuilder {

   private int id;
   private String name;

   public FooBuilder id(int id){
       this.id = id;
       return this;
   }

  public FooBuilder name(String name){
       this.name = name;
       return this;
   }
}
```

If I want to specify the method `id(int)` or `name(String)`, how would I do that:

```java
MethodSpec.methodBuilder(field.getFieldName())
        .returns( ??? )
```

The problem is that `MethodSpec.Builder.returns()` expects `TypeName` (could be constructed with `TypeMirror`) or `Type` itself. Since `FooBuilder` has not been generate yet, there is no `TypeMirror` available nor `FooBuilder.class`. 

Have I missed something? Is there a "fallback" method I could use i.e. just passing the name of the class as String?

**Comment by JakeWharton** [comment]
This is #197. You can use `ClassName.get` with the package and name of the class to create a `TypeName` that can be used. For example, `ClassName.get("com.example", "FooBuilder");`.

**Comment by sockeqwe** [comment]
Oh, thanks! I have overlooked that one! Sorry!

**Comment by JakeWharton** [comment]
No problem. You're are neither the first nor the last to be tripped up on it. Hopefully we can come up with something per what the issue I linked described to make this case easier.

**Comment by carlochum** [comment]
I've tried using ClassName.get and I keep getting an error at build-time:

Could not find property 'ClassName' on project ':android'

Any suggestions?

**Comment by carlochum** [comment]
Never mind. Took me 3 hours to realise I was missing an import of ClassName :')
