### ISSUE TITLE
clazz.getPackage() should not be used.

### ISSUE THREAD

**Issue by rzwitserloot** [square/javapoet#295]
In regards to:

https://github.com/square/javapoet/blob/869f9dd91b6fce1133d137b5eae8ba543c92806a/src/main/java/com/squareup/javapoet/ClassName.java#L108

.getPackage(), as the spec says, doesn't HAVE to return an actual object. That doesn't mean the class file isn't in a package; it simply means the package it is in doesn't have a representable Package object by the class loader. In 'normal' java world this doesn't happen, but throw in just about any fancypants module loader and you'll run into .getPackage() returning null.

The fix is easy enough as you really don't need to call it here. To turn a j.l.Class ref into a string that would 'work' when generating java code, .getName() will get the job done as long as it isn't an array, and you can import up to the final dot without issues. However, to stick with the javapoet model of having the entire package as a single name `names.get(0)`, the outer class as `names.get(1)`, and then each subsequent inner a further element in the `names` arraylist, I suggest this fix, replacing lines 104-109:

    Class<?> top;
    for (Class<?> c = clazz; c != null; c = c.getEnclosingClass()) {
        names.add(c.getSimpleName());
        top = c;
    }
    String complexName = top.getName();
    int lastDotIdx = complexName.lastIndexOf('.');
    if ( lastDotIdx != -1) {
        names.add(complexName.substring(0, lastDotIdx));
    }

or just a oneliner:

    return new ClassName(clazz.getName().split("\\."));

but the above one-liner changes some behaviour, in that package parts are now separate items in the 'names' arraylist, whereas before the package is the first name, and all (inner) classes are subsequent elements. java.lang.String was ["java.lang", "String"] and becomes ["java", "lang", "String"]. Hence, I think you're looking for the first snippet and not the second.

I can't use types _AT ALL_ anywhere in java poet right now, I have to route them all to my own hackjob that returns proper ClassName instances. It's taking away rather a lot of the elegance of the library. Not that I can really impose a sense of urgency to an open source project, but let's just say I owe you a particularly nice drink of choice if you could add this to a forthcoming release :)

Thanks for reading!

NB: I relinquish any and all copyrights of this snippet to the maintainers of the javapoet on github and attest to the fact that I am the author of them.

**Comment by swankjesse** [comment]
Wanna send a pull request?
