### ISSUE TITLE
TypeName can not handle recursive generic type variable.

### ISSUE THREAD

**Issue by freetigerliu** [square/javapoet#304]
`class Foo<T extends Enum<T>>`

`ParameterizedTypeName.get(Foo.class)` will cause dead loop.

**Comment by sormuras** [comment]
Duplicate of https://github.com/square/javapoet/issues/237 ?

**Comment by tbroyer** [comment]
Yup, probably the same issue, as `T extends Enum<T>` is recursive (irrespective of the enclosing element)
