### ISSUE TITLE
No way to build generic types.

### ISSUE THREAD

**Issue by shalecraig** [square/javapoet#308]
Unless I'm reading the documentation & `TypeSpec` source incorrectly, there's no way to build the following abstract class:

```java
public abstract class MyFoo<T> implements Foo<T> {
 T getT() {
  ...
 }
}
```

I have a way around this (generating a class for each type `T` may be), but it's sub-optimal.

**Comment by kenzierocks** [comment]
`ParameterizedTypeName`? Along with `ClassName.forName` or something?

**Comment by shalecraig** [comment]
`TypeSpec.classBuilder` only takes a string argument, and there's no way to add generic parameters to the class.

**Comment by kenzierocks** [comment]
`addTypeParameter`, IIRC. I thought you said `TypeName` first :|

**Comment by shalecraig** [comment]
I'm not sure why I missed that. Thanks!

(closing)

For people looking at this in the future, it's [`addTypeVariables`](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/TypeSpec.java#L383-L396).
