### ISSUE TITLE
How do I pass arguments to a superclass?

### ISSUE THREAD

**Issue by alexandremoore** [square/javapoet#311]
I'm trying to generate:
```java
public class ClassA extends ClassB<ClassC> {
...
}
```
With the following code:
```java
TypeVariableName typeVariableName = 
		TypeVariableName.get("ClassB<ClassC>", ClassB.class, ClassC.class);

TypeSpec typeSpec =
        TypeSpec.classBuilder("ClassA")
                .superclass(typeVariableName)
                .addModifiers(Modifier.PUBLIC)
                .build();
```				
It generates the code ok but but it does not import ClassB and ClassC.

If I do 
```java
.superclass(ClassB.class) 
```
it does import the ClassB.

How do I pass arguments to a superclass?

**Comment by tbroyer** [comment]
`ClassB<ClassC>` is not a _type variable_, it's a _parameterized type_.

IMO, the above code should not work (both the `<` and `>` in the name of the type variable, and the use of a `TypeVariableName` as a superclass).

You should use:

```java
TypeSpec typeSpec = TypeSpec.classBuilder("ClassA")
    .superclass(ParameterizedTypeName.get(ClassB.class, ClassC.class)
    …
```

**Comment by danrice-square** [comment]
@tbroyer is correct:

```% cat MyStringList.java
public class MyStringList extends java.util.List<String> {}
% javac MyStringList.java
MyStringList.java:1: error: no interface expected here
public class MyStringList extends java.util.List<String> {}
                                                ^
1 error
``

**Comment by alexandremoore** [comment]
It works like a charm now! Thanks!

**Comment by tbroyer** [comment]
@danrice-square `superclass()` checks `!superclass.isPrimitive()`, should it also check `superclass instanceof ClassName || superclass instanceof ParameterizedTypeName`? (and similarly for superinterfaces BTW, which doesn't even check `isPrimitive()` currently)
WDYT?
