### ISSUE TITLE
Refering to an enum constant

### ISSUE THREAD

**Issue by Herr-Herner** [square/javapoet#321]
I must create the following code snippet:

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
class MyPojo {
...
}

I have tried it that way:
TypeSpec.Builder typeSpec = TypeSpec.classBuilder(simpleName)
				.addAnnotation(AnnotationSpec.builder(JsonInclude.class)
						.addMember("value", "$L", JsonInclude.Include.NON_NULL)
						.build())
				.addModifiers(Modifier.PUBLIC, Modifier.FINAL);

I get the following:

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(NON_NULL)
class MyPojo {
...
}

What is the right approach here?

**Comment by JakeWharton** [comment]
Use `$T.NON_NULL` and pass `Include.class`. Specifying members is being tracked by #317.

**Comment by JakeWharton** [comment]
You could also do `"$T.$L", Include.class, Include.NON_NULL.name()` if you wanted to be refactor friendly (although that particular enum is unlikely to change).

**Comment by Herr-Herner** [comment]
Thank you very much... Both the solutions are working perfectly!
