### ISSUE TITLE
javapoet-maven-plugin?

### ISSUE THREAD

**Issue by JanecekPetr** [square/javapoet#322]
Hi,

sorry about this issue, it's probably more of a question / discussion that might end up in writing some code, but I don't really know where else should I ask questions about Javapoet...

How do you guys use this thing? I'm using Javapoet to generate some massive classes for me at build-time. I currently have the `exec-maven-plugin` set up to run my Javapoet-generator classes at the `generate-sources` phase, but it feels slightly wrong - e.g. I need to pass the target file path via the `exec-maven-plugin` into the generator file's `main()` and parse it there, etc.

Are there any plans for a `javapoet-maven-plugin`, or would there be an interest on your side to own it had I written it by any chance?

Or am I missing a different and more elegant way to use Javapoet at build-time?

**Comment by swankjesse** [comment]
We use it inside of Wire, for example. That project has its own Maven plugin.
https://github.com/Square/wire

**Comment by drewctaylor** [comment]
https://github.com/drewctaylor/javapoet-maven-plugin

If anyone is, like I was, still looking for a maven plugin - I've written a very simple one: if you point it at a static method that returns Iterable<JavaFile>, it will write those java files to a specified directory.
