### ISSUE TITLE
equals()/hashCode() in JavaPoet incorrect

### ISSUE THREAD

**Issue by sormuras** [square/javapoet#345]
```java
  @Test public void equalAndHash() {
    AnnotationSpec a = AnnotationSpec.builder(AnnotationC.class).build();
    AnnotationSpec b = AnnotationSpec.builder(AnnotationC.class).build();
    Assert.assertEquals(a, b);
    a = AnnotationSpec.builder(AnnotationC.class).addMember("value", "$S", "123").build();
    b = AnnotationSpec.builder(AnnotationC.class).addMember("value", "$S", "123").build();
    Assert.assertEquals(a, b);
  }
```
The last assertion fails as `TypeName` and `CodeBlock` don't override `equals()` and `hashCode()` properly, read not at all.

Both classes need something like:
```java
  @Override public int hashCode() {
    return toString().hashCode();
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    return toString().equals(obj.toString());
  }
```

As both are immutable, caching the `toString()` result is an option, right?

**Comment by sormuras** [comment]
This blocks a nice solution for http://stackoverflow.com/questions/33055732/compare-javapoet-parameterspec-type-with-java-8-annotatedtype

**Comment by swankjesse** [comment]
I think using `toString()` for `CodeBlock.equals()` is pretty clever. It could also just compare its internal state. In either case, yes, let's implement these methods on these types.

**Comment by sormuras** [comment]
Let's rename this issue to **equals()/hashCode() in JavaPoet** as tomorrow s/o wants to compare `MethodSpec`s or other types.
