### ISSUE TITLE
Attempts to resolve names fail when using toString

### ISSUE THREAD

**Issue by kenzierocks** [square/javapoet#352]
The new resolving code fails when using toString because it attempts to consider items in the current package when the package is `null`. Test case to come soon.

**Comment by kenzierocks** [comment]
It actually looks like this might be fixed in latest, I'll update my snapshots.

**Comment by kenzierocks** [comment]
Yes indeed. Good catch with the null packages @sormuras.

**Comment by sormuras** [comment]
Caught by accident. :8ball:
