### ISSUE TITLE
nested annotation is fully qualified despite import of parent

### ISSUE THREAD

**Issue by yrfselrahc** [square/javapoet#366]
I generated code like the following with javapoet:

```java
import dagger.Component;
@Component
public abstract class TestComponent {
  @dagger.Component.Builder
  public interface Builder {
    TestComponent build();
  }
}
```

I was surprised by the "@dagger.Component.Builder" despite the import of dagger.Component. I would have instead expected @Component.Builder.

I'm not sure what elements of this construction are relevant, but the questionable annotation was generated with:

```java
TypeSpec.Builder interfaceBuilder =
          TypeSpec.interfaceBuilder(builderClassName.simpleName())
              .addModifiers(Modifier.PUBLIC)
              .addAnnotation(Component.Builder.class);
```

**Comment by swankjesse** [comment]
@yrfselrahc I believe this is fixed in the latest JavaPoet.
