### ISSUE TITLE
Import of types located in default package

### ISSUE THREAD

**Issue by sormuras** [square/javapoet#369]
In some cases, the auto-import feature tries to import types from the default package and generates for example:
```java
import Test;
```
That leads to not compiling code.

A debugger snapshot from `JavaFile:79`, local variable `suggestedImports` looks like:
```
{
Generated=javax.annotation.Generated, 
SuppressWarnings=java.lang.SuppressWarnings, 
Test=Test, 
ByteBuffer=java.nio.ByteBuffer, 
Clock=java.time.Clock, 
Map=java.util.Map,
Long=java.lang.Long,
HashMap=java.util.HashMap
}
```

I could not produce a simple test case to reproduce this behaviour -  working on this.

Possible solution is to ignore (i.e. not map) class names from default package in `CodeWriter:323` - or don't emit import statements with package-less class names.

**Comment by swankjesse** [comment]
Yeah, the default package is such an awkward corner case!

**Comment by sormuras** [comment]
This https://bugs.openjdk.java.net/browse/JDK-6975015 is related and may result in a `JavaFile#build()` error if such an import would be produced?

**Comment by sormuras** [comment]
Is fixed. Close.
