### ISSUE TITLE
Inner class $T reference

### ISSUE THREAD

**Issue by sergiords** [square/javapoet#371]
When referencing an inner class within a statement, the type name generated contains outer class name,  which is unpractical to generate inner class constructor call, particularly when inner class is itself generic.

```java

class Outer {
    class Inner {
    }
}

interface Main {
    static void main(String[] args) throws IOException {

        TypeName outerTypeName = TypeName.get(Outer.class);

        TypeName innerTypeName = TypeName.get(Outer.Inner.class);

        MethodSpec barMethod = MethodSpec.methodBuilder("bar")
                .addStatement("new $T().new $T()", outerTypeName, innerTypeName)
                .build();

        TypeSpec fooType = TypeSpec.classBuilder("Foo")
                .addMethod(barMethod)
                .build();

        JavaFile.builder("foo.bar", fooType).build().writeTo(System.out);
    }
}

```

Generated code is as follow.

```java

class Foo {
    void bar() {
        new Outer().new Outer.Inner(); // does not compile
    }
}

```

Is there any way to generate following code for this particular case (using $T reference, because we want to keep generic references too when they are present) ?

```java

new Outer().new Inner();

```

Many thanks

**Comment by swankjesse** [comment]
I suspect this is a special case where you want to use `$L` with the simple name of the type.

**Comment by sergiords** [comment]
Yes this is how I do it now. I was just wondering if there was a cleaner way to do it when `Inner` type is generic. In that case we have to write type parameters by hand if we use `$L` with simple name of the type.

````java
class Outer {
    class Inner<T> {
    }
}
````
when using `$T` with type name
````java
class Foo {
    void bar() {
        new Outer().new Outer.Inner<T>(); // does not compile, but type parameter is present
    }
}
````
when using `$L` with simple name
````java
class Foo {
    void bar() {
        new Outer().new Inner(); // compiles, but without type parameters
    }
}
````

**Comment by tbroyer** [comment]
Should there be a new kind of placeholder similar to `$T` but with the simple name only?

**Comment by sormuras** [comment]
Introducing new placeholders is ... difficult. See #317 for `$R` or #344 for `$E`  ;-) 

On topic, maybe, you just build the generic inner class as if it was a top level class via `ClassName.get(...)` and use `$T` to refernce it.

**Comment by sergiords** [comment]
Unfortunately an import is generated for top level class in that case.

````java
import Inner;
````

**Comment by sormuras** [comment]
Use the 1.5.0 snapshot version, as #370 solved that bug.

**Comment by swankjesse** [comment]
I still think your best bet is `$L` with manual type parameters. Even passing `$T` for a constructor is a bit weird: that doesn't support `<>`.

**Comment by sergiords** [comment]
I agree, I'll stick with `$L` option and manual type parameters.
Thanks for your feedback
