### ISSUE TITLE
how do I create a field from a TypeSpec?

### ISSUE THREAD

**Issue by ryanmeador** [square/javapoet#372]
I'm creating two classes, A and B.  B contains a field of type A.  How do I create this?  The FieldSpec builder only takes a Type or TypeName.  I'm pretty sure Type is off the table because A doesn't exist in the JVM at runtime.  The TypeName seems like the right way, but I can't figure out any way to create a TypeName from A's TypeSpec.

**Comment by tbroyer** [comment]
See #270 (and possibly #197 and #227)

**Comment by fkleedorfer** [comment]
See also #816 @ryanmeador I think this is what you were looking for, right? Without this, you have to remember the package for each TypeSpec you create if you want to use it somewhere later.

**Comment by ryanmeador** [comment]
Yes, that is exactly what I was looking for! Thank you for creating it. The project where I need it is long done, but I'll keep it in mind if I ever need to do this kind of thing again. I believe I went with the technique in #227 at the time.
