### ISSUE TITLE
ParameterizedTypeName with <? extends Foo> syntax

### ISSUE THREAD

**Issue by ryanmeador** [square/javapoet#376]
Is there a way to create a ParameterizedTypeName such as `List<? extends Foo>`?  I've figured out how to create `List<Foo>` using this code: `ParameterizedTypeName.get(ClassName.get(List.class), ClassName.bestGuess("my.package.Foo"))`.  I can't figure out how to add the question mark thing (I have no idea what that language feature is named either).  The examples in the JavaPoet readme don't seem to cover this case and reading the source of ParameterizedTypeName hasn't enlightened me.

**Comment by JakeWharton** [comment]
That's called a wildcard! And you're right we don't show any examples of it.

There's a few in the unit tests though that you can look at: https://github.com/square/javapoet/blob/4ee84e2372a8cfe60e991b4d2f948e6af05fd1da/src/test/java/com/squareup/javapoet/AbstractTypesTest.java#L168-L181

Basically, wrap your `ClassName.bestGuess` in a `WildcardTypeName`.

**Comment by ryanmeador** [comment]
Thanks for the quick and educational reply.  That's really easy.  You guys
have made a pretty great library here.

**Comment by shruthij** [comment]
How would you create something like this: `List<? extends Foo<Bar, Bar>`? I tried 
```ParameterizedTypeName.get(
            ClassName.get(List.class),
            ParameterizedTypeName.get(
                ClassName.bestGuess(WildcardTypeName.subtypeOf(Foo.class).toString()),
                ClassName.get(Bar.class),
                ClassName.get(Bar.class))
```
but I get an error: `java.lang.IllegalArgumentException: couldn't make a guess for ? extends Foo`
