### ISSUE TITLE
Inline annotations for fields

### ISSUE THREAD

**Issue by badoualy** [square/javapoet#380]
Hi,

the inline argument (annotations) for fields seems to be hardcoded to false (see https://github.com/square/javapoet/blob/c8b9d019a3ac8d676e38c6fb43a1ca7b4f74341e/src/main/java/com/squareup/javapoet/FieldSpec.java), anyway to change it? It makes the code very difficult to read when you start having multiple annotations.

Thanks!

**Comment by sormuras** [comment]
@badoualy I'd suggest using a post-formatter configured to your needs. The non-inlined annotations might not be the only "issue" with the default JavaPoet format style.

Like https://github.com/diffplug/spotless or https://github.com/google/google-java-format or ... others.

**Comment by sormuras** [comment]
See #105 for more styling thoughts.

**Comment by JakeWharton** [comment]
We're very hesitant to add too many stylistic options. I'm at the point where I'd even rescind filing #105. JavaPoet code is meant to look like it could have been written by a human, but not necessarily a human that was following _your_ style guide. Post-processing your code with a formatter works really well.
