### ISSUE TITLE
Can we create static code section in javapoet

### ISSUE THREAD

**Issue by uwudamith** [square/javapoet#381]
I want to generate below code bloc inside class.

static {
    // whatever code is needed for initialization goes here
}

How can i do it with javapoet

**Comment by sormuras** [comment]
http://stackoverflow.com/questions/34319246/how-to-add-static-section-in-to-java-class-in-javapoet

Issue #381 implements Closeable. ;-)

**Comment by tbroyer** [comment]
Dupe of #266 actually.
