### ISSUE TITLE
How to implement a interface which is just created with TypeSpec

### ISSUE THREAD

**Issue by raheelshah31** [square/javapoet#386]
How do i implement a interface that i generated with java poet i have the TypeSpec reference . Is this possible ?

**Comment by jbgi** [comment]
that would be a question for stackoverflow not a github issue. I think you have to create a ```ClassName``` corresponding to your ```TypeSpec```. The simple name of the class is a public field of ```TypeSpec```. The package is for you to define.

**Comment by raheelshah31** [comment]
Thanks.
