### ISSUE TITLE
equals() and hashCode() in TypeName and attached annotations

### ISSUE THREAD

**Issue by sormuras** [square/javapoet#400]
Applies to JavaPoet 1.5.0 and older versions.

The `equals()` and `hashCode()` of `TypeName` and derived classes sometimes respect attached annotations and sometimes not. In 1.4.0 (and lower?) `TypeName.<PRIMITIVE>` used it's `toString()`-representation for both methods. That respected all attached annotations. `ClassName` uses only the canonical name - attached annotations are ignored. Same goes for the other 4 types.

Do attached annotations matter? Stream-line behaviour according to the answer.

**Comment by JakeWharton** [comment]
They should, yes. We want strict equivalence (and thus hash generation).
Those who want looser matching (e.g., is a `@NonNull @Redacted String` a
`String`?) can do so themselves.

**Comment by sormuras** [comment]
Just to make sure, that I'm on the right track. This...
```java
  @Test public void annotatedEquivalence() {
    annotatedEquivalence(TypeName.VOID);
    annotatedEquivalence(ClassName.get(String.class));
    annotatedEquivalence(ArrayTypeName.get(String[].class));
    annotatedEquivalence(TypeVariableName.get(String.class));
    annotatedEquivalence(WildcardTypeName.get(List.class));
  }

  private void annotatedEquivalence(TypeName type) {
    assertFalse(type.isAnnotated());
    assertNotEquals(type, type.annotated(NEVER_NULL));
    assertNotEquals(type.hashCode(), type.annotated(NEVER_NULL).hashCode());
  }
```
...result in green lights?

**Comment by JakeWharton** [comment]
Seems accurate to me!
