### ISSUE TITLE
Covariant and Contravariant parameterized types

### ISSUE THREAD

**Issue by badoualy** [square/javapoet#402]
Hi, is there anyway to build a parameterized type to give following result:

```java
List<? super MyObject>
```

I tried to play with ParameterizedTypeName and variants, but no luck,
thanks !

**Comment by sormuras** [comment]
Try WildcardTypeName like

```java
    TypeName listOfSuper = ParameterizedTypeName.get(ClassName.get(List.class),
        WildcardTypeName.supertypeOf(String.class));
    // List<? super String> superString;
```

More interesting types: https://github.com/sormuras/javapoet/blob/master/src/test/java/com/squareup/javapoet/TypeSpecTest.java#L89

**Comment by badoualy** [comment]
Perfect, should add an example about this in the wiki :)

**Comment by sormuras** [comment]
There's no wiki @ https://github.com/square/javapoet (-:
