### ISSUE TITLE
Common super interface for builders

### ISSUE THREAD

**Issue by sockeqwe** [square/javapoet#408]
Maybe I have missed something and something like this already exists, but I find myself quite often "injecting" the same code block or single statement during code generation in an annotation processor but in different syntactical constructs.

i.e. I call `MethodSpec.Builder.addStatement(myStatement)`, and `TypeSpec.Builder.addStaticBlock(CodeBlock.Builder.addStatement(myStatement))`.

It would be nice to have a common super interface like `HasStatement` (I don't know a better name right now, but I'm sure there is a better one):
```java
interface HasStatement {
   void addStatement(String format, Object... args);
}
```

Then `CodeBlock.Builder` and `MethodSpec.Builder` could implement this interface so it would be easier to inject the same statement in different Builders by programming against the super interface:

```java
private void addAssignment(HasStatement builder) {
    builder.addStatement("foo= $S", "something");
}
```

**Comment by JakeWharton** [comment]
You can return CodeBlock instead of accepting a type to add to. CodeBlocks
can be arbitrarily nested.

**Comment by sockeqwe** [comment]
oh, thanks!
