### ISSUE TITLE
CodeWriter internals

### ISSUE THREAD

**Issue by sormuras** [square/javapoet#409]
Is there a reason, why `CodeWriter` uses an [`Appendable`](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/CodeWriter.java#L48) and not a `StringBuilder` for collecting emitted content?

* For an import refactoring i need the current position (which is equals to `StringBuilder.length()`) of the content already emitted. My current solution reads `out.toString().length()` ... which is really awkward.
* Could get rid of all `IOException` declaration and handling around `emit()` methods.

**Comment by swankjesse** [comment]
Unfortunately there's at least one project that's generating gigabyte-sized .java files, and this will break them.

**Comment by sormuras** [comment]
:fearful: Yikes! Mh, then an `Appendable` decorator that count the chars before passing it down to the component will solve my issue here. Because, having an `out.toString()` call will certainly produce an OutOfMemoryException as well...

**Comment by sormuras** [comment]
Is "type import" and "static import" a feature needed if you generate such large files?!

What trying is emitting an entire `JavaFile` with all `$T` as canonical names with collection meta-information of each `$T` rendering in to a StringBuilder instance. After processing the meta-information according to JavaPoet constraints, the "static import" and "import" sections are injected to builder and the imported package (and package+member) string are deleted.

**Comment by sormuras** [comment]
After typing the former comment, I'm realizing how to achieve that w/o the in-memory `StringBuilder`. Will need a `CountingAppendableDecorator` first to produce the meta-information, process'em like now and feed the result into a `ManglingAppenableDecorator` that filters the `$T`s occurences respecting the import statementes...

**Comment by sormuras** [comment]
Updated the PR to only contain the exception handling clean up.

**Comment by sormuras** [comment]
Revoked PR - @tbroyer was convincing.
