### ISSUE TITLE
How to extend class without implement generics？

### ISSUE THREAD

**Issue by baitouwei** [square/javapoet#415]
I have two class:
```java
Class A<T>{
}

Class B<R extend String> extend A<R>{
}
```
now,i want to use javapoet implement class C:
```java
Class C extend B{
}
```

**Comment by sormuras** [comment]
Just declare `B` using a simple `ClassName`: `ClassName.get("your.pack.age", "B")` and pass it your `C` type builder. Maybe, you want to add `@SuppressWarnings("rawtypes")` for `C` as well.

That type of question is suited here: http://stackoverflow.com/questions/tagged/javapoet

**Comment by baitouwei** [comment]
@sormuras Thanks
