### ISSUE TITLE
CodeBlock convenience methods

### ISSUE THREAD

**Issue by ronshapiro** [square/javapoet#420]
In migrating Dagger 2 to JavaPoet, I created a `CodeBlocks.format()` which mimics `CodeBlock.of()` (which was deleted in 0f0f80c0eb67ec2d71e6b01d9801480298eaed57). It's already got 89 usages, and I just came across a need for it in migrating AutoFactory as well. Instead of continually redefining this, would you be in favor of bringing this method back?

Less used, but still pretty useful is `CodeBlocks.join(codeBlocks, delimitter)` which has 34 direct+indirect usages. Common uses of this are to join arguments for a method call, type parameters, etc. This would also be useful in the AutoFactory migration.

Here's the code for reference: [CodeBlocks.java](https://github.com/google/dagger/blob/6475f47799f55eb2d22af72b7c8bddf3f7b1d01c/compiler/src/main/java/dagger/internal/codegen/CodeBlocks.java)

**Comment by swankjesse** [comment]
Sure. Send a pull request. I prefer `of()` over `format()`.

**Comment by JakeWharton** [comment]
We have lots of builder().oneThing().build() calls in some to-be-released
things as well. :+1:

**Comment by JakeWharton** [comment]
More evidence: https://github.com/square/javapoet/blob/19fe0a411228683d54e84e9e16b755bcc1a67058/src/test/java/com/squareup/javapoet/TypeSpecTest.java#L2164-L2168

**Comment by kenzierocks** [comment]
I'd like to suggest adding a `addStatement` or similar to match `MethodSpec.Builder.addCode`. I find myself using `addStatement` way more than `addCode`, and I feel that much of my code could benefit from adding a direct version of it to `MethodSpec.Builder`.

**Comment by sormuras** [comment]
@kenzierocks Same for me, see https://github.com/square/javapoet/pull/412/files#diff-f126073fdb367a6757ccfc47a6547ba5R60 - having a `CodeBlock.statementOf(format, args)` would be cool.

**Comment by swankjesse** [comment]
Yep, I think we could definitely use `addStatement()`. We’ve already got most of the other related methods. @ronshapiro would you like the honors?

**Comment by ronshapiro** [comment]
Sure. Could we also discuss the `addLine()` idea as well? 

And would we want parallel static factories: `CodeBlock.statement()` and `CodeBlock.line()`?

**Comment by swankjesse** [comment]
Symmetry with CodeBlock is good. I don't think `line()` is necessary, and it could be confusing around whether it adds `;` etc.

**Comment by JakeWharton** [comment]
Is there anything left we want to tackle here? We have `of`, `join()`, and `joiner()` from this.

**Comment by ronshapiro** [comment]
I sometimes am interested in `CodeBlock.name(FieldSpec/ParameterSpec)` type factories, but not greatly. I haven't found good names for them
