### ISSUE TITLE
java.lang classes fully qualified when annotated

### ISSUE THREAD

**Issue by ronshapiro** [square/javapoet#422]
I'm seeing some weirdness which I believe happens when JavaFile.Builder.skipJavaLangImports(true) is specified and java.lang classes are being annotated.

This code:

```java
JavaFile.builder(
        "tacos",
        TypeSpec.classBuilder("Tacos")
            .addField(
                ClassName.get(String.class)
                    .annotated(AnnotationSpec.builder(Override.class).build()),
                "string")
           .build())
    .skipJavaLangImports(true)
    .build()
    .writeTo(System.err);
```

prints:
```java
package tacos;

class Tacos {
  @Override java.lang.String string;
}
```

I would expect `java.lang.String` to just be `String`, but it seems that the `skipJavaLangImports` reverses some functionality?

**Comment by swankjesse** [comment]
Yikes, that's terrible. Will fix.
