### ISSUE TITLE
maven problem: no google/errorprone

### ISSUE THREAD

**Issue by Patterner** [square/javapoet#424]

**Comment by Patterner** [comment]
[INFO] Building JavaPoet 1.6.0-SNAPSHOT

Downloading: https://maven-central.storage.googleapis.com/com/google/errorprone/error_prone_annotations/2.0.8/error_prone_annotations-2.0.8.pom
[WARNING] The POM for com.google.errorprone:error_prone_annotations:jar:2.0.8 is missing, no dependency information available
Downloading: https://maven-central.storage.googleapis.com/com/google/errorprone/error_prone_annotations/2.0.8/error_prone_annotations-2.0.8.jar

[INFO] BUILD FAILURE

[ERROR] Failed to execute goal on project javapoet: Could not resolve dependencies for project com.squareup:javapoet:jar:1.6.0-SNAPSHOT: Could not find artifact com.google.errorprone:error_prone_annotations:jar:2.0.8 in google-maven-central (https://maven-central.storage.googleapis.com) -> [Help 1]

1> HEAD https://maven-central.storage.googleapis.com/com/google/errorprone/error_prone_annotations/2.0.8/error_prone_annotations-2.0.8.pom
404 Not Found

**Comment by swankjesse** [comment]
Works for me.

```
Downloading: https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_annotations/2.0.8/error_prone_annotations-2.0.8.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_annotations/2.0.8/error_prone_annotations-2.0.8.pom (2 KB at 7.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_parent/2.0.8/error_prone_parent-2.0.8.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_parent/2.0.8/error_prone_parent-2.0.8.pom (5 KB at 24.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/google/testing/compile/compile-testing/1.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/google/testing/compile/compile-testing/1.0-SNAPSHOT/maven-metadata.xml (785 B at 8.6 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/google/truth/truth/1.0-SNAPSHOT/truth-1.0-20160202.151806-42.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/google/truth/truth/1.0-SNAPSHOT/truth-1.0-20160202.151806-42.jar (104 KB at 490.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar
Downloading: https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_annotations/2.0.8/error_prone_annotations-2.0.8.jar
Downloaded: https://repo.maven.apache.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar (0 B at 0.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_annotations/2.0.8/error_prone_annotations-2.0.8.jar (8 KB at 19.5 KB/sec)```

Does it work if you change your network?

**Comment by swankjesse** [comment]
Possibly an issue with `https://maven-central.storage.googleapis.com` ?

**Comment by JakeWharton** [comment]
How are you configuring it to use Google's mirror? settings.xml?

Make sure you have the <mirrorOf> tag which should let it fall back to the
real repo1.maven.org location (per
http://googlecloudplatform.blogspot.com/2015/11/faster-builds-for-Java-developers-with-Maven-Central-mirror.html
)

**Comment by Patterner** [comment]
fixed. thx. never expected a google pom not being available on googleapis. sorry.
