### ISSUE TITLE
Type annotations on qualified names

### ISSUE THREAD

**Issue by cushon** [square/javapoet#431]
Type annotations on qualified names have to be applied to the simple name of the type. JLS [§9.7.4](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.7.4) says:

> It is a compile-time error if an annotation of type T applies to a type (or any part of a type) in a type context, and T is applicable in type contexts, and the annotation is not admissible.
> 
> For example, assume an annotation type TA which is meta-annotated with just `@Target(ElementType.TYPE_USE)`. The terms `@TA java.lang.Object` and `java.@TA lang.Object` are illegal because the simple name to which `@TA` is closest is classified as a package name. On the other hand, `java.lang.@TA Object` is legal.

Incorrect:

``` java
@Target(ElementType.TYPE_USE)
@interface Anno {}

class Test {
  @Anno java.util.Map.Entry e;
}
```

```
error: scoping construct cannot be annotated with type-use annotation: @Anno
```

Correct:

``` java
java.util.Map.@Anno Entry e;
```

JavaPoet doesn't get this right.

Failing test case:

```diff
diff --git a/src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java b/src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
index 35b2b1f..e420d85 100644
--- a/src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
+++ b/src/test/java/com/squareup/javapoet/AnnotatedTypeNameTest.java
@@ -20,16 +20,24 @@ import static org.junit.Assert.assertFalse;
 import static org.junit.Assert.assertNotEquals;
 import static org.junit.Assert.assertTrue;

+import java.lang.annotation.ElementType;
+import java.lang.annotation.Target;
 import java.util.List;
+import java.util.Map;
 import org.junit.Test;

 public class AnnotatedTypeNameTest {

   private final static String NN = NeverNull.class.getCanonicalName();
   private final AnnotationSpec NEVER_NULL = AnnotationSpec.builder(NeverNull.class).build();
+  private final AnnotationSpec TYPE_USE_ANNOTATION =
+      AnnotationSpec.builder(TypeUseAnnotation.class).build();

   public @interface NeverNull {}

+  @Target(ElementType.TYPE_USE)
+  public @interface TypeUseAnnotation {}
+
   @Test(expected=NullPointerException.class) public void nullAnnotationArray() {
     TypeName.BOOLEAN.annotated((AnnotationSpec[]) null);
   }
@@ -102,6 +110,14 @@ public class AnnotatedTypeNameTest {
     annotatedEquivalence(WildcardTypeName.get(Object.class));
   }

+  @Test public void annotatedNestedType() {
+    String expected =
+        "java.util.Map.@com.squareup.javapoet.AnnotatedTypeNameTest.TypeUseAnnotation Entry";
+    TypeName type = TypeName.get(Map.Entry.class).annotated(TYPE_USE_ANNOTATION);
+    String actual = type.toString();
+    assertEquals(expected, actual);
+  }
+
   private void annotatedEquivalence(TypeName type) {
     assertFalse(type.isAnnotated());
     assertEquals(type, type);
```

```
Expected :java.util.Map.@com.squareup.javapoet.AnnotatedTypeNameTest.TypeUseAnnotation Entry
Actual   :@com.squareup.javapoet.AnnotatedTypeNameTest.TypeUseAnnotation java.util.Map.Entry
```

**Comment by JakeWharton** [comment]
Fascinating. Thanks for the report.

**Comment by sormuras** [comment]
True.

But only compiles with Java 8 right? `ElementType.TYPE_USE` is annotated with `since 1.8`. Working on fix, though.

**Comment by JakeWharton** [comment]
Type annotations came with Java 8, yes. No different than our other support
of Java 8 language features.

**Comment by sormuras** [comment]
It get's interesting, when it comes to imports. Is the following assumption correct?

```java
    AnnotationSpec typeUseAnnotation = AnnotationSpec.builder(TypeUseAnnotation.class).build();
    TypeName type = TypeName.get(Map.Entry.class).annotated(typeUseAnnotation);
    String source = JavaFile.builder("com.squareup.tacos",
        TypeSpec.classBuilder("TestTypeAnnotationsOnQualifiedTypeNames")
            .addField(type, "entry")
            .build())
        .build()
        .toString();
    assertThat(source).isEqualTo(""
        + "package com.squareup.tacos;\n"
        + "\n"
        + "import com.squareup.javapoet.AnnotatedTypeNameTest;\n"
        + "import java.util.Map;\n"
        + "\n"
        + "class TestTypeAnnotationsOnQualifiedTypeNames {\n"
        + "  Map.@AnnotatedTypeNameTest.TypeUseAnnotation Entry entry;\n" 
        + "}\n");
```

**Comment by sormuras** [comment]
Even more interesting:
```java
  Map.@TypeUseAnnotation Entry entry1; // ok
  
  @TypeUseAnnotation Map.Entry entry2; // ok
  
  @TypeUseAnnotation  java.util.Map.Entry entry3; // fails!
```

**Comment by cushon** [comment]
`@TypeUseAnnotation Map.Entry entry2` isn't valid if the annotation specifies `@Target(TYPE_USE)`. `Entry` is a static nested class, so `Map` is just a 'scoping construct'. With qualified names for inner (non-static) classes, it's possible to apply type annotations to the simple name of the inner class or the qualifier, though.

And annotating the simple name of a qualified type is only legal for `TYPE_USE` annotations, declaration annotations need to appear with modifiers.

More examples:

```java
package test;

import java.lang.annotation.Target;
import java.lang.annotation.ElementType;

@Target(ElementType.TYPE_USE) @interface TypeUseAnnotation {}
@Target(ElementType.FIELD) @interface FieldAnnotation {}

class Test {

  static class Nested{}
  class Inner {}

  test.Test.@TypeUseAnnotation Nested e1;
  test.@TypeUseAnnotation Test.Nested e2; // scoping construct cannot be annotated
  @TypeUseAnnotation test.Test.Nested e3; // scoping construct cannot be annotated

  test.Test.@TypeUseAnnotation Inner e4;
  test.@TypeUseAnnotation Test.Inner e5;
  @TypeUseAnnotation test.Test.Inner e6; // scoping construct cannot be annotated

  @FieldAnnotation test.Test.Inner e7;
  test.Test.@FieldAnnotation Inner e8; // annotation type not applicable
}
```

**Comment by sormuras** [comment]
:fearful:  Eek! Learned  a lot, tonight. Thanks!

So, PR #432 will include this example a test, tomorrow.

**Comment by sormuras** [comment]
@cushon Referring to your initial report, this only applies if JavaPoet emit "fully qualified type names". If I'm not wrong, that only happens when your're emitting an annotated `TypeName` by itself, i.e. no enclosing `JavaFile` instance is present.

So commonly, when you use an annotated `TypeName` within a `JavaFile` context, the auto-import feature kicks in stripping the package name from the type name. For example, all fields below compile:
```java
class Test {
  // ...
  Test.@TypeUseAnnotation Nested f1a; // same as e1
  @TypeUseAnnotation Nested f1b; // same as e1
  
  Test.@TypeUseAnnotation Inner f4a; // same as e4 && e5
  @TypeUseAnnotation Inner f4b; // same as e4 && e5
}
```

**Comment by JakeWharton** [comment]
Fully qualified names are still emitted by a JavaFile when there are simple
name collisions.

**Comment by sormuras** [comment]
True. But what are the odds, that both occur in one place? Name collision and an annotated nested class name. That'said why I'm interested in @cushon s use-case.

**Comment by cushon** [comment]
Your comment about f4a and f4b both being the same as e4 and e5 isn't quite right, e4 and e5 aren't the same as each other. In e5 the annotation is on the outer type `Test`, in e4 the annotation is on `Inner`.

```
  test.Test$Inner e4;
    descriptor: Ltest/Test$Inner;
    flags:
    RuntimeInvisibleTypeAnnotations:
      0: #12(): FIELD, location=[INNER_TYPE]
```

```
  test.Test$Inner e5;
    descriptor: Ltest/Test$Inner;
    flags:
    RuntimeInvisibleTypeAnnotations:
      0: #12(): FIELD
```

In the real-world example that prompted the bug report, someone was annotating a nested class where the enclosing class was in the same package, and it got written out as `@TypeAnnotation ClassInSamePackage.SomeStaticNestedClass`.

I haven't seen any examples where an outer class type is annotated (like e4), so just emitting type annotations beside the inner-most simple name is probably a good start. It'd be nice to leave room in the API to handle the general case, though.

**Comment by sormuras** [comment]
iirc, i listed field and parameter type annotation as "hard coded" and therefore not working in #432 - that observation is not valid, as field and parameter annotation are always rendered as a prefix to the annotated element, field or parameter. Right?

If the answer is yes, I could resurrect the closed PR and dive deeper into the open `$T` issue. As `$T` can occur in type use, field and parameter and "every other" contexts, is not so easy to fix. Or am I missing a point here?

`ClassName.get("test", "A", "B", "C").annotated(T)` yields `test.A.B.@T C` 

What type of API do prefer, when talking about not annotating the inner-most simple name? Count from 0 to inner-most name? Pass "steps back up the hierachy" like:

`ClassName.get("test", "A", "B", "C").annotated(T, -1)` yields `test.A.@T B.C`

**Comment by sormuras** [comment]
@cushon do you agree, that the current `AnnotatedTypeNameTest` includes a bunch of false positives, when **all** annotated `TypeName` annotations are considered _@Target(ElementType.TYPE_USE)_ implicitely? For example, it should read like:
```java
  @Test public void annotatedType() {
    String expected = "java.lang.@" + NN + " String";
    TypeName type = TypeName.get(String.class);
    String actual = type.annotated(NEVER_NULL).toString();
    assertEquals(expected, actual);
  }
```
and not `expected = "@" + NN + " java.lang.String"`

**Comment by cushon** [comment]
Annotations can't be applied to types unless their `@Target` includes `TYPE_USE`, see [JLS 9.6.4.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.4.1):

> If an annotation of type java.lang.annotation.Target is not present on the declaration of an annotation type T, then T is applicable in all declaration contexts except type parameter declarations, **and in no type contexts**.

**Comment by JakeWharton** [comment]
@sormuras All `TypeName` annotations _are_ type annotations. That's the whole point of the JavaPoet API. If you want to annotate a field, parameter, or method then add that annotations to that model object, not the type.

**Comment by sormuras** [comment]
That's my point, @JakeWharton - when s/o uses JavaPoets `TypeName.annotate()` we can treat those annotations as type (use) annotations. That's why the PR #437 seems valid to me, when changing the test assumptions from `@T java.lang.String` to `java.lang.@T String`. These assupmtions were wrong in the first place.

@cushon JavaPoet hat no notion of an annotation target. Not, yet. It's up to the API user to pass only valid annotation types to ... a `TypeName`, type, method, field, parameter and so forth.

**Comment by JakeWharton** [comment]
> Not, yet.

Not ever! `javac` covers our ass there and we delegate to it for validation. We're only concerned with ensuring the code is well structured, not semantically correct.

**Comment by sormuras** [comment]
_Never ever!_ (-:

Can you all please have a look at this test?

https://github.com/sormuras/javapoet/commit/806a01e448c943e68e0a9aa516630f964137cddc#diff-0959801b341a3e8d5e98ce499cf56cf3R578

**Comment by sormuras** [comment]
@cushon @JakeWharton Is the following JavaPoet API usage and output correct?
```java
  @Test public void annotatedFullyQualifiedNameInJavaFile() {
    String expected = ""
        + "package test;\n"
        + "\n"
        + "class Test {\n"
        + "  Map justHereToForceQualifiedNamesBelow1;\n"
        + "\n"
        + "  Byte justHereToForceQualifiedNamesBelow2;\n"
        + "\n"
        + "  java.util.Map.Entry e0;\n"
        + "\n"
        + "  java.util.Map.Entry<java.lang.Byte, java.lang.Byte> e1;\n"
        + "\n"
        + "  java.util.Map.@T Entry<java.lang.Byte, java.lang.Byte> e2;\n"
        + "\n"
        + "  java.util.Map.Entry<java.lang.@T Byte, java.lang.Byte> e3;\n"
        + "\n"
        + "  java.util.Map.Entry<java.lang.@T Byte, java.lang.@T Byte> e4;\n"
        + "\n"
        + "  java.util.Map.@T Entry<java.lang.@T Byte, java.lang.@T Byte> e5;\n"
        + "\n"
        + "  @T\n"
        + "  java.util.Map.@T Entry<java.lang.@T Byte, java.lang.@T Byte> f1;\n"
        + "}\n";
    // assuming: @Target({ElementType.FIELD, ElementType.TYPE_USE}) at @interface test.T
    AnnotationSpec tag = AnnotationSpec.builder(ClassName.get("test", "T")).build();
    ClassName entryNoTag = ClassName.get(Map.Entry.class);
    ClassName entryTagged = (ClassName) ClassName.get(Map.Entry.class).annotated(tag);
    TypeName byteNoTag = TypeName.BYTE.box();
    TypeName byteTagged = TypeName.BYTE.box().annotated(tag);
    TypeName e1 = ParameterizedTypeName.get(Map.Entry.class, Byte.class, Byte.class);
    TypeName e2 = e1.annotated(tag);
    TypeName e3 = ParameterizedTypeName.get(entryNoTag, byteTagged, byteNoTag);
    TypeName e4 = ParameterizedTypeName.get(entryNoTag, byteTagged, byteTagged);
    TypeName e5 = ParameterizedTypeName.get(entryTagged, byteTagged, byteTagged);
    FieldSpec f1 = FieldSpec.builder(e5, "f1").addAnnotation(tag).build();
    JavaFile file = JavaFile.builder("test", TypeSpec.classBuilder("Test")
        .addField(ClassName.get("test", "Map"), "justHereToForceQualifiedNamesBelow1")
        .addField(ClassName.get("test", "Byte"), "justHereToForceQualifiedNamesBelow2")
        .addField(entryNoTag, "e0")
        .addField(e1, "e1")
        .addField(e2, "e2")
        .addField(e3, "e3")
        .addField(e4, "e4")
        .addField(e5, "e5")
        .addField(f1)
        .build())
        .build();
    assertThat(file.toString()).isEqualTo(expected);
  }
```

**Comment by cushon** [comment]
That looks reasonable to me, FWIW.

I think it makes sense to punt on  `package.@TypeAnnotation Outer.Inner`. It looks like the API also doesn't allow parameterized qualified names like `package.Outer<T>.Inner`?

**Comment by JakeWharton** [comment]
Correct!

**Comment by eamonnmcmanus** [comment]
I think this bug has been fixed? I find that if I call `TypeName.get(...).annotation(aTypeAnnotation)` then `aTypeAnnotation` correctly appears with the `Map.@Nullable Entry` syntax.

**Comment by cushon** [comment]
I think `package.@TypeAnnotation Outer.Inner` is still unsupported, but that's probably fine.

The unit test in the original bug report was submitted in f80f1072b9c09b95b36b71d6d9c211f9c4a68eb6 and un-`@Ignored` in d91f8e1374f7ccdb68d92c206c84864cd09c02f6, so this bug can be closed.
