### ISSUE TITLE
Cannot add a literal value from an empty String

### ISSUE THREAD

**Issue by luiggi0925** [square/javapoet#435]
I want to generate the following code:

    map.put("id", 0);
    map.put("name", "");

For this, I'm using `MethodBuilder#addStatement` inside a `for` loop:

    String fieldName = "name of a field";
    ExecutableElement field = ...; //fields
    methodSpecBuilder.addStatement("$N.put(\"$N\", $S)", "map", fieldName, getDefaultValue(field)) );
    //...
    public Object getDefaultValue(ExecutableElement param) {
        Map<String, Object> defaultValues = new HashMap<>();
		defaultValues.put(char.class.getName(), "");
		defaultValues.put(boolean.class.getName(), 0);
		defaultValues.put(byte.class.getName(), 0);
		defaultValues.put(short.class.getName(), 0);
		defaultValues.put(int.class.getName(), 0);
		defaultValues.put(long.class.getName(), 0);
		defaultValues.put(float.class.getName(), 0);
		defaultValues.put(double.class.getName(), 0);
		defaultValues.put(Character.class.getName(), "");
		defaultValues.put(Boolean.class.getName(), 0);
		defaultValues.put(Byte.class.getName(), 0);
		defaultValues.put(Short.class.getName(), 0);
		defaultValues.put(Integer.class.getName(), 0);
		defaultValues.put(Long.class.getName(), 0);
		defaultValues.put(Float.class.getName(), 0);
		defaultValues.put(Double.class.getName(), 0);
		defaultValues.put(String.class.getName(), "");
		defaultValues.put(List.class.getName(), "[]");
		defaultValues.put(ArrayList.class.getName(), "[]");
		defaultValues.put(LinkedList.class.getName(), "[]");
		defaultValues.put(Set.class.getName(), "[]");
		defaultValues.put(Object.class.getName(), "");
		return defaultValues.getOrDefault(param.getReturnType().toString(), " ");
    }

It generates the following:

    map.put("name", " ");
    map.put("id", "0"); //literal String 0, not 0

If I use a literal `$L` instead of a string `$S`, I get the following:

    map.put("name", ); //issue here!
    map.put("id", 0); //this is fine

**Comment by sormuras** [comment]
I guess, you need `$L` with some escaping here.

```java
defaultValues.put(char.class.getName(), ""); // empty char?! Use for example '\u0000'
...
defaultValues.put(Character.class.getName(), ""); // see above
...
defaultValues.put(String.class.getName(), ""); // use "\"\""
```

**Comment by ronshapiro** [comment]
Why don't you pass the MethodSpec.Builder to the method and rename it
addMapEntry(MethodSpec, ExecutableElement)? Instead of building a map just
to receive a default value, have a conditional for each type and use the
correct $L/$S/etc appropriately?

**Comment by luiggi0925** [comment]
@sormuras I used `"\"\""` to solve this. I figured it out after doing some debugging of your code. It would be great if info like that is explained in the literal `$L` example.

**Comment by swankjesse** [comment]
one other option is to return a CodeBlock from `getDefaultValue()`.
