### ISSUE TITLE
Adding a MethodSpec.Builder::addExceptionIfNotDeclared method

### ISSUE THREAD

**Issue by arey** [square/javapoet#438]
Hi,

I'm using Javapoet to generate Java code dynamically (you may see my project on https://github.com/arey/javabean-marshaller)
To avoid a method throwing the same exception twice, I've coded the following method:
```
 public static void addExceptionIfNotDeclared(MethodSpec.Builder methodBuilder, Class<?> exception) {
        ClassName ex = ClassName.get(exception);
        if (!methodBuilder.build().exceptions.contains(ex)) methodBuilder.addException(ex);
    }
```

Here how I call this method:
```
JavapoetHelper.addExceptionIfNotDeclared(method, MyException.class);
```

Is-ti possible to add a similar feature on the MethodSpec.Builder class?

Regards

Antoine

**Comment by sormuras** [comment]
Or with #341 implemented, you wouldn't need the extra-work of `methodBuilder.build()`. Then you just could type:
```java
ClassName ex = ClassName.get(MyException.class);
if (!methodBuilder.exceptions().contains(ex)) methodBuilder.addException(ex);
```

**Comment by swankjesse** [comment]
We should probably make addException discard duplicates. Should be an easy win.
