### ISSUE TITLE
Add TypeVariableName.withBounds

### ISSUE THREAD

**Issue by JakeWharton** [square/javapoet#440]
I use a constant for type variables and I want to add bounds when using in a type declaration.

e.g.,
```java
TypeSpec.classBuilder("Example")
    .addTypeVariable(tVar.withBounds(boundTypeName))
    .addField(tVar, "whatever", PRIVATE FINAL)
```

**Comment by swankjesse** [comment]
Yeah!

**Comment by sormuras** [comment]
Do you want a single `withBounds(TypeVariableName boundTypeName)` or some convenient overloaded `withBounds` methods as well?
