### ISSUE TITLE
Inner class of parameterized type does not generate correct code

### ISSUE THREAD

**Issue by marcosb** [square/javapoet#458]
If we have something like:

class MyClass<T> {
  class InnerClass {}
}

There is currently no way to output MyClass<T>.Inner (ParameterizedTypeName doesn't have any way to specify this, nor does ClassName)

**Comment by marcosb** [comment]
Woops, my brackets were swallowed by the github formatter.

No way to output `MyClass<T>.Inner`is what I meant.

**Comment by tbroyer** [comment]
AFAIK, this is a known limitation; you'll use a `ParameterizedTypeName` for the outer class and then simple strings (simple name) for the inner classes.

**Comment by marcosb** [comment]
Yes, the problem is TypeName.get(TypeMirror mirror, [other params]), which happens to be what I'm using, ends up translating to a raw type.

**Comment by marcosb** [comment]
#460 fixes the issue

**Comment by marcosb** [comment]
Slight update to the patch to actually fix the issue

**Comment by marcosb** [comment]
Gentle ping - does this fix seem reasonable? I'm guessing there's a lot of code generators out there using javapoet to build code from a TypeMirror which are incorrectly generating raw types right now (that was the case with me, and we've gone many months w/o noticing)

**Comment by marcosb** [comment]
Cleaner pull @ https://github.com/square/javapoet/pull/461 after talking to Christian
