### ISSUE TITLE
Adding support for multiple parameters in Enum constants (method Builder.addEnumConstant)

### ISSUE THREAD

**Issue by MaximeOpsommer** [square/javapoet#459]
The current method `Builder.addEnumConstant(String name, TypeSpec typeSpec)` accepts a single parameter to the constant definition.

Would it be possible to allow for more parameters to be defined by replacing the current definition by `Builder.addEnumConstant(String name, TypeSpec... typeSpec)` or `Builder.addEnumConstant(String name, Iterable<TypeSpec> typeSpec)` ?

**Comment by JakeWharton** [comment]
For what purpose? Only a single anonymous subclass can be associated with a constant.

**Comment by MaximeOpsommer** [comment]
I would like to create an enum constant like this one : `LEVEL("level", double.class)`, but I don't think I can create such a constant with 2 parameters using the current API, isn't it?

**Comment by JakeWharton** [comment]
```java
.addEnumConstant("LEVEL", TypeSpec.anonymousClassBuilder("$S, double.class", "level").build())
```
