### ISSUE TITLE
allow TypeVariableName.withBounds() to take TypeName subclasses as input

### ISSUE THREAD

**Issue by caplan** [square/javapoet#463]
It'd be nice if this

```java
public TypeVariableName withBounds(List<TypeName> bounds);
```

could be something like this:

```java
public TypeVariableName withBounds(List<? extends TypeName> bounds);
```

I think this is the only method affected, all others take varargs rather than collections as input so we get covariance for free.

**Comment by JakeWharton** [comment]
Send a PR? Sounds reasonable to me.
