### ISSUE TITLE
Cannot add fields to Annotations

### ISSUE THREAD

**Issue by haliquim** [square/javapoet#467]
I want to generate an Android StringDef like the following
```java
@StringDef({
		Foo.bar,
		Foo.baz
})
public @interface Foo {
	String bar = "bar";
	String baz = "baz";
}
```
Building the annotation with the annotation builder, I wrote
```java
TypeSpec.annotationBuilder("Foo")
				.addModifiers(Modifier.PUBLIC,Modifier.STATIC)
				.addField(FieldSpec.builder(String.class, "bar")
						.initializer("bar")
						.build())
				.addField(FieldSpec.builder(String.class, "baz")
						.initializer("baz")
						.build())
				.build();
```
However, the build fails with
> java.lang.IllegalStateException: ANNOTATION Foo cannot have fields

Disabling the check for fields on annotations generates valid code, and as far as I can tell annotations can have fields.

Is there another way to do this correctly, or is this a bug/limitation?

**Comment by JakeWharton** [comment]
Try adding `PUBLIC` and `STATIC` to the fields.

**Comment by JakeWharton** [comment]
and `FINAL`

**Comment by haliquim** [comment]
Adding modifiers doesn't fix it, it fails in TypeSpec.Builder.addField with the check:

`checkState(kind != Kind.ANNOTATION, "%s %s cannot have fields", kind, name);`

which disabled fields on annotations regardless of the modifiers

**Comment by JakeWharton** [comment]
Ok thanks. We'll fix to use the same mechanism as normal interfaces which will require `PUBLIC`, `STATIC`, and `FINAL` on them.
