### ISSUE TITLE
Append/Update enum or inner class/interface to exists *.java source

### ISSUE THREAD

**Issue by foror** [square/javapoet#489]
Example I have some domain class:

```
public class Customer {
    private String name;
}
```

and I want add refs to his fields and validation messages:

```
public class Customer {
    public enum field {
        name;
    }

    public interface m {
        public enum validator {
            empty_name;
        }
    }

    private  String name;
}
...
validator.add(new Violation(Customer.field.name, Customer.m.validator.empty_name));
```

Label and m will be generated on each build with append or replace generated code in Customer class.

**Comment by JakeWharton** [comment]
We have no plans to do parsing or expose a fully-mutable AST. You'll have far better luck with JetBrains PSI or something like http://spoon.gforge.inria.fr/ which is designed for this case. JavaPoet is for taking a non-code model and generating an entire source file projection of it.
