### ISSUE TITLE
Can't add modifier to any spec in Android Studio

### ISSUE THREAD

**Issue by androidmind** [square/javapoet#491]
Calling `addModifiers` on `TypeSpec` results in `can't resolve method error`. After looking at source code, I have found that `javax.lang.model.element.Modifier` is  not imported in source files. I am attaching a also attaching a snapshot, please have a look.
![capture](https://cloud.githubusercontent.com/assets/6380863/17647339/51290f4e-6206-11e6-997d-20bbc20171fb.PNG)

**Comment by JakeWharton** [comment]
Is this an Android module or a Java module? JavaPoet isn't going to work in an Android module.

**Comment by androidmind** [comment]
It's a java module.

**Comment by androidmind** [comment]
I have solved this issue by adding `android-apt` plugin in gradle and setting `apt` as scope for my module dependency.

**Comment by 328629033** [comment]
android-apt? I also import java-poet int Java module and the same error with yours. If there is any other solutions?

**Comment by allaudin** [comment]
I thing I also added `source-compatibility = 1.7` in build file.

**Comment by Pedramrn** [comment]
I have the same problem. the thing is, it compiles and generates codes, but shows as error in Android Studio.

this is my `build.gradle`


```groovy
apply plugin: 'java'

targetCompatibility = JavaVersion.VERSION_1_7
sourceCompatibility = JavaVersion.VERSION_1_7

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.squareup:javapoet:1.8.0'
    compile 'com.google.auto.service:auto-service:1.0-rc2'
    compile 'com.google.auto:auto-common:0.6'
    testCompile 'com.google.truth:truth:0.28'
    testCompile 'junit:junit:4.12'
}
```
These are the methods that do not resolve:

```java
addModifiers(Modifier.PUBLIC, Modifier.STATIC)
javaFile.writeTo(filer)
SuperficialValidation.validateElement(element)//from auto common
```

**Comment by JakeWharton** [comment]
Studio is likely erroneously using the Android platform APIs instead of the
JDK APIs.

**Comment by StefanDeBruijn** [comment]
Fixed this by using 
annotationProcessor project(path: 'processor')  instead of compile

**Comment by Gericop** [comment]
So what's the solution for this bug? The file write won't happen unless the errors are fixed. It even kills other annotation processors. `annotationProcessor project(path: 'processor')` won't fix it (don't understand why would it, it has nothing to do with the Java library module). Android Studio 2.3.1, Java 1.7 source and target compatibility.

**Comment by JakeWharton** [comment]
If you can't reference the needed types in a Java module then it's an
Android studio bug and should be filed on b.android.com.

**Comment by Gericop** [comment]
I found a temporary quick fix, if anyone needs it, I'll just leave it here.
So, the problem is that basically (*among others*) JSR 308 is missing, thus we need to support it to the compiler somehow. I found a lib that contains it, so you just have to add the following line to your dependencies in build.gradle:
```gradle
compile 'org.checkerframework:checker:2.1.10'
```
This will fix the `addModifiers(...)` method, however, `javaFile.writeTo(filer)` still causes an annotation processor failure (at least I use it there), but that's not a big problem since it can be avoided by manually providing the writer to that method:

```java
JavaFileObject source = processingEnv.getFiler().createSourceFile("some.package.HelloWorld");
Writer writer = source.openWriter();
// ...
JavaFile javaFile = JavaFile.builder("some.package", helloWorld).build();
javaFile.writeTo(writer);
writer.flush();
writer.close();
```

This way I was able to generate the given source file with the specified modifiers.

**Comment by Gericop** [comment]
Sorry, it was too soon to be happy. Apparently that "checker" framework was compiled with Java 8, hence no APK can be generated for 1.7 compatibility...

**Comment by JakeWharton** [comment]
Your module doing code generation can target Java 8 since it doesn't end up
in the APK. It runs on the host computer.

**Comment by Gericop** [comment]
I found an easier solution: copied the `Modifier` class from source to my module and it just works now...

**Comment by joeywp** [comment]
I was suffering from the same bug when I made my first annotation processor. Maybe I'm doing something wrong, but for me it worked fine when I changed "compile" to "provided". Because my annotations are using Retention.SOURCE everything now works fine. I guess that when you're using another retention type it might still not work, but I didn't test that. 

An example:
```gradle
provided project(path: ':my-processor')
annotationProcessor project(":my-processor")
```

**Comment by KingJA** [comment]
@Gericop I hava resoved the same problem with your library.tks.

**Comment by mrrobot97** [comment]
compile 'org.checkerframework:checker:2.1.10' works well.

**Comment by Poney1** [comment]
how to sovle?

**Comment by dengshiwei** [comment]
the problem is android studio bug.

**Comment by dashu52** [comment]
I have resoved the same probliem when  create java library moudle in android studio
