### ISSUE TITLE
Making small modifications to JavaPoet as a fork

### ISSUE THREAD

**Issue by kenzierocks** [square/javapoet#492]
I'm writing a language that is very similar to Java (actually a superset of it), and I'd love to be able to use JavaPoet to emit it's code since I make very little changes to what is defined by the JLS. However, it does add a few modifiers, so I'm willing to fork off another version.

I did want to ask if there would be any particular way you recommend that I fork the library, since I would like to update my fork to use any bugfixes/changes you make in the original. It seems like a lot of work for me to update for every small bugfix when I'm just applying some small changes to the model of JavaPoet.

**Comment by swankjesse** [comment]
Unsure. Probably easiest is to just fork with Git and rebase your fork as necessary.

**Comment by tbroyer** [comment]
Rebasing would make it harder than necessary for anyone else working with the repo. You'd better merge from upstream, fixing merge conflicts as needed. Git should detect file moves/renames so merges should be rather straightforward.

**Comment by kenzierocks** [comment]
Ok, that's what I'll do.

**Comment by kenzierocks** [comment]
I do have one more (legal) question: What modifications do I make to the license and it's respective header [here](https://github.com/square/javapoet#user-content-license)? Do I move your copyright to LICENSE-javapoet.txt and stick a new copyright on there that is mine, or something else?

**Comment by JakeWharton** [comment]
We are not allowed to give any legal guidance or advice.

**Comment by tbroyer** [comment]
This is Apache licensed, so you only have to keep the copyright; you can even re-license under different terms.
