### ISSUE TITLE
A feature to automatically generate setter and getter methods on FieldSpec 

### ISSUE THREAD

**Issue by ErencanOzkan** [square/javapoet#494]
FieldSpec  may have a field variable to auto generate getter and setter for FieldSpec  when building the class.

For example:

`FieldSpec field = FieldSpec.builder(.....).autogenerateGettersAndSetters(true).build();`

During the generation of the class, the getters and setters of the above field can be generated automatically.

**Comment by jbgi** [comment]
Looks similar to #484. (closed as won't fix)

**Comment by swankjesse** [comment]
Yup. Dumb getters and setters are a mistake in a world of fancy refactoring tools.

**Comment by ronshapiro** [comment]
Even for those who like getters and setters, you probably never want a
feature like this. This would expose *any* implementation detail from your
type. You could easily create helper methods to create a getter or setter
from a FieldSpec, but to do it to all fields is almost definitely a mistake.

**Comment by Bertrand82** [comment]
"You could easily create helper methods to create a getter or setter
from a FieldSpec"
Where is the code ?

**Comment by Bertrand82** [comment]
public static void addGetterAndSetter(FieldSpec fieldSpec, Builder classBuilder) {
		addGetter(fieldSpec, classBuilder);
		addSetter(fieldSpec, classBuilder);
	}
	
	
	private static void addSetter(FieldSpec fieldSpec, Builder classBuilder) {
		String setterName  = "set"+capitalizeFirstLetter(fieldSpec.name);
		MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(setterName).returns(fieldSpec.type).addModifiers(Modifier.PUBLIC);
		methodBuilder.addParameter(fieldSpec.type, fieldSpec.name);
		methodBuilder.addStatement("this."+fieldSpec.name+"="+fieldSpec.name);
		classBuilder.addMethod(methodBuilder.build());	
	}


	public static void addGetter(FieldSpec fieldSpec, Builder classBuilder) {
		String getterName  = "get"+capitalizeFirstLetter(fieldSpec.name);
		MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(getterName).returns(fieldSpec.type).addModifiers(Modifier.PUBLIC);
		methodBuilder.addStatement("return this."+fieldSpec.name);
		classBuilder.addMethod(methodBuilder.build());	
	}
	
	

	private static String capitalizeFirstLetter(final String str) {
		final String s = str.substring(0, 1).toUpperCase() + str.substring(1);
		return s;
	}

**Comment by Bertrand82** [comment]
public static void addGetterAndSetter(FieldSpec fieldSpec, Builder classBuilder) {
		addGetter(fieldSpec, classBuilder);
		addSetter(fieldSpec, classBuilder);
	}
	
	
	private static void addSetter(FieldSpec fieldSpec, Builder classBuilder) {
		String setterName  = "set"+capitalizeFirstLetter(fieldSpec.name);
		MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(setterName).addModifiers(Modifier.PUBLIC);
		methodBuilder.addParameter(fieldSpec.type, fieldSpec.name);
		methodBuilder.addStatement("this."+fieldSpec.name+"="+fieldSpec.name);
		classBuilder.addMethod(methodBuilder.build());	
	}


	public static void addGetter(FieldSpec fieldSpec, Builder classBuilder) {
		String getterName  = "get"+capitalizeFirstLetter(fieldSpec.name);
		MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(getterName).returns(fieldSpec.type).addModifiers(Modifier.PUBLIC);
		methodBuilder.addStatement("return this."+fieldSpec.name);
		classBuilder.addMethod(methodBuilder.build());	
	}
	
	

	private static String capitalizeFirstLetter(final String str) {
		final String s = str.substring(0, 1).toUpperCase() + str.substring(1);
		return s;
	}

**Comment by tbroyer** [comment]
Beware of the locale with `toUpperCase` if your code is meant to run on other developers' machines.
