### ISSUE TITLE
Add support for annotated method parameters.

### ISSUE THREAD

**Issue by ragunathjawahar** [square/javapoet#50]
Which of the following API design is better on `interface` and `abstract` methods that will support annotated parameters?

```
javaWriter.beginMethodSignature(returnType, methodName, modifiers);
javaWriter.emitAnnotation(annotationType);
javaWriter.emitParam(paramType, paramName);
javaWriter.endMethodSignature();
```

or

```
javaWriter.beginMethodSignature(returnType, methodName, modifiers);
javaWriter.emitAnnotation(annotationType);
javaWriter.emitParam(paramType, paramName);
javaWriter.endMethodSignature();
javaWriter.endMethod(); // <== Regardless of the type definition or modifier??
```

**Comment by Pedramrn** [comment]
So how this is done with the latest version?
I couldn't find anything related in linked issues.

**Comment by sormuras** [comment]
See https://github.com/square/javapoet#parameters which refers to https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/ParameterSpec.java#L121 and following lines. Especially, all the `addAnnotation[s](...)` methods.
