### ISSUE TITLE
Should there be an API for calling super.method?

### ISSUE THREAD

**Issue by perezd** [square/javapoet#500]
I wonder if this is common enough that it'd be worth supporting that as part of an API? Thinking `MethodSpec.Builder.callSuper()`

**Comment by swankjesse** [comment]
It’s probably more work for people to remember that that exists than to just call super the current way.

**Comment by perezd** [comment]
What is the current way? Manual add statement?

**Comment by sormuras** [comment]
Have a look at https://github.com/sormuras/poetry/blob/master/src/main/com/github/sormuras/poetry/Poetry.java#L183 or the real meat at https://github.com/sormuras/poetry/blob/master/src/main/com/github/sormuras/poetry/Poetry.java#L187
Just add a `super.` and you're done.
