### ISSUE TITLE
ArrayIndexOutOfBoundsException instead of friendly message when format index incorrect

### ISSUE THREAD

**Issue by kenzierocks** [square/javapoet#504]
When some code does something like `codeBlock.add("$0L", "myFirstParam")`, an ArrayIndexOutOfBoundsException is thrown. It isn't obvious that the indexed parameters are supposed to be 1-based, especially when [the code itself](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/CodeBlock.java#L148) states they are 0-based!

The comment should either be fixed to say that it is 1-based OR the code should be fixed to be 0-based. I would prefer the latter as it fits with nearly every Java index system.

Additionally, examples of indexed parameters should be added to the README and the code should tell you when your index is too low, rather than emitting an ArrayIndex exception.

**Comment by JakeWharton** [comment]
Changing to 0-based is too big of a change and will break consumers. We're
like String.format which is 1-based.

**Comment by swankjesse** [comment]
That link is referring to the varargs index, which is 0-based. You’re misinterpreting an implementation detail.

**Comment by kenzierocks** [comment]
Hmm, ok. Still, I'd love an example in the README.

**Comment by JakeWharton** [comment]
There's a bunch of examples in Wire, if you're just looking for examples:
https://github.com/square/wire/blob/master/wire-java-generator/src/main/java/com/squareup/wire/java/JavaGenerator.java#L1141-L1142
