### ISSUE TITLE
How to edit a existed java source file?

### ISSUE THREAD

**Issue by Ahaochan** [square/javapoet#505]
Hi!
i have a existed java source file. such as:
```
public class A{
    public int a;
    public long b;
    public void methodA(){}
}
```
now i want to remove `int a` and 'methodA()'.
how to do?
i hope get
```
public class A{
    public long b;
}
```

**Comment by JakeWharton** [comment]
JavaPoet is only for generating new files. Try [Spoon](http://spoon.gforge.inria.fr/) for manipulating existing files.

**Comment by SunShineShine** [comment]
Spoon can only parse source code？？

**Comment by rvaladez34** [comment]
Is this still the case? Can javapoet not modify existing java files?

**Comment by JakeWharton** [comment]
Yes. And it's not going to be added.
