### ISSUE TITLE
How change import order?

### ISSUE THREAD

**Issue by frank780117** [square/javapoet#508]
Hi,

I try to follow guild to create new JavaFile.

like 
```
package com.frank.dao.map;

import com.frank.domain.CmsImageConvertConf;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;

public class CmsImageConvertConfRowMapper implements RowMapper<CmsImageConvertConf> {
  public CmsImageConvertConf mapRow(ResultSet rs, int index) throws SQLException {
    // ...
  }
}
```

But I want to import java package first, and other last,
how can I customize import order? I cannot find relation method on JavaFile class

**Comment by swankjesse** [comment]
You cannot customize the import order. In this case JavaPoet follows the Google Java Style Guide.
https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing
