### ISSUE TITLE
Creating new class on top of another one

### ISSUE THREAD

**Issue by gnom7** [square/javapoet#510]
Hello, help me please to figure out if is there any way to create new java class on top of another (for instance I'm interesting in copying stuff from one class to my new one and then add or remove some fields/methods)

**Comment by JakeWharton** [comment]
JavaPoet is for authoring new classes directly. If you want to modify an existing class consider something like [Spoon][1].

 [1]: http://spoon.gforge.inria.fr/

**Comment by gnom7** [comment]
Thanks
