### ISSUE TITLE
Document or blog advantage of Java Poet over templated approach.

### ISSUE THREAD

**Issue by nicenemo** [square/javapoet#511]
Coming from .NET I used code generation with T4 templates.  For Java I found Java Poet First and a Velocity based approach second(https://deors.wordpress.com/2011/10/31/annotation-generators/). I think writing, reading and maintaining generators using templates is easier than the DSL approach of Java Poet. Am I wrong and why? If not where is Java Poet the better thing to use?

**Comment by eamonnmcmanus** [comment]
FWIW I use Velocity-compatible templates with [AutoValue](https://github.com/google/auto/tree/master/value). I think opinions differ on the two approaches. Personally I find code-generating code hard to understand in all but the most trivial of cases, especially when the language being generated is the same as the language doing the generation. But templates can also get pretty [unwieldy](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/autovalue.vm#L98).

**Comment by JakeWharton** [comment]
Automatic imports, automatic ordering of source members, automatic
formatting, automatic name collision avoidance. When you do templates you
bear the burden of all these tedious tasks and repetitive ceremony
yourself. Templates are also ill suited for incremental building of files
through delegation. You can't conditionally have a method contribute a
field, constructor param, constructor statement, and a method without
either building up your own object model or spreading the conditional logic
in multiple places.

**Comment by eamonnmcmanus** [comment]
I think @nicenemo is right that it would be good to make those arguments somewhere more accessible, perhaps in the documentation of JavaPoet or perhaps in a blog post that is linked to from that documentation.

**Comment by nicenemo** [comment]
AutoValue is almost exactly what I wanted. But after discussion with a
coworker we might change to some BeanInfo like generation and then Java
Poet does a better job generating a projection of a datamodel.

Op 18 okt. 2016 12:49 a.m. schreef "Éamonn McManus" <
notifications@github.com>:
>
> FWIW I use Velocity-compatible templates with AutoValue. I think opinions
differ on the two approaches. Personally I find code-generating code hard
to understand in all but the most trivial of cases, especially when the
language being generated is the same as the language doing the generation.
But templates can also get pretty unwieldy.
