### ISSUE TITLE
Support named parameters

### ISSUE THREAD

**Issue by cconroy** [square/javapoet#518]
The positional parameter API can become unwieldy in long statements or code blocks. 

If we had named parameters, then a lot of generated code could more easily be represented by block templates instead of statement-by-statement poet API calls.

The exact syntax is TBD, but something like the following:

```
$someType:T $someName:N = new $someType:T();
while (etc) {
  $someName.foo();
  ...
}
```

**Comment by swankjesse** [comment]
I particularly like this because it gets us the best of both worlds – JavaPoet’s composability, plus the code-familiarity you usually get with template systems. We might even convince our AutoValue friends to use this!

**Comment by swankjesse** [comment]
Shipped!
