### ISSUE TITLE
Do not import from java.lang

### ISSUE THREAD

**Issue by theangrydev** [square/javapoet#519]
There's no need to have imports from java.lang

**Comment by kenzierocks** [comment]
It's done to prevent collisions by default. You can disable the imports with `JavaFile.skipJavaLangImports`.

**Comment by theangrydev** [comment]
Thanks for the info!

**Comment by JakeWharton** [comment]
More like there's no reason for javac to import java.lang by default in
over a decade.

**Comment by tbroyer** [comment]
See also https://github.com/square/javapoet/issues/77#issuecomment-69699316 (and following comments), and https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/JavaFile.Builder.html#skipJavaLangImports-boolean-
