### ISSUE TITLE
Suggest try-with-resource controlFlow style

### ISSUE THREAD

**Issue by peter-lawrey** [square/javapoet#534]
Instead of writing

```java
block.beginControlFlow(conditionStatement);
block.addStatement(statement);
block,endControlFlow();
```

which can get confusing when you have multiple nested blocks you could allow the following pattern

```java
try (ControlBlock _1= block.controlFlow(conditionStatement)) {
    block.addStatement(statement);
}
```

as these nest more naturally in code and there is less chance you will be confused about where to place the end of block

```java
try (ControlBlock _1= block.controlFlow(conditionStatement)) {
    block.addStatement(statement);
    try (ControlBlock _2= block.controlFlow(conditionStatement2)) {
        block.addStatement(statement2);
    }
    block.addStatement(statement3);
}
```

This can be implemented by making `ControlBlock` a `Closeable` where `close()` calls `endControlBlock()`

**Comment by peter-lawrey** [comment]
BTW I am happy to issue a PR if there is interest.

**Comment by swankjesse** [comment]
I think if we were going to go this way we'd instead want to offer an AST-style builder. Another option if you're getting tangled up in control flow is to build the code you're proposing as a utility class.

**Comment by giantm** [comment]
Also, you could build the nested block in a CodeBlock, then:

Builder.beginControlFlow(whatever)
    .add( nestedBlock )
    .endControlFlow();

I would assume there is much less chance of getting lost if it’s all in one statement.

**Comment by peter-lawrey** [comment]
Closed for now.
