### ISSUE TITLE
In line imports for fields

### ISSUE THREAD

**Issue by Zeyad-37** [square/javapoet#535]
I am trying to generate a file and sometimes i need to import another generated class. So the import has to be in line. 
private com.example.GeneratedClass generatedClass;

But i was not able to achieve this. I had to import them manually.

**Comment by JakeWharton** [comment]
Are you using a ClassName with the fully-qualified name of the generated
class for the field spec?

**Comment by Zeyad-37** [comment]
Yes, like this.

TypeName typeName = ClassName.get(pkg, vName);
FieldSpec.builder(typeName, variableName);

**Comment by ronshapiro** [comment]
Why do you need it fully qualified? But if you do, what about using $L
instead of $T?

**Comment by Zeyad-37** [comment]
@ronshapiro could please elaborate on that. code please :)

**Comment by ronshapiro** [comment]
Oh sorry, I forgot that fields are not specified with the same formatting as a CodeBlock is. But my original question still stands: why does it matter that the type of the field needs to be fully qualified?

**Comment by Zeyad-37** [comment]
@ronshapiro because if i want to add a field type from a generated file, the outcome is just the class name and is missing the import. With alt-enter, Android Studio adds the full path.
Like this:

Generated File:
private GeneratedClass generatedClass; // GeneratedClass would be unimported, giving a compilation error.

After importing (alt-enter):

private com.example.GeneratedClass generatedClass;

If i have multiple instances of that class i always have to add the full path.

public void setGeneratedClass(List<com.example.GeneratedClass> generatedClass) {
    this.generatedClass = generatedClass;}

  public List<com.example.GeneratedClass> getGeneratedClass() {
    return generatedClass;}

**Comment by tbroyer** [comment]
Isn't your issue then that the import statement isn't generated? (IIUC)

**Comment by Zeyad-37** [comment]
@tbroyer yes.

**Comment by JakeWharton** [comment]
I still fail to see what JavaPoet is doing wrong. It will either emit the
fully-qualified type or emit and import and simple name. Can you express
you bug in the form of a test case?

**Comment by Zeyad-37** [comment]
I am trying to implement an annotation processor that generates a RealmObject from a POJO, the same fields and getters and setters. A case of it is that the class(A) would have a field of type another POJO(B) that also has another class generated(Gen_B) already. I would like to have this the (Gen_A) would have Gen_B is the field type not B. But the problem is that the A_Gen would have the field unimported and android studio prompts me to import the field to get ride of the compilation error. And when i do import it, android studio import the field inline, by explicitly expressing the full path of the class, even if the field is expressed multiple time, like with its getters and setters. I would like javapoet to generate the file with the inline imports.

Current output :
```
public class Example extends RealmObject {
    public Example2 example2;
    
    public Example2 getExample2(){
        return example2;
    }
    public void setExample2(Example2 example2){
        this.example2 = example2;
    }
}
```
Desired output:
```
public class Example extends RealmObject {
    public com.example.Example2 example2;

    public com.example.Example2 getExample2(){
        return example2;
    }
    public void setExample2(com.example.Example2 example2){
        this.example2 = example2;    
    }
}
```

JavaPoet Code:
```
for (int i = 0, allElementsSize = allElements.size(); i < allElementsSize; i++) {
            Element element = allElements.get(i);
            if (element.getKind().isField()) {
                if (element.getAnnotation(Ignore.class) == null) {
                    TypeName typeName = TypeName.get(element.asType());
                    String variableName = element.getSimpleName().toString();
                    FieldSpec.Builder builder;
                    // TODO: 12/18/16 Try to remove annotation!
                    if (element.getAnnotation(FindMapped.class) == null)
                        builder = FieldSpec.builder(typeName, variableName);
                    else {
                        if (isCollection(typeName.toString())) {
                            String name = typeName.toString().split("<")[1];
                            String[] split = name.split("\\.");
                            String vName = split[split.length - 1];
                            vName = "AutoMap_" + vName.split(">")[0];
                            typeName = ParameterizedTypeName.get(ClassName.get("io.realm", "RealmList"),
                                    ClassName.get(pkg, vName));
                            builder = FieldSpec.builder(typeName, variableName);
                        } else {
                            String[] split = typeName.toString().split("\\.");
                            String vName = "AutoMap_" + split[split.length - 1];
                            typeName = ClassName.get(pkg, vName);
                            builder = FieldSpec.builder(typeName, variableName);
                        }
                    }
                    for (Modifier modifier : element.getModifiers()) {
                        builder.addModifiers(modifier);
                    }
                    if (element.getAnnotation(PrimaryKey.class) != null)
                        builder = builder.addAnnotation(PrimaryKey.class);
                    if (element.getAnnotation(SerializedName.class) != null)
                        builder = builder.addAnnotation(AnnotationSpec.builder(SerializedName.class)
                                .addMember("value", "$S", element.getAnnotation(SerializedName.class).value())
                                .build());
                    String variableNameCamelCase = CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, variableName);
                    if (!(element.getModifiers().contains(Modifier.FINAL) && element.getModifiers().contains(Modifier.STATIC))) {
                        // add setter
                        classBuilder.addMethod(MethodSpec.methodBuilder("set" + variableNameCamelCase)
                                .addModifiers(Modifier.PUBLIC)
                                .returns(void.class)
                                .addParameter(typeName, variableName)
                                .addCode("this.$N = $N;", variableName, variableName)
                                .build());
                        // add getter
                        classBuilder.addMethod(MethodSpec.methodBuilder("get" + variableNameCamelCase)
                                .addModifiers(Modifier.PUBLIC)
                                .returns(typeName)
                                .addCode("return $N;", variableName)
                                .build());
                        if (!element.asType().getKind().isPrimitive()) {
                            isEmptyImplementation += isEmptyParameterName + "." + variableName + " == null &&\n";
                        }
                    }
                    classBuilder.addField(builder.build());
                }
            }
        }
```

**Comment by JakeWharton** [comment]
Why do you want fully qualified types instead of imports?

**Comment by Zeyad-37** [comment]
because i get a complication error if they are not.

**Comment by Zeyad-37** [comment]
<img width="641" alt="screen shot 2016-12-21 at 2 48 21 am" src="https://cloud.githubusercontent.com/assets/5938141/21373489/09cb0d64-c728-11e6-89aa-09b954c8166d.png">

**Comment by ronshapiro** [comment]
What is the error you're getting?

**Comment by Zeyad-37** [comment]
Error:(54, 42) error: cannot find symbol class AutoMap_RepoModel

<img width="942" alt="screen shot 2016-12-21 at 2 51 14 am" src="https://cloud.githubusercontent.com/assets/5938141/21373525/6b35812e-c728-11e6-8541-ef5fe13165cf.png">

**Comment by ronshapiro** [comment]
And how does that file generated?

**Comment by Zeyad-37** [comment]
https://github.com/Zeyad-37/UseCases/blob/master/processor/src/main/java/com/zeyad/usecases/codegen/AutoMapProcessor.java

**Comment by JakeWharton** [comment]
A quick guess is you're using the wrong package for that ClassName. What
import is emitted for that type?

**Comment by Zeyad-37** [comment]
This method returns the package of the annotated file. which is the same package for the generated file, but in the build/generated/source/apt/debug/...
```
package com.zeyad.usecases.codegen;

import javax.lang.model.element.Element;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Types;

/**
 * @author zeyad on 12/12/16.
 */
class TypeUtil {
    /**
     * Returns the name of the package that the given type is in. If the type is in the default
     * (unnamed) package then the name is the empty string.
     *
     * @param type given type
     * @return package name
     */
    static String packageNameOf(TypeElement type) {
        while (true) {
            Element enclosing = type.getEnclosingElement();
            if (enclosing instanceof PackageElement) {
                return ((PackageElement) enclosing).getQualifiedName().toString();
            }
            type = (TypeElement) enclosing;
        }
    }
}
```

**Comment by JakeWharton** [comment]
So is this a feature request or a bug report? If you want fully-qualified
types you can call toString on a TypeSpec and skip the JavaFile. Otherwise
we need a failing test case that we can execute that demonstrates that the
import feature isn't working as expected.

**Comment by Zeyad-37** [comment]
Well if that was a feature or something that was supposedly achievable then i would say a bug report. if not, then a feature

**Comment by tbroyer** [comment]
AFAICT, your problem has nothing to do with JavaPoet. Your `UserModel` and `RepoModel` are in the same package, and the generated `AutoMap_UserModel` and `AutoMap_RepoModel` are also in the same package, so JavaPoet is right in not generating neither an import nor a qualified name.

Your problem is that you don't generate the source files in the appropriate folder hierarchy corresponding to the package: you pass the simple class name to the `javax.annotation.processing.Filer`, rather than the qualified class name. BTW, you also attempt to create the same file twice with different content (your mappers).
