### ISSUE TITLE
Add API for comments on Type level

### ISSUE THREAD

**Issue by Zubnix** [square/javapoet#536]
Currently it seems TypeSpec.Builder does not allow to add line and/or block comments (or arbitrary code). I would like to add a copyright header to my generated types. Currently the only way to do this, is inside the Javadoc which is not really desirable.

**Comment by tbroyer** [comment]
How about [`JavaFile.Builder.addFileComment`](https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/JavaFile.Builder.html#addFileComment-java.lang.String-java.lang.Object...-)?

**Comment by Zubnix** [comment]
oh look at that :)

**Comment by snturk** [comment]
Is there a way to add comments **inside** an interface/class that created by `TypeSpec.Builder`?

Example:

```
public interface MyInterface {
    // Comment Line
}
```
