### ISSUE TITLE
why "ClassName.bestGuess("int")" get error?

### ISSUE THREAD

**Issue by Jude95** [square/javapoet#540]

**Comment by peckb1** [comment]
There are two issues with using `ClassName.bestGuess("int")`.

`ClassName.bestGuess( ~ )` assumes that the input is ASCII and _follows typical Java style (lowercase package names, UpperCamelCase class names)_: such as `java.util.Observer`, or `Integer`. 

The String `"int"` is then assumed to be a string representing the package `int` with no class given to try and create a `ClassName` for.

Additionally, primitive types cannot be represented as a `ClassName`. Even if you were to use the `ClassName.get(int.class)` method to avoid the guessing nature of `.bestGuess( ~ )`, an `IllegalArgumentException` would still be thrown.

**Comment by JakeWharton** [comment]
Wow, thanks @peckb1! Somehow this issue slipped through the cracks without a reply.
