### ISSUE TITLE
Generic parameter <T extends MyClass & MyInterface>

### ISSUE THREAD

**Issue by Pedramrn** [square/javapoet#543]
I couldn't find any documentation for this kind of generic types.

How to generate something like this:
`public static <T extends MyClass & MyInterface> MyOtherClass someMethod(T type)`

The problem is the `& MyInterface` part.

**Comment by sormuras** [comment]
See https://github.com/square/javapoet/blob/master/src/test/java/com/squareup/javapoet/TypeSpecTest.java#L584 and following lines.

**Comment by tbroyer** [comment]
Either `withBounds` or passing the bounds to the static factory: [`TypeVariableName.get("T", myClass, myInterface)`](https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/TypeVariableName.html#get-java.lang.String-com.squareup.javapoet.TypeName...-)
