### ISSUE TITLE
Return same class as method parameter

### ISSUE THREAD

**Issue by wadinj** [square/javapoet#545]
Hello,

I try to generate a class "Customer" and I have a method like this : 
`public void addCustomer(Customer c) {}`
How can I generate that ? I cannot reference Customer class as parameter because the generation is in progress.
`currentMethodBuilder.addParameter(/* How can I get the object "Class" of my current generated class, args.toCamelCase());`

Thanks a lot,
Jonathan

**Comment by tbroyer** [comment]
This is #258 (and many other related issues)
