### ISSUE TITLE
Inner interface reference through inheritance

### ISSUE THREAD

**Issue by RomainPiel** [square/javapoet#546]
I'm facing a small issue with javapoet:

Let’s say I have a class like
```java
class A {
   public interface MyInterface {}
}
```
If I want to generate a class extending `A` and referencing `MyInterface` it will always use a qualified reference:
```java
class B extends A {
  A.MyInterface myInterface = new A.MyInterface() {}
}
```
Instead of:
```java
class B extends A {
  MyInterface myInterface = new MyInterface() {}
}
```

As `MyInterface` is public and `B` extends `A`, we don't really need this fully qualified import. Is there any way to get the format of the latter?

**Comment by tbroyer** [comment]
FWIW, you actually need the qualified name (or import) to disambiguate with a possible class/interface of the same name in the same package as B.

**Comment by JakeWharton** [comment]
You can also just emit a raw string referencing the class name instead of a
ClassName but you're taking on risk.

**Comment by RomainPiel** [comment]
That makes sense, thanks both!
