### ISSUE TITLE
Hardcoded line separator bug

### ISSUE THREAD

**Issue by dmytro-grankin** [square/javapoet#552]
The bug occurs when the Javadoc text formed with Windows `\r\n` line separator.

For example, we have the comment `A\r\n\r\nB\r\n`. Because `JavaPoet` uses hardcoded line separator, `CodeWriter#emitAndIndent(String)` splits the comment on the next lines: `A\r`, `\r`, `B\r`. As the second line is not empty, indentation emitted.

It's a problem, if someone wants to test generation of Javadoc, that uses `JavaPoet`. Generated Javadoc depends on a platform (Windows or Unix). On Unix the Javadoc empty lines are really empty, but on Windows they are indented. In reason of this unreal to test generation of a Javadoc on different platforms.

Hardcoded line separator may cause and others bugs also.

**Comment by swankjesse** [comment]
Can fix.

**Comment by dmytro-grankin** [comment]
What I get for `A\r\n\r\nB\r\n`:

```java
/**
 * A\r\n\
 * \r\n\
 * B\r\n\
 */
```

What I expect:

```java
/**
 * A\r\n\
 *\r\n\
 * B\r\n\
 */
```

The difference is in the line containing only `\r\n`. Currently, it contains a redundant space.

The fix, that I see is just to use `System.lineSeparator()` instead of a hard-coded `\n` in the whole library code or at least in `CodeWriter#emitAndIndent(String)`.

**Comment by topalavlad** [comment]
I'm not super familiar with this project, but using `System.lineSeparator()` also seems error prone since you might have a string with `\r\n` but on an operating system that uses `\n`. I would still go with the `\r?\n` regex.
