### ISSUE TITLE
Add support for get/set methods for fields

### ISSUE THREAD

**Issue by dhoffer** [square/javapoet#553]
JavaPoet has nice support for fields and methods but what about properties?  It would be great if when creating fields it could also create the optional getters and setters for the field.

**Comment by JakeWharton** [comment]
This has come up a few times. Our stance is here: https://github.com/square/javapoet/pull/484#issuecomment-236918486

Basically we're a tool for generating exactly what you tell us and not a tool for inferring code to generate. You can write a static method or helper class which can produce a field, getter, and setting in one shot onto a `TypeSpec.Builder`.

**Comment by sormuras** [comment]
https://github.com/square/javapoet/issues/494 too
