### ISSUE TITLE
Remove final modifiers

### ISSUE THREAD

**Issue by sergiofigueras** [square/javapoet#554]
Hello guys,

Well, some classes like "JavaFile" makes it really hard to test using mocks, because we would need to use Powermock (and its definitely NOT a good approach).

Does anyone have any plan to remove final modifiers from those classes? Why they exists? Can we remove this design decision?

Thanks!

Sergio.

**Comment by trevjonez** [comment]
you can mock finals with mockito: https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#unmockable

**Comment by sergiofigueras** [comment]
@trevjonez the problem with that is that it makes use of bytecode instrumentation, which is definitely a bad practice. In other hand, I can't see a good design value on making those classes final. The attributes are already final, so, why preventing anyone from extending it or use bytecode instrumentation to test that?

Thanks!

**Comment by JakeWharton** [comment]
You don't need to mock JavaFile. You can validate interaction by calling
toString() and asserting the generated code or by inspecting its public
fields.

**Comment by swankjesse** [comment]
Here’s an example if you’d like to be inspired.
https://github.com/square/wire/blob/master/wire-tests/src/test/java/com/squareup/wire/java/JavaGeneratorTest.java
