### ISSUE TITLE
support ParameterizedTypeName with no type arguments

### ISSUE THREAD

**Issue by h908714124** [square/javapoet#555]
Currently, the following throws `IllegalArgumentException("no type arguments: java.lang.String")`:

```java
public static void main(String[] args) {
  ParameterizedTypeName.get(ClassName.get(String.class));
}
```

When user code is optionally parameterized, i.e. it can be `ClassName` or `ParameterizedTypeName`, I use `TypeName` and then have to use the following helpers:

````java
static ClassName rawType(TypeName typeName) {
  if (typeName instanceof ParameterizedTypeName) {
    return ((ParameterizedTypeName) typeName).rawType;
  }
  return ((ClassName) typeName);
}

static List<TypeName> typeArguments(TypeName typeName) {
  if (typeName instanceof ParameterizedTypeName) {
    return ((ParameterizedTypeName) typeName).typeArguments;
  }
  return Collections.emptyList();
}
````

If `ParameterizedTypeName` would allow an empty list of type args, it would be a generalisation of `ClassName` and could be used instead of `TypeName` in this situation.

**Comment by swankjesse** [comment]
Unfortunately, `String<>` isn’t a valid type.

**Comment by h908714124** [comment]
I used `String` just for a minimal runnable example. In practice, given a typeElement from `RoundEnvironment#getElementsAnnotatedWith`, I do this:

````java
private static TypeName maybeParameterized(TypeElement typeElement) {
  if (typeElement.getTypeParameters().isEmpty()) {
    return ClassName.get(typeElement);
  }
  List<TypeVariableName> typevars = typeElement.getTypeParameters().stream()
      .map(TypeVariableName::get)
      .collect(toList());
  TypeVariableName[] typeArguments = typevars.toArray(new TypeVariableName[typevars.size()]);
  return ParameterizedTypeName.get(ClassName.get(typeElement), typeArguments);
}
```` 

Here, the last line would throw `IllegalArgumentException` if the `typeElement.getTypeParameters().isEmpty()` had not handled the unparameterized case.

**Comment by JakeWharton** [comment]
You can call TypeName.get(typeElement.asType()) which should do all that
for you.

**Comment by h908714124** [comment]
Thanks @swankjesse that's surely an improvement. Still, I'd like to put this suggestion up for discussion, because all these casts are not pretty in my eyes...

**Comment by h908714124** [comment]
oops sorry @JakeWharton

**Comment by h908714124** [comment]
@JakeWharton @swankjesse 
The core of the matter is that there's currently no good representation of an _annotated class_:

* `TypeName` is too wide, it includes primitives.
* `ClassName` is too narrow, it can't represent a class with one or more type parameters.
* `ParameterizedTypeName` is also too narrow, it can't represent a class with zero type parameters.

As a consequence, pretty much every annotation processor handles this bread-and-butter use case by using `TypeName` and doing `instanceof` and casts later on. That's terrible!

I would suggest looking at one of the following options:

* widening `ParameterizedTypeName` so that it can also represent `ClassName`, OR
* adding some new type that's wide enough to include `ParameterizedTypeName` and `ClassName`, but doesn't include primitives

Thanks for listening.

**Comment by swankjesse** [comment]
I guess I don’t understand why including primitives is bad?

**Comment by h908714124** [comment]
Including primitives isn't bad _per se_, but there are common situations where `TypeName` isn't appropriate.

For example, suppose you're writing an annotation processor for an annotation that's `@Target(ElementType.TYPE)`: We already know it can't appear on an `int`, for instance. It can only be a class, interface or enum. For brevity, let's call that `X`.

The javapoet user will choose `TypeName` to represent `X`, because that's what `TypeName.get(typeElement.asType())` returns, and javapoet doesn't offer any alternatives. So imagine we want to check if `X` has type arguments, supposedly for validation: 

````java
private static boolean checkParameterized(TypeName typeName) {
  if (typeName instanceof ParameterizedTypeName) {
    return true;
  }
  if (!(typeName instanceof ClassName)) {
    throw new AssertionError();
  }
  return false;
}
````
This becomes even more messy if you want to validate that the annotated class is not nested:

````java
private static boolean checkNested(TypeName typeName) {
  if (typeName instanceof ParameterizedTypeName) {
    ParameterizedTypeName realType = ((ParameterizedTypeName) typeName);
    return realType.rawType.enclosingClassName() != null;
  }
  if (!(typeName instanceof ClassName)) {
    throw new AssertionError();
  }
  ClassName realType = ((ClassName) typeName);
  return realType.enclosingClassName() != null;
}
````

Those are just two examples where you need to do `instanceof` checks, but I could obviously show you more. Now let's imagine that `ParameterizedTypeName` is made more flexible, so that it can be used to represent `X`, even if `X` doesn't have type arguments. Then the two methods could look like this:

````java
private static boolean checkParameterized(ParameterizedTypeName typeName) {
  return !typeName.typeArguments.isEmpty();
}

private static boolean checkNested(ParameterizedTypeName typeName) {
  return typeName.rawType.enclosingClassName() == null;
}
````
`TypeName` isn't bad, it's just too general in this case.

**Comment by swankjesse** [comment]
Got it. I think it's probably too late for this kind of a model change.

**Comment by jbgi** [comment]
@h908714124 personaly I would not do validation on javapoet models, but rather directly on java.lang.model: as I see it javapoet is a rather lossy model of java lang  which main/only purpose is to output java files in a composable manner, leaving most safety to the compiler of the output file.
If using java.lang.model for validation is not possible for your case then maybe you ought to use a more precise model than javapoet, ie: https://github.com/phax/jcodemodel

**Comment by h908714124** [comment]
@jbgi how'd you find this? the issue is closed!
Thanks for these pointers, anyway.
