### ISSUE TITLE
Javapoet not importing classes

### ISSUE THREAD

**Issue by amitkma** [square/javapoet#561]
I am trying to create a method as following.

methodSpecBuilder.addCode(String.format("try {\n"
            + "     return BackgroundExecutor.getInstance().submit(new Callable<%s>() {\n"
            + "        @Override\n"
            + "        public %s call() throws Exception {\n"
            + "          %s;\n"
            + "        }\n"
            + "      });\n"
            + "    } catch (InterruptedException e) {\n"
            + "      e.printStackTrace();\n"
            + "      return null;\n"
            + "    } catch (ExecutionException e) {\n"
            + "      e.printStackTrace();\n"
            + "      return null;\n"
            + "    }", binding.getReturnType(), binding.getReturnType(), returnStatment));

But after writing the file, Code is not importing BackgroundExecutor, Callable or Exception etc.
How can I import those classes?

**Comment by ronshapiro** [comment]
Please read the docs on using $T in place of types. Without that, javapoet can't know what is the fully qualified name that you want to use.

**Comment by tbroyer** [comment]
You're never telling JavaPoet which classes those are and what (and whether) to import.
You need to use `$T` placeholders (and btw probably replace your `String.format` too) and pass the types (either as `java.lang.Class` or JavaPoet `ClassName`). You could also build the anonymous class using a `TypeSpec`.

Something like the following (assuming `binding.getReturnType()` returns a string with the fully qualified class name):

```java
methodSpecBuilder
    .beginControlFlow("try")
    .addStatement("return $T.getInstance().submit($L)",
        BackgroundExecutor.class,
        TypeSpec.anonymousClassBuilder("")
            .addSuperinterface(ParameterizedTypeName.get(ClassName.get(Callable.class), ClassName.bestGuess(binding.getReturnType())))
            .addMethod(MethodSpec.methodBuilder("call")
                .addAnnotation(Override.class)
                .addModifier(PUBLIC)
                .addException(Exception.class)
                .addStatement("$L", returnStatement)
                .build())
            .build())
    .nextControlFlow("catch ($T e)", InterruptedException.class)
    .addStatement("e.printStackTrace()")
    .addStatement("return null")
    .nextControlFlow("catch ($T e)", ExecutionException.class)
    .addStatement("e.printStackTrace()")
    .addStatement("return null")
    .endControlFlow();
```

**Comment by amitkma** [comment]
Thanks @tbroyer and @ronshapiro It worked.
