### ISSUE TITLE
relation to java compiler api

### ISSUE THREAD

**Issue by jackzhp** [square/javapoet#563]
Is this project some kind of related to 
    com.sun.source.tree and 
    com.sun.source.util ?

or the Mirror API? 

seems not! I would say it would be much better if the logic is based on abstract syntax tree. is there any difficulty to do so? Only because it is hard to understand what other people wrote, it is much easier to write my own copy?

jack

**Comment by swankjesse** [comment]
It is not! We took this approach because we find it more productive. If you’d prefer another approach, you can do what you like.
