### ISSUE TITLE
Is it possible to create List<Field> FieldSpec?

### ISSUE THREAD

**Issue by zeroarst** [square/javapoet#566]
I want to generate a field that comes with `List<Field>` type or any types of List.
It seems that I have to give `Type` or `TypeName` for the builder. However, I don't know how to get the `Type` of `List<Field>`. Currently I solve this by defining a `List<field> list` field in the processor class and use the reflection to get it: `this.getClass().getDeclaredField("list").getGenericType()` I wonder is there any proper way to do it?

**Comment by tbroyer** [comment]
You're looking for a [`ParameterizedTypeName`](https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/ParameterizedTypeName.html)

```java
ParameterizedTypeName.get(List.class, Field.class)
```
