### ISSUE TITLE
Generic parsing

### ISSUE THREAD

**Issue by creati8e** [square/javapoet#569]
I have a string, for example "java.util.Map<java.lang.String,android.util.Pair<java.lang.Boolean,java.lang.Long>>". How can i build ParametrizedTypeName from this string? I don't have any TypeMirror.

**Comment by JakeWharton** [comment]
You can write your own parser for this using `<` and `,` as the tokens to break on. Then call `ClassName.bestGuess` on each string which represents a type. Then build up a `ParameterizedTypeName` using the resulting structure.
