### ISSUE TITLE
'$' clashes in source code

### ISSUE THREAD

**Issue by ronshapiro** [square/javapoet#570]
I'm not sure this is necessarily an issue, but it definitely was unexpected when I just encountered it.

Dagger creates proxies for `@Provides` methods that are inaccessible from the perspective of the `@Component` which uses them. These proxy methods have signature that look identical to the methods they call, forwarding all of the parameters along to the user-written method.

I encountered a problem where the method being proxied is itself generated, and uses `$` in the parameter names (it seems to be using the FQCN with periods replaced with '$'). So the generated method I'm trying to create looks like:

```java
public static Foo proxyFoo(Bar com$example$bar$Bar) {
  return FooModule.foo(com$example$bar$Bar);
}
```

This is failing as the `CodeBlock` is seeing `$e`, which isn't a valid escape sequence.

I can (and probably will) just double escape '$' here, but it's hard to predict all of the cases where this could arise. What if the method also has a '$' in it?

It would be likely very challenging to do this for `1.x`, but if there's a `2.x` in the books, this might be a good thing to consider. KotlinPoet decided to use `%`, maybe for this same reason? Maybe and `@` sign if you want to stray away from `%` since it's similar to `String.format`?

**Comment by swankjesse** [comment]
Are you using `$N` to name your method? That shouldn’t double-escape.

**Comment by ronshapiro** [comment]
Ah, d'oh. We weren't, but we totally could have. We were adding the parameter directly without creating a `ParameterSpec`.
