### ISSUE TITLE
Only classes have super classes, not INTERFACE

### ISSUE THREAD

**Issue by mrgenco** [square/javapoet#583]
I am trying to generate code for JPA repository below using JavaPOET library but i am getting "only classes have super classes, not INTERFACE" error.

@Repository 
public interface UserRepository extends PagingAndSortingRepository<User, Long> { 
}

Here is the JavaPOET code i tried..

TypeSpec userRepository = TypeSpec.interfaceBuilder("UserRepository")
                .addAnnotation(Repository.class)
                .addModifiers(Modifier.PUBLIC)
                .superclass(ParameterizedTypeName.get(ClassName.get(PagingAndSortingRepository.class),  
                                                      ClassName.get(User.class),
                                                      ClassName.get(Long.class)))
                .build();

Any solution/best practice for generating interface extending a class? Thanks,

**Comment by JakeWharton** [comment]
Use addSuperinterface method instead of superclass for interfaces.
