### ISSUE TITLE
Zero-width version of $W

### ISSUE THREAD

**Issue by ronshapiro** [square/javapoet#588]
I'm looking into the possibility of removing google-java-format from Dagger (https://github.com/google/dagger/issues/368) and `$W` is a useful tool in adding line breaks when necessary, but sometimes I want the option of breaking if necessary, or no space at all. 

Consider this example: I want to write the following method invocations without thinking about how many arguments I'm about to pass:

```java
Foo_Factory.create(arg0, arg1, arg2);

Foo_Factory.create(
    arg0,
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
    ...,
    argN);
```

`$W` works for args `1..N` but in the first example, adding in a `$W` between `create(` and `arg0` would create an awkward space.

https://github.com/square/kotlinpoet/pull/281 is a similar attempt that maybe can be applied here as well?

**Comment by JakeWharton** [comment]
This is also needed for parameter lists. The first parameter never wraps.

**Comment by ronshapiro** [comment]
What are your thoughts on having `$W` inspect the previous character for insights on whether it should be zero-width or one-width?

In `foo($Warg1,$Warg2)`

**Comment by swankjesse** [comment]
I think that might be too clever. Maybe just like `$B` for optional-break?

**Comment by ronshapiro** [comment]
Fine by me. Cool if I send a PR?

**Comment by swankjesse** [comment]
Please do!
