### ISSUE TITLE
Please add Automatic-Module-Name manifest entries

### ISSUE THREAD

**Issue by io7m** [square/javapoet#589]
Hello!

It'd be great if `javapoet` published Automatic-Module-Name entries in the jar manifest for each module. This would assign the modules stable names to be used in (modular) Java 9 projects.

Of course, full modularization would be better, but `Automatic-Module-Name` is quick and easy.

**Comment by sormuras** [comment]
Adding a module descriptor is not that difficult either -- but needs an upgade to jdk 9. At least for compiling the `module-info.java` source file.

**Comment by JakeWharton** [comment]
We do not want to do that since it can break tools.

**Comment by sormuras** [comment]
You mean having a `module-info.class` in the root of the JAR file breaks tools? Because it ends with `.class` and can not be instantiated (or ignored) by older Java runtimes and custom class parsers/loaders?

**Comment by JakeWharton** [comment]
Yes

**Comment by io7m** [comment]
Thanks for the quick response!
