### ISSUE TITLE
more info in FieldSpec

### ISSUE THREAD

**Issue by vipsy** [square/javapoet#592]
Can't find a way to see if the FieldSpec is enum or not.

I am developing on an SPI and just have the `TypeSpec` to generate additional code.
I am iterating over all the fields and get FieldSpec, where I need to know if the types are primitive, enum, boxed primitive or custom objects. I can get primitive, boxed or objects based on `FieldSpec.type.isPrimitive()`  and other methods, but can't find a way to know if the FieldSpec is enum.

**Comment by swankjesse** [comment]
That isn't true in Java either. You need to access the referenced type to see if it's an enum.

```
class Taco {
  Cheese cheese; // enum? Only cheese knows.
}
```

**Comment by vipsy** [comment]
In `TypeSpec` I can see if `enumConstants.isEmpty()` but can't access `TypeSpec` of the field from `FieldSpec` as it only has `TypeName`.
