### ISSUE TITLE
CodeBlock.Builder.isEmpty()

### ISSUE THREAD

**Issue by JakeWharton** [square/javapoet#595]
This is useful when building things that are concatenated to check when you need to prepend a `+`, for example.

**Comment by ronshapiro** [comment]
Can you provide an example?

Because `CodeBlock`s are cheap, doing a `.build().isEmpty()` seems sufficient to me. In Dagger, when we need to concatenate code blocks, we create many small ones and then join them together at the end - which also has the nice benefit of encouraging less mutable state

**Comment by JakeWharton** [comment]
It's basically a series of 5 conditionals which need to optionally prepend a comma. I've also needed this in loops containing conditionals for prepending a comma. Since I don't know whether the previous conditionals have run or not, I need some other signal for knowing whether the code block is non-empty. I could keep a separate boolean but now I have to ensure its state is properly synchronized with the builder (I've done this in the past). While `build().isEmpty()` works, I still feel like having it on the builder is warranted as this has come up at least 3 times for me in the past.

**Comment by ronshapiro** [comment]
We have a number of utilities for joining code blocks in Dagger (https://github.com/google/dagger/blob/5e7dcda31247c04ac7cb2453b718a80776774b63/java/dagger/internal/codegen/CodeBlocks.java) - would something like those be useful? Should they be put somewhere common? 

Just as a comparison, Guava has shied away from `isEmpty()` checks on immutable collection builders with main point that accessors on builders are a smell. They're not directly analgous, but I wonder if a builder `isEmpty()` check is a shortcut to potentially better solutions (like joining code blocks).

**Comment by JakeWharton** [comment]
We have something similar in KotlinPoet: https://github.com/square/kotlinpoet/blob/87f4f1b0cb34c628b4f16c29bb26a5ccdb3aef32/src/main/java/com/squareup/kotlinpoet/CodeBlock.kt#L412-L421.

Assembling a list of CodeBlocks and then joining at the end would likely cover the majority of the cases that `isEmpty()` was meant to, so I'd be receptive.

**Comment by ronshapiro** [comment]
Maybe a joining() static method for CodeBlock that returns a Collector,
with necessary overloads? And also maybe a
CodeBlock.join(Iterable<CodeBlock>, String delimiter) convenience as well?
