### ISSUE TITLE
Update JavaPoet Javadoc

### ISSUE THREAD

**Issue by pushbit** [square/javapoet#597]
https://square.github.io/javapoet/1.x/javapoet/ is stuck back on 1.7.0.  A refresh to the latest version would be nice, or perhaps just link the README to https://javadoc.io/doc/com.squareup/javapoet/ instead.

**Comment by JakeWharton** [comment]
I do not like javadoc.io because you cannot deep link into it unless you remove frames. We'll update our hosted copy.

**Comment by swankjesse** [comment]
Javadoc updated with [Osstrich](https://github.com/square/osstrich/).
