### ISSUE TITLE
Check if type extends a specific class

### ISSUE THREAD

**Issue by WellingtonCosta** [square/javapoet#601]
Hi,

Anyone knows how to check a superclass of element?

Example: 

```java
@ValidateOnClick
Button button;
```

or

```java
@ValidateOnClick
ToggleButton button;
```

or

```java
@ValidateOnClick
ImageButton button;
```

I want to check if the element annotated with ```@ValidateOnClick``` is a ```Button``` or extends this class.

**Comment by JakeWharton** [comment]
JavaPoet cannot do this. It models names, not actual types or type hierarchies. You'll need to use the annotation processing APIs such as Types and ElementUtils.

**Comment by WellingtonCosta** [comment]
I'm trying exactly with Java Annotation Processing. I using both JavaPoet and Java Annotation Processing. I almost there.
