### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/javapoet/MethodSpec

### ISSUE THREAD

**Issue by sunshine763** [square/javapoet#610]
**I use the code in readme.md,but I got the error in the picture below,my android studio version is 3.0.1**
![z3 pif egy lwiiryri2w](https://user-images.githubusercontent.com/18045111/35604779-f04d754c-067e-11e8-8b00-3d893f94530a.png)

**my build.gradle:**
```
apply plugin: 'java-library'

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.squareup:javapoet:1.10.0'

}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"
```

But the same code is running successfully in android studio 2.1.1

How to solve this problem?Thanks.

**Comment by yanzhenjie** [comment]
I encountered the same problem in Android Studio V2.3.3 and Android Studio V3.0.1.  

The following is a description of the situation in Android Studio V2.3.3.
Gradle file of java module:
```
apply plugin: 'java-library'

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.squareup:javapoet:1.10.0'
}
```

Gradle file of project:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

Result of running `gradle [module-name]:dependencies --configuration compile` command:
```text
> Configure project :[module-name]
...

> Task :[module-name]:dependencies 
------------------------------------------------------------
Project :[module-name]
------------------------------------------------------------

\--- com.squareup:javapoet:1.10.0

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

I checked #580 carefully, but it seems to me not much help.

**Comment by yanzhenjie** [comment]
A friend found two solutions, can work, but I think this unscientific.

1, Modify [moduel-name].iml file of the java module, probably here:
```java
<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id=":[module-name]"...
  <component name="FacetManager">
    ...
  </component>
  <component name="NewModuleRootManager"...
    ...
    <orderEntry type="library" scope="PROVIDED" name="javapoet-1.7.0" ... />
  </component>
</module>
```
Delet `PROVIDED`, the modified result is as follows:
```java
...
<orderEntry type="library" scope="" name="javapoet-1.7.0" ... />
...
```

2, apply `idea` plugin
In your java module, apply this plugin:
```
apply plugin: 'java'
apply plugin: 'idea'

...
```
Then run the `gradle idea` command to generate the full path dependency.  Then you will see that your [module-name].iml file has changed.

But the downside to both is that you have to modify the [module-name].iml file or run `gradle idea` after each sync.

**Comment by yanzhenjie** [comment]
I seem to find the law, if it is in AndroidStudio, when the Android module and java modules coexist, just run java module this problem occurs. When in the idea, there is only one java module, and running the sample code does not have this problem.
Fortunately, if it is a complete Android project, that is, there are a few modules: api, processor, annotation, sample, gradle automatically compiled successfully generated class, does not happen this problem.

Great, thanks for this open source project.

**Comment by sunshine763** [comment]
Thanks for reply. Indeed, when the Android module and java modules coexist, just run java module this problem occurs.Is Gradle having problem?

**Comment by JakeWharton** [comment]
No action for JavaPoet to take. This is an IDE and rt.jar vs android.jar problem.
