### ISSUE TITLE
Generated enum is very long.

### ISSUE THREAD

**Issue by ToivoAdams** [square/javapoet#612]
Any way to make it more compact?
Ideally in one line.

Current result

  public enum Vars {
    bstr,

    A,

    B,

    Number,

    opcode,

    astr
  }

Preferred

  public enum Vars { bstr, A, B, Number, opcode, astr }

Thank you
Toivo

**Comment by swankjesse** [comment]
Sorry. The whitespace is fixed.

If later you added Javadoc to one of these, say `astr`, then that one would probably not be on the same line as the rest. And with our current codegen strategy the number of lines of diff between old and new is low, which is handy if you’re checking the generated sources into version control.
