### ISSUE TITLE
1.10.0 compile error 

### ISSUE THREAD

**Issue by tanpuer** [square/javapoet#613]
![error](https://user-images.githubusercontent.com/16443498/36139738-b3e42320-10d9-11e8-8f45-e36519c94ad2.jpg)
1.10.0 not work, but 1.9.0 dose.
Android studio 3.0.1 JDK1.7

**Comment by tbroyer** [comment]
1.10.0 actually requires JDK 1.8 now. See https://github.com/square/javapoet/pull/599#pullrequestreview-89481890

**Comment by ronshapiro** [comment]
JavaPoet shouldn't be on the classpath for Android projects, just the processor path. Try checking the dependency tree to see where you're getting JavaPoet and switch to the `annotationProcessor` scope accordingly
