### ISSUE TITLE
Type annotations on array types.

### ISSUE THREAD

**Issue by rluble** [square/javapoet#614]
Type annotations can be applied to the array type or any of its components. From JLS §[9.7.4](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.7.4):

> Type annotations can apply to an array type or any component type thereof (§10.1). For example, assuming that `A`, `B`, and `C` are annotation types meta-annotated with `@Target(ElementType.TYPE_USE)`, then given the field declaration:
>
> ```java
>@C int @A [] @B [] f;
>```
> `@A` applies to the array type `int[][]`, `@B` applies to its component type `int[]`, and `@C` applies to the element type int. For more examples, see §[10.2](https://docs.oracle.com/javase/specs/jls/se8/html/jls-10.html#jls-10.2).

In its current state javapoet lacks the expressivity regarding Java 8 `TYPE_USE` annotations and  makes the current usage `arraytype.annotated(typeAnnotation)` confusing. The annotation will be emitted preceding the type and hence applies to the component not to the array type.

This issue is related to #431.

**Comment by ronshapiro** [comment]
Yes

**Comment by rluble** [comment]
This issue is also solved by commit d91f8e1374f7ccdb68d92c206c84864cd09c02f6.
