### ISSUE TITLE
Refactor indent method to accept type and number of indents

### ISSUE THREAD

**Issue by DrPeroxide** [square/javapoet#622]
The current implementation of the indent method is questionable, accepting any old String and appending this to the beginning of every line with no validation done as to the validity of the indentation provided.

I recommend adding a method that sets the indentation type to either SPACE or TAB, along with another method accepting an integer to describe how many of these should be appended before each line.

**Comment by JakeWharton** [comment]
Would you ever expect multiple tabs? Also is this a problem in practice? We could add a check to ensure that it's filled with whitespace and that seems like it would cover any accidental value.
