### ISSUE TITLE
How can i convert Method type to ExecutableElement？

### ISSUE THREAD

**Issue by yuanhoujun** [square/javapoet#624]
![image](https://user-images.githubusercontent.com/7424397/36833332-fd028aaa-1d69-11e8-8e17-df86dafab5a1.png)

**Comment by tbroyer** [comment]
You can't, but overloads of `MethodSpec.overriding()` taking `java.lang.reflect.Method` should probably be added.

**Comment by yuanhoujun** [comment]
Yep, this will be much better

**Comment by jollytoad** [comment]
I'm currently investigating javapoet, and this too has confused me, where do we obtain an ExecutableElement in the first place? what is the use-case for this?

**Comment by tbroyer** [comment]
`ExecutableElement` is the kind of object you get when you're writing an annotation processor (such as Dagger, Butterknife, etc.): https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html

**Comment by NightlyNexus** [comment]
>overloads of MethodSpec.overriding() taking java.lang.reflect.Method should probably be added.

just tried this, and I don't know that there's a good way to do it without a lot of reflection help for contextually resolving types?

my attempt: https://github.com/square/javapoet/commit/a5aa72678bb11a9b475e3df88c5cc77ca7338542

**Comment by tbroyer** [comment]
I tried too yesterday and came up with something very similar. I had just left out the `overriding(Method,Type)` overload as, as you say, a lot of work is needed to resolve type variables.

**Comment by TjeuKayim** [comment]
[The unit-tests of kotlinpoet](https://github.com/square/kotlinpoet/blob/master/src/test/java/com/squareup/kotlinpoet/FunSpecTest.kt) make use of Google's "Compile Testing" library.

https://github.com/google/compile-testing

**Comment by vogma** [comment]
Is it currently possible to use the MethodSpec.overriding() Method like @yuanhoujun suggested? And if not how can i get an ExecutableElement without an additional library like the one in @TjeuKayim's answer?

Thanks
