### ISSUE TITLE
Support for custom formatters

### ISSUE THREAD

**Issue by uschi2000** [square/javapoet#633]
This is more a question than a bug or feature request: Is there any interest in supporting pluggable source code formatting as part of the `JavaFile#writeTo` code path? For instance, we use the following wrapper to format with google-java-format:

```
public final class Goethe {

    private static final Formatter JAVA_FORMATTER =
            new Formatter(JavaFormatterOptions.builder().style(JavaFormatterOptions.Style.AOSP).build());

    private Goethe() {}

    /** Formats the given Java file and emits it to the appropriate directory under {@code baseDir}. */
    public static Path formatAndEmit(JavaFile file, Path baseDir) {
        try {
            Path outputFile = getFilePath(file, baseDir);
            StringBuilder code = new StringBuilder();
            file.writeTo(code);

            CharSink sink = com.google.common.io.Files.asCharSink(outputFile.toFile(), StandardCharsets.UTF_8);
            JAVA_FORMATTER.formatSource(CharSource.wrap(code), sink);
            return outputFile;
        } catch (IOException | FormatterException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Returns the full path for the given Java file and Java base dir. In a nutshell, turns packages into directories,
     * e.g., {@code com.foo.bar.MyClass -> /<baseDir>/com/foo/bar/MyClass.java} and creates all directories.
     * Implementation taken from JavaPoet's {@link JavaFile#writeTo(File)}.
     */
    private static Path getFilePath(JavaFile file, Path baseDir) throws IOException {
        Preconditions.checkArgument(Files.notExists(baseDir) || Files.isDirectory(baseDir),
                "path %s exists but is not a directory.", baseDir);
        Path outputDirectory = baseDir;
        if (!file.packageName.isEmpty()) {
            for (String packageComponent : file.packageName.split("\\.")) {
                outputDirectory = outputDirectory.resolve(packageComponent);
            }
            Files.createDirectories(outputDirectory);
        }

        return outputDirectory.resolve(file.typeSpec.name + ".java");
    }
}
```

If there is interest, I'd be happy to discuss the design and contribute the PR.

**Comment by swankjesse** [comment]
I think your wrapper is the right approach. I don't think we'd get much from having a more sophisticated API here.

It's also not something I encourage. Adjusting whitespace in generated code takes real time & complexity for negligible benefit. You can get a lot with just the `$W` operator.

**Comment by uschi2000** [comment]
I'm fine with your decision, but would encourage you to consider the following points at some point in the future:
- Code gen time is typically async, once, and fast; the resulting code is long-lived and frequently read by humans for which good formatting and readability has real benefits.
- A pluggable no-op formatter would preserve today's zero overhead behavior
- Instead of investing development time on hand-crafting the formatting of the generated code with `$W` etc, I'd rather generate the syntax tree and have a computer do the formatting.

**Comment by JakeWharton** [comment]
One counterpoint for the first bullet is here: https://github.com/google/dagger/issues/368

**Comment by uschi2000** [comment]
Hence the second bullet point :)
