### ISSUE TITLE
Question: How to detect duplicate sub classes within annotated classes and dynamically assign them to interfaces

### ISSUE THREAD

**Issue by menacher** [square/javapoet#634]
I am using java poet to generate java client library sources for our REST api. We annotate our REST entity java classes with specific annotations. However, since there is an entity-per-version where most fields are actually just duplicated and only a couple of fields are added/modified. How is it possible to dynamically generate interfaces for the common fields, so that translators(to json) down the line, dont have to write specific translator per version?

E.g.
```java
@SpecialAnnotation(version="V1")
ConfigV1 {
    String a;
    static class SubClassV1 {
        String subA;
        int subB;
    }
}

@SpecialAnnotation(version="V2")
ConfigV2 {
    String a;
    String b;
    static class SubClassV2 {
        String subA;
        int subB;
    }
}
```
In the above code the only thing that actually changed was "b" got added. Everything else has remained the same. Is it possible while generating client code to have SubClassV1 and V2 extend Interface which has all the getters/setters so that translators/aggregators at client side needs to be written only once for the interface and not for each individual un-changing class?

**Comment by JakeWharton** [comment]
This shouldn't happen at the JavaPoet layer. You should perform this diffing at the model layer and then only emit any resulting properties.

**Comment by menacher** [comment]
Thought so! Thanks for confirming. Any idea about code/libraries that can do model layer diffing?

**Comment by swankjesse** [comment]
No specific advice. You might not even need to do diffing; just generate the Type spec for each entity.
