### ISSUE TITLE
Retain ClassName in TypeSpec

### ISSUE THREAD

**Issue by adam-mccormick** [square/javapoet#647]
Unless I'm completely missing it; is there a reason that the `ClassName` of a `TypeSpec` is not retained. It would be nice to be able to build a `TypeSpec` that I can later get the `ClassName` of to refer to. 

I think it would also make sense for `JavaFile.builder(TypeSpec)` to take the package name from the given `TypeSpec` instead of having to give it explicitly. I don't really understand the need to separate the package name from the `TypeSpec`...

**Comment by JakeWharton** [comment]
A type does not know which package it is in. The factory of a `TypeSpec` that takes a `ClassName` is a convenience to pull out the simple name.

**Comment by adam-mccormick** [comment]
Is there a reason it shouldn't know which package it's in? Maybe a better way to state what I would want it to have the `TypeSpec` retain it's fully qualified name.

**Comment by JakeWharton** [comment]
For the same reason a method does not know about its enclosing class. The package is a property of the file into which you place one or more types.

**Comment by adam-mccormick** [comment]
Ok, that makes sense.
