### ISSUE TITLE
Is it possible to generate a open parameter list?

### ISSUE THREAD

**Issue by olpf** [square/javapoet#648]
Hi,
I want to generate a method like this

`public String myMethod(final String... params)`

Is this possible?

Regards
Oli

**Comment by JakeWharton** [comment]
There is a `varargs()` method on the builder for that, yes.

https://github.com/square/javapoet/blob/3ddde8f3ccb5182ce5da7fcca21997efe96028a0/src/test/java/com/squareup/javapoet/TypeSpecTest.java#L1109-L1126
