### ISSUE TITLE
Make it possible to construct a `TypeName` directly from a string

### ISSUE THREAD

**Issue by zcourts** [square/javapoet#649]
I can't see any means of constructing a `TypeName` instance from a string.
All usages I've seen require a `Class` or `Type` object.

The use case I have is that the code generation we're doing, some of the types that we need to use a fields do not exist, they're themselves generated and all that's available is the name.

Since JavaPoet does everything else we want, I hacked it to get something going by using reflection to grab the currently private string constructor and creating instances via reflection...a hack I'd rather not have to keep for too long.

I'm asking for this feature not knowing why it's currently impossible to construct `TypeName` from a string so do share if there's a better way I should be doing this. Happy to send a PR with the minor change of making the constructor public if it'll be accepted.

**Comment by kenzierocks** [comment]
I think parsing full type names is out of scope for JavaPoet, but you can construct `ClassName` instances out of strings (`ClassName#get` and `ClassName#bestGuess`) and then construct your own `TypeName` instances out of that, using `ParameterizedTypeName#get` (or the equivalent for other types).

**Comment by zcourts** [comment]
Yes it is, that gets me what I want.
Thanks
