### ISSUE TITLE
Make column limit configurable

### ISSUE THREAD

**Issue by quijote** [square/javapoet#663]
Currently column limit is hardcoded to 100 characters in CodeWrite.java:
```this.out = new LineWrapper(out, indent, 100);```

Some projects use different column limits for their code. It would be great to be able to generate code that confirms to the common style used by a project.

**Comment by swankjesse** [comment]
We're actually deliberate on this. We follow Google's style guide here & think you should too. 99 columns is not enough for OverlyVerboseJavaClassNames and 101 is too many for my smart phone’s narrow screen. 100 is just right.

https://google.github.io/styleguide/javaguide.html#s4.4-column-limit
