### ISSUE TITLE
ParameterSpec miscellany

### ISSUE THREAD

**Issue by ronshapiro** [square/javapoet#665]
I noticed a few things today when looking at the `ParameterSpec` source:
  - `ParameterSpec.get(VariableElement)` doesn't check that the element kind is a parameter
  - `ParameterSpec.get(VariableElement)` doesn't copy annotations from the element
  - The only valid modifier on a parameter is `final`, but JavaPoet will accept any. This isn't inconsistent with the rest of the APIs, but I wonder if it's a good place to fail fast instead of generating code that will surely not compile. I noticed this when thinking that `ParameterSpec.getModifiers()` returns a `Set<Modifier>` - it is consistent with the other `*Spec` classes, but may make someone think twice about what types of modifiers might go there.

Happy to send PRs for any of the above. I presume the second is surely a bug; not sure if the first is Working As Intended or not.

**Comment by swankjesse** [comment]
Send PRs? The only thing I'd leave as-is is the `Set<Modifier>`. With recent acceleration of Oracle’s Java language changes who knows what’s coming. Consistency with the other *Spec classes helps us stay future-proof.
