### ISSUE TITLE
If a string variable contains "\n", it will create a new line in source code

### ISSUE THREAD

**Issue by tzutalin** [square/javapoet#680]
Hi,
I used the below snippet code to generate a string variable containing `\n` inside a string variable.
I expected the output should look like `{"hi", "\ntest"}`, but the result is like this.
```
{"hi", "\n"
    + " test"}
```
Snippet code I used
```
        final CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("{$S, $S}", "hi", "\n test");
        CodeBlock codeBlock = builder.build();
        System.out.println(codeBlock.toString());
```

Is any soluiton to this problem?

**Comment by tzutalin** [comment]
I found that JavaPoet supportted literal format already! 
In the case, I expect to output the code without escape.
`builder.add("{$L, $L}", "hi", "\n test");`

**Comment by swankjesse** [comment]
This is working as designed.
