### ISSUE TITLE
Add an API to add header comment (i.e. license header) to TypeSpec.Builder

### ISSUE THREAD

**Issue by simonetripodi** [square/javapoet#682]
Currently, `TypeSpec.Builder` supports javadoc only, it would be really nice to have a method to add a class header where adding a license header.

**Comment by JakeWharton** [comment]
I think you want `JavaFile.addFileComment` for that.

**Comment by simonetripodi** [comment]
AWESOME I just gave a try and, indeed, it is what I was looking for, thanks!
And please apologise for not having noticed it before opening the issue! :)

**Comment by ewoks** [comment]
@JakeWharton is there any flag to enforce `block comment `instead of `line comment`?
I am getting headers similar to:
```
// Copyright (c) 2019
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
// http://www.apache.org/licenses/LICENSE-2.0
```
instead of text surrounded with /** ... */
