### ISSUE TITLE
Utility function for spacing

### ISSUE THREAD

**Issue by falu2010-netflix** [square/javapoet#689]
Is there a utility function to add spacing while using .addStatement or .addCode API rather then adding manually? 

Sample Code:
 .addStatement("   logger.error($S, $L, $L)", logger, api.getParamName(), "e")
                .addStatement("     $T.getCounter($S, $T.singletonList(new $T($S, $S))).increment()",

**Comment by JakeWharton** [comment]
Why are you adding it? Most things do it automatically like beginControlFlow or a method body in general.
