### ISSUE TITLE
TypeSpec for interface should not require abstract

### ISSUE THREAD

**Issue by mnybon** [square/javapoet#696]
TypeSpec has a requirement for Methods on Interfaces to be declared Abstract, Default or Static.

From
https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/TypeSpec.java

    public Builder addMethod(MethodSpec methodSpec) {
      if (kind == Kind.INTERFACE) {
        requireExactlyOneOf(methodSpec.modifiers, Modifier.ABSTRACT, Modifier.STATIC,
            Modifier.DEFAULT);
    requireExactlyOneOf(methodSpec.modifiers, Modifier.PUBLIC, Modifier.PRIVATE);

This makes my life kind of hard, as I am trying to write a piece of code that generates both the Interface and Class at the same time. The only change from the Interface to the Class is the code block, so I am reusing the MethodSpec.Builder by defining the method with modifiers, then calling `interfaceBuilder.add(methodBuilder.build())` before adding the codeblock, setting the override annotation and calling `classBuilder.add(methodBuilder.build())` again.
The problem is that I am being stopped by the Abstract/Static/Default requirement. Once I set that on the MethodSpec.Builder there is no way to remove it, which means that I can now add it to the interface, but now the method is abstract, which means that I can't reuse it for the class builder.

Is it possible to remove that Abstract requirement for the Interface so I don't have to create the same method builder two times to create my interface/class combo.

**Comment by tbroyer** [comment]
Workaround:
```java
interfaceBuilder.add(methodBuilder.build().toBuilder().addModifiers(ABSTRACT).build());
```

See also #575, #650, and to some extent #557, #478, and #341.

**Comment by JakeWharton** [comment]
This cannot be removed or it would prevent creating private instance or static methods for Java 10 and newer.

**Comment by mnybon** [comment]
That workaround works but note that it is only viable before you add code to the method.
