### ISSUE TITLE
Consider MethodSpec toBuilder(String name) overload

### ISSUE THREAD

**Issue by bjakke** [square/javapoet#699]
(This is somewhat related to some other issues, but I see this as a much smaller scope, additionally this is just a "would be nice to have" feature, I can workaround this pretty easily)

If I call toBuilder() on a MethodSpec, the name of the method cannot be changed in the resulted Builder (I did not find any way at least, sorry if I missed. Based on the code it is final anyway at https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/MethodSpec.java). 

It would be nice if I could pass the name of the method to the builder as an overload toBuilder(String methodName). I'm aware that only additions are possible through the builder, however the name is a mandatory parameter (since you need it for MethodSpec.methodBuilder(name) always), so it cannot be changed. 

My use-case would be to generate a set of methods, with some being "XXXAsync", which are mostly identical (return type and final statement are different), but the name is different.

Might need some thinking for constructors, however in another usecase, one of my methods would be identical to a (partially constructed) constructor MethodSpec. Therefore it would be sort-of nice if I could transform a method MethodSpec to a constructor MethodSpec builder, and vice versa (the code seems to use `static final String CONSTRUCTOR = "<init>"; ` for the name, could it be possible to expose this constant as public?). And as extra mention, it would be nice to have a single method to construct MethodSpecs, and if passed that <init> it would be a constructor (e.g. let's say MethodSpec.rawBuilder or something).

**Comment by JakeWharton** [comment]
Seems like we just need a setter in the builder and to enforce the invariants there.

**Comment by bjakke** [comment]
That would solve the issue (both actually), however I feel I want to point out the following:

Having a setter in the `Builder` would mean 2 ways to set the name (the setter + parameter to the `MethodSpec.methodBuilder`), which sounds redundant (I'm assuming everything must be backwards-compatible). And now that I looked it closer also it might affect badly for the `MethodSpec.overriding` way of making the `Builder`, you probably do not want the option to change the name there (easily, you could do `.build().toBuilder(differentName)` still if needed). Having the name as overload in the `toBuilder` would avoid that (and avoids changes to any field modifiers etc, i.e. would be just addition of one method overload).

**Comment by bjakke** [comment]
Hmm, makes sense.
