### ISSUE TITLE
Add a feature

### ISSUE THREAD

**Issue by tianrandailove** [square/javapoet#704]
it will be better that can custome the classLoader

**Comment by Egorand** [comment]
Sorry, it's not clear what you mean. Could you please explain it in more detail?

**Comment by tianrandailove** [comment]
I'm making a intellij platform plugin that need load class from the user's project source file(compiled file),so I hope that ClassName can loadClass  from the defined URL(directory) .

**Comment by JakeWharton** [comment]
JavaPoet doesn't load classes. If you want to define a `ClassName` from a `URL` then you can parse it into the package and name parts and create one using `ClassName.get`.
