### ISSUE TITLE
Simplify usage

### ISSUE THREAD

**Issue by YunaBraska** [square/javapoet#708]
Javapoet is really great, but i can't see the poet part.
It takes much time tu understand javapoet for a single use case.
It would be really nice if there is a way to make javapoet consistent and human readable.
For example, you have the FieldSpec for the TypeSpec but not for MethodSpec. You always have to rethink how to implement when you are using different Types.

Examples:
ClassBuilder.addVariable(<String Name><FieldSpec/Type><Initializer><Modifiers>);
MethodBuilder.addVariable(<String Name><FieldSpec/Type><Initializer><Modifiers>);

VariableBuilder(<String Name><Type><Modifiers>).Initializer(...);
TypeBuilder(Class)
TypeBuilder(CodeBlock)
TypeBuilder.buildGenericOf(Class) //Class<?>
TypeBuilder.buildGenericOf(Class, Class) //<Class <extends Class>>

**Comment by tbroyer** [comment]
In Java, classes have fields and methods (and nested classes and interfaces):
* https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html
* https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html

and methods have parameters:
* https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4
* https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Method.html

JavaPoet is closer to the JLS than to `javax.lang.model.element` (which does represent fields and parameters as a single [`VariableElement`](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/element/VariableElement.html)), but more importantly, everything that I know of in Java land (including annotation [`@Target`s](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/ElementType.html)) talks about fields and parameters (and type parameters) in a **consistent way,** even `javax.lang.model` (see e.g. [`ExecutableType`](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/type/ExecutableType.html) and [`ExecutableElement`](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/element/ExecutableElement.html)).

Fwiw, fields can have a visibility (`public`, `protected` or `private`) and be `volatile` or `transient`, whereas parameters can only be `final`, so you couldn't use the same *variable* instance interchangeably anyway.
