### ISSUE TITLE
JavaFile.writeTo(Filer) can cause non UTF-8 output files

### ISSUE THREAD

**Issue by andreas-eberle** [square/javapoet#709]
When you use the JavaFile.writeTo(Filer) method to write a file, the encoding is not ensured to be UTF-8. In fact, the encoding seems to be system dependent. See https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/JavaFile.java#L115

This causes problems when building the Tensorflow Java API, since the generated Ops.java file contains non-ascii characters but is encoded as ascii.

**Comment by JakeWharton** [comment]
There's some prior art in #577 for this discussion.

**Comment by andreas-eberle** [comment]
Thanks. Unfortunately, I have no idea how to provide the encoding through bazel to the annotation processor. However, simply removing the non-ascii characters from the template did work as well.

I see the point of not breaking the API but also see the problem of the now unconsistent API since methods with the same name but different arguments behave very differently, which isn't usually the idea when you overload a method.
