### ISSUE TITLE
[Help wanted] How to generate chained method calls with assignment

### ISSUE THREAD

**Issue by kartikpatodi** [square/javapoet#710]
How can we generate something like
`final List<String> strings = ListUtils.getData().getList("strings");`
Is there a support for generating such chainned calls?

**Comment by Egorand** [comment]
No, JavaPoet doesn't model things such as variable initializers or method bodies. You can use `$T` for `List<String>` and `ListUtils` so that these types can be imported, and `$S` for `"strings"` to get it auto-escaped, but everything else is just going to be a string.

**Comment by tbroyer** [comment]
So, to be accurate, no there's no specific support for that, because the API models code blocks as strings (with placeholders); something like:

```java
CodeBlock.of("final $T strings = $T.getData().getList($S);", listOfString, listUtils, "strings");
```
(where `listOfString` and `listUtils` will be appropriate `TypeName`s or `java.lang.Class`)

or for a `FieldSpec` initializer:
```java
  .initializer("$T.getData().getList($S)", listUtils, "strings")
```

**Comment by kartikpatodi** [comment]
@Egorand @tbroyer  Is there any specific reason for not doing so?

**Comment by JakeWharton** [comment]
The complexity would be orders of magnitude larger than modeling only the structure of types. It also means we don't need to bother with tracking the majority of the evolution of the language since new features often reside in code statements and not in the structure of types.
