### ISSUE TITLE
About imcremental Genertation of Java files.

### ISSUE THREAD

**Issue by splm** [square/javapoet#715]
Sometimes The generated java files don't need to recreate every time.
In my opinion,firstly I build a tag file to mark which file has changed  ,and then when the processor is running,the changed files will be overwritten rather than all files are recreated.
But in fact,if i don't call JavaFile.writeTo method,the compiler gonna failed.

**Comment by splm** [comment]
Here is the source file:
https://github.com/splm/WeBase/blob/master/weannotation-processor/src/main/java/me/splm/app/inject/processor/component/proxy/AbsGenerateJavaAction.java

The performAction method is entry point.

**Comment by tbroyer** [comment]
This is not how annotation processing works (btw, you're using Gradle, which supports incremental annotation processing; have a look at how you can take advantage of it), and is out of scope of JavaPoet.
