### ISSUE TITLE
Unable to be compatible with high version of gradle !

### ISSUE THREAD

**Issue by EspoirX** [square/javapoet#726]
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
classpath 'com.android.tools.build:gradle:3.4.1'

Such a configuration cannot generate a file in build/generated/source/apt/debug

**Comment by Egorand** [comment]
It'd be helpful to have a sample project that reproduces the issue. My feeling is that JavaPoet isn't the culprit here.

**Comment by EspoirX** [comment]
You can create a simple APT example to reproduce，like this:
```
    @AutoService(Processor.class)
    public class MyProcessor extends AbstractProcessor {
        
        private Filer mFiler;
     
        @Override
        public synchronized void init(ProcessingEnvironment processingEnvironment) {
            super.init(processingEnvironment);
            mFiler = processingEnv.getFiler();
        }

        @Override
        public boolean process(Set<? extends TypeElement> set, RoundEnvironment roundEnvironment) {
            TypeSpec finderClass = TypeSpec.classBuilder("MyTestClass")
                    .addModifiers(Modifier.PUBLIC)
                    .build();
            JavaFile javaFile = JavaFile.builder("com.example.demo", finderClass).build();
            try {
                javaFile.writeTo(mFiler);
            } catch (IOException e) {
                e.printStackTrace();
            }
            return true;
        }

        @Override
        public Set<String> getSupportedAnnotationTypes() {
            Set<String> types = new LinkedHashSet<>();
            types.add(Override.class.getCanonicalName());
            return types;
        }
    }
```

as you said，I am not sure the problem is in JavaPoet or google#auto-service，But after I lowered the gradle version, the problem was solved. So I hope that you can follow up to make sure it is not a JavaPoet issue.

**Comment by tbroyer** [comment]
How are your dependencies configured? And which older version of Gradle is working?
In 5.0 for example, Gradle stopped using processors from the compile classpath, you have to declare your processor dependencies in the `annotationProcessor` configuration.

**Comment by EspoirX** [comment]
yes，My configuration is correct，like this，
annotationProcessor project(':compiler')

**Comment by JakeWharton** [comment]
Please provide a full sample project in the form of a zip or GitHub repo that reproduces the problem.

**Comment by EspoirX** [comment]
demo : https://github.com/EspoirX/IssuesDemo

thanks!

**Comment by tbroyer** [comment]
Your AutoService dependency should be in both `api` (or `compileOnly` as the annotation has source retention) and `annotationProcessor`.
I haven't tried the project but that alone would break it with Gradle 5.0, as explained earlier.

**Comment by LiChangXing** [comment]
I have the same problem

**Comment by LiChangXing** [comment]
My gradle build is gradle-5.1.1-all.zip
Gradle version is 3.4.1
The problem I encountered was also a class generation failure. Do I have to downgrade to use it @ @tbroyer

**Comment by EspoirX** [comment]
you should downgrade to use it @LiChangXing

**Comment by Shadowself** [comment]
So Have you solved it?
