### ISSUE TITLE
How to add parameter Activity ?

### ISSUE THREAD

**Issue by BayMax-Yi** [square/javapoet#729]
I want to generate code like 

public void inject(MainActivity activity){
     ......
}

and I add code in AbstractProcesser.process  in javaLibrary  like this

 public boolean process(Set<? extends TypeElement> set, RoundEnvironment roundEnvironment) {
     
             .......
               MethodSpec methodSpec = MethodSpec.methodBuilder("inject")
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(Class.forName("com.example.MainActivity"), "activity")
                    .returns(void.class)
                    //.addStatement()
                    .build();

        return true;
    }

than I got the exception "java.lang.ClassNotFoundException".

How should I do ? Thanks you !

**Comment by tbroyer** [comment]
`Class.forName()` implies that the class exists already (can be loaded and used, possibly instantiated, etc.)

You want or `ClassName.bestGuess("com.example.MainActivity")` or, better, `ClassName.get("com.example", "MainActivity")` (though ideally you should probably either already have a `ClassName` instance of that, or possibly a `TypeElement`)
