### ISSUE TITLE
Static imports

### ISSUE THREAD

**Issue by JakeWharton** [square/javapoet#73]
```java
public JavaWriter addStaticImport(Class<?> cls, String methodName) { }
```
```java
private final SetMultimap<ClassName, String> staticImports = LinkedHashMultimap.create();
```
Should be a bit more straightforward to emit since the logic for actually choosing which imports only applies to the current and parent contexts in the same file. A much smaller scope than regular import resolution.

**Comment by hascode** [comment]
As I am writing a code generator for a framework that uses/offers a DSL - using a lot of static imports - I would really be delighted to see this feature being added to javapoet!

Keep up the good work! :+1:

**Comment by swankjesse** [comment]
Definitely want this for Wire also.

**Comment by swankjesse** [comment]
One tricky problem is that we'll need to detect the referenced method import in the code. We'd need to teach `CodeBlock` to look beyond its normal scope at things like `$T.identifier`, inspecting the string to find the identifier. If it does, it would omit `$T` and the dot that follows.

It gets very difficult if we favor in the possibility of name collisions. For example, if the current type declares a method that collides, or even _extends_ a class that has a method that collides, the static import is unsafe.

**Comment by sormuras** [comment]
What do you like more?
 * a) Automatically inserted import static statements for all static referable members?
```java
JavaFile.builder(...).autoStaticImports(true)...
```
 * b) Explicitly named static referable members? See [addStaticImports](https://github.com/sormuras/javapoet/blob/ref/src/test/java/com/squareup/javapoet/MemberRefTest.java#L154)
```java
JavaFile.builder(...).addStaticImports(MemberRef.get(System.class.getMethod("gc")), ...)...
```

**Comment by hascode** [comment]
@sormuras b) is my favourite, too :+1:

**Comment by sormuras** [comment]
a) is #390
b) is #389
c) not implemented, yet

**Comment by sormuras** [comment]
`implementes Closeable` :tada:
