### ISSUE TITLE
Is there possible to write to the same file with the method named writeTo of JavaFiler.

### ISSUE THREAD

**Issue by zqwxmao** [square/javapoet#730]
I tried to write to the same file with JavaFiler, but the file was overwritten . 
My need is to write to the same file. Just my suggestion. ummm xixi

**Comment by JakeWharton** [comment]
No. JavaPoet is for creating new types, not modifying existing ones. For that use case, try Spoon: http://spoon.gforge.inria.fr/

**Comment by zqwxmao** [comment]
Thank you very much for your help.Your are
so efficient
