### ISSUE TITLE
Should javadocs include a trailing newline if one isn't present?

### ISSUE THREAD

**Issue by ZacSweers** [square/javapoet#731]
Right now, if I add a one line doc comment, I get something like this

```java
/**
 * This type + annotation exists for sharing information to the Crumb annotation processor and should not be considered public API. */
final class Lib1ProducerCrumbIndex {
  private Lib1ProducerCrumbIndex() {
  }
}
```

I think it should just always add a trailing newline for style reasons, but want to check before opening a PR if there was a reason for this. Kotlinpoet appears to always add the trailing newline for the equivalent kdoc

```java
/**
 * This type + annotation exists for sharing information to the Crumb annotation processor and should not be considered public API.
 */
final class Lib1ProducerCrumbIndex {
  private Lib1ProducerCrumbIndex() {
  }
}
```

**Comment by JakeWharton** [comment]
Yes. And method bodies. Everything.

**Comment by ZacSweers** [comment]
I'll make a PR

**Comment by JakeWharton** [comment]
I vaguely remember it being shockingly non-trivial. Please also do
KotlinPoet.

**Comment by ShaishavGandhi** [comment]
I know that KotlinPoet has it for KDoc but probably not for method bodies and such.
