### ISSUE TITLE
Construct WildcardTypeName

### ISSUE THREAD

**Issue by amandeepg** [square/javapoet#738]
I was able to construct instances of all other types in JavaPoet, but `WildcardTypeName` is proving more difficult. I have a `List<TypeName>` for the upper and lower bounds and want to use that to construct a `WildcardTypeName`, but the constructor for that is private.

There are public static methods but they only take one or the other of upper or lower bounds. Am I missing how to construct a `WildcardTypeName`?

**Comment by tbroyer** [comment]
What Java type declaration do you want to create?

**Comment by amandeepg** [comment]
A bounded wildcard: https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#d5e3166

**Comment by tbroyer** [comment]
…which can be either `? extends LowerBound` or `? super UpperBound`, but cannot have both an upper and lower bounds.

**Comment by amandeepg** [comment]
Thanks! I changed my model to be similarly restricted to only be either a lower or upper bound.
