### ISSUE TITLE
Add array support to AnnotationSpec

### ISSUE THREAD

**Issue by jherrera123** [square/javapoet#745]
I'm trying to replicate array values in Annotations like JAXB supports (see propOrder):

```
@XmlType(name = "", propOrder = {
    "field1",
    "field2
})
```

I tried the following options but both are clunky:

```
AnnotationSpec.addMember(String name, String format, Object... args)
AnnotationSpec.addMember(String name, CodeBlock codeBlock)
```

In option one, I have to convert my ArrayList to String using String.join(), in option two, I have to use CodeBlocks including adding braces, which seems inconvenient. I think it would be nicer to support arrays and add a getter:

```
addMember(String name, String[] values)

public String[] getMemberArray(String name, String[] values)
```

**Comment by tbroyer** [comment]
According to https://github.com/square/javapoet/blob/e9460b84fc41464c2aa2ef85c84dd1ac87ae1692/src/test/java/com/squareup/javapoet/AnnotationSpecTest.java#L204 you can call `addMember` repeatedly for each value of the array.
