### ISSUE TITLE
Add Named / CodeBlock overload to control flow

### ISSUE THREAD

**Issue by ennerf** [square/javapoet#751]
I really like the `CodeBlock::addNamed` / `MethodSpec.Builder::addNamedCode` features as they make the generating code a lot more readable.

Unfortunately, when trying to work exclusively with named code, it becomes somewhat annoying to deal with the statement and control flow characters. It'd be great if you could add some convenience methods to `MethodSpec.Builder`

* `addNamedStatement`
* `beginNamedControlFlow`
* `nextNamedControlFlow`

Additionally, it'd be great if `beginControlFlow` and `nextControlFlow` could have overloads for accepting a `CodeBlock` parameter like the `addStatement` method. That would make it easier to work with helper methods, e.g.,

`method.beginControlFlow(CodeBlock.builder().addNamed("if ($field:N != null)", map).build());`

**Comment by Egorand** [comment]
SGTM! Would you be interested in submitting a PR?

Is there value in implementing both of your suggestions? I.e., if you have a `beginControlFlow(CodeBlock)` overload, would you need a `beginNamedControlFlow()` method?

**Comment by ennerf** [comment]
I think the CodeBlock overload would work well enough by itself. PR is filed.
