### ISSUE TITLE
TypeSpec.Builder#superclass doesn't import superclass

### ISSUE THREAD

**Issue by slava110** [square/javapoet#754]
I'm using code like
```java
ClassName PARENT = ClassName.get("com.testing", "ParentClass")
TypeSpec.Builder cmdBuilder = TypeSpec.classBuilder("NewClass")
                .superclass(PARENT)
                .addModifiers(Modifier.PUBLIC);
```
And ParentClass isn't imported

**Comment by JakeWharton** [comment]
Are you generating in the `com.testing` package? Because in that case, no import is required.

**Comment by slava110** [comment]
Sorry, there's something else wrong, not JavaPoet. Annotation processor just doesn't see that package for some reason. Idk what's causing it but probably it's not your fault
