### ISSUE TITLE
Add support for raw (opaque String) parameter list

### ISSUE THREAD

**Issue by vlsi** [square/javapoet#760]
Hi,

`MethodSpec.Builder#addParameter(com.squareup.javapoet.ParameterSpec)` is nice when parameter types are known.

However, I have a use case when parameters are not really known.

In other words, I want to create a method, and I want to use a simple string for arguments.

For instance:

```java
MethodSpec.methodBuilder(name)
    .addParameters("int x, int y, List z")
    ....
```

---

The use case is code generation in https://github.com/javacc/javacc/issues/140
For historical reasons, JavaCC does not really parse user-provided argument types.

For instance, SQL grammar contains the following:

```
// Parse sql type name that allows precision and scale specifications.
SqlTypeNameSpec SqlTypeName3(Span s) : <-- HERE. result type and formal parameters are not parsed to JavaCC model :(
{
    final SqlTypeName sqlTypeName;
    int precision = -1;
    int scale = -1;
}
{
    (
        (<DECIMAL> | <DEC> | <NUMERIC>) { sqlTypeName = SqlTypeName.DECIMAL; }
    |
        <ANY> { sqlTypeName = SqlTypeName.ANY; }
    )
    ...
```

In practice, JavaCC's code generator does not care much of the return type and argument type.

It turns out JavaPoet allows to use raw (opaque) string for return type: `ClassName.get("", "List<any type>")`.
However, there's no way to declare a method without knowing the structure of its parameters :(

**Comment by vlsi** [comment]
What do you think of the following?

```java
    public final CodeBlock opaqueParameters;

    public MethodSpec.Builder addOpaqueParameters(CodeBlock block) {
      this.opaqueParameters.add(block);
      return this;
    }
```

**Comment by JakeWharton** [comment]
I'm opposed to such an API because it means we need to support it for return types, field types, and then many other places we support types. Additionally, you still need to process the opaque type to emit imports correctly in which case you could just build a proper TypeName. How do you handle imports with these?

**Comment by vlsi** [comment]
>How do you handle imports with these?

Just like with `CodeBlock#addCode(String, ...)`.
The opaque data is either not using imports, or it uses fully qualified references, or it assumes the classes are imported.

Note: JavaCC uses declare imports manually.
So I don't really mind editing the output with substring.

Full type grammar is non-trivial (there are annotations, comments, etc), and I don't really need that for my use case. JavaCC does not need to process/analyze arguments either.
I just want to generate a method with user-provided arguments.

The contents of the method would be a mix of user-provided and machine-generated code, that is why I want to use JavaPoet for that.

> it means we need to support it for return types, field types, and then many other places we support types

types != parameters

There's a workaround for types: `ClassName.get("", "whatever I want")` returns `TypeName` that can be used as an opaque type.

For instance,  `ClassName.get("", "List<String>")` just works for me.

**Comment by vlsi** [comment]
> many other places

It looks like the impacted cases are the ones that have lists of items.

Two more places are: `superinterfaces`, and `method exceptions`.

Note: for `for` and `catch` the problem does not exist because JavaPoet does not enforce the layout. In other words, controlFlow is opaque-first (which might be good or bad, but it is what it is)

**Comment by Egorand** [comment]
You should be able to solve this by post-processing generated code, e.g. generate a placeholder `ParameterSpec` that would be easy to locate and replace it with the opaque string.

**Comment by vlsi** [comment]
Oh, if you mean that as a workaround, then thanks. It might be helpful indeed.
If you mean that as the only possible solution, then it is sad.

For the time being (e.g. while the issue is under consideration), I've copy-pasted JavaPoet to my source tree and added `addOpaqueParameters` method.

**Comment by vlsi** [comment]
One more `opaque` case: `TypeSpec` body. In other words, if half of the `TypeSpec` exists as a string, then it should be possible to append it.

**Comment by JakeWharton** [comment]
That doesn't really fit into the model that JavaPoet wants to create though

**Comment by Egorand** [comment]
Agree, I wouldn't want this kind of API to be a part of core JavaPoet. Closing.
