### ISSUE TITLE
$ makes uses from Kotlin weird

### ISSUE THREAD

**Issue by vlsi** [square/javapoet#761]
`$` in Kotlin strings has its powers, and unfortunately, it can't be disabled.
I think it is a flaw in Kotlin, however, the solution at the Kotlin side does not seem to be coming soon :(

Current JavaPoet syntax requires to escape all the `$` characters:

```kotlin
addCode("\$[\$L=generateRegexp()\$]", regex.lhsTokens.asString())
```

Do you think there might be an option to use `%` as an extra (or instead) of `$` for code blocks?

I understand a mere addition of `%` as a special character might break the existing users.
However, I think it still might be possible to add an extra API like `*.Builder#setSpecialChar(char)`.
An implementation could be like `convert %-like to $-like if non-standard character is set`.

As far as I understand, it is hard to do that without modification of JavaPoet since the classes are final. For instance, I expect that `MethodSpec.Builder#setSpecialChar` would propagate the call to its `CodeBlock.Builder javadoc`, `CodeBlock.Builder code`, `CodeBlock defaultValue`, and so on.

WDYT?

**Comment by sormuras** [comment]
Are you generating Java code from Kotlin?

Just in case, for generating Kotlin code, there's https://github.com/square/kotlinpoet

**Comment by vlsi** [comment]
@sormuras , thanks for pointing that out, however, you are reading it right: I'm using JavaPoet from Kotlin to generate Java code (see https://github.com/square/javapoet/issues/760, https://github.com/javacc/javacc/issues/140 )

The need for generating Java code is that the result of my generator needs to incorporate **opaque** Java code that is written by humans.

Here's an [example of my input](https://github.com/apache/calcite/blob/0196bb67a5255b7b0f9e297c74742c4d7203403d/core/src/main/codegen/templates/Parser.jj#L773-L795)

The code in curly braces is Java, and I can't "automatically transpile it to Kotlin".

If you are curious, I'm using https://github.com/agrosner/KPoet/ which brings a slightly more readable DSL for JavaPoet.

**Comment by JakeWharton** [comment]
I've found the easiest way to handle this is to declare

```kotlin
const val L = "\$L"
```
which lets you use `$L` and not worry about escaping each time.

In hindsight we would probably prefer having used percent as we did with KotlinPoet. I don't think an option is a good idea, though.

**Comment by vlsi** [comment]
> I've found the easiest way to handle this is to declare

It does not work for `$[` and `$>` :(

**Comment by Egorand** [comment]
Silently supporting `%` alongside `$` might be a way to go, are there any cases where this would break? I'm not in favor of introducing `setSpecialChar()` API either.

**Comment by JakeWharton** [comment]
Anyone emitting percent in a `CodeBlock` would break
```java
var hello = CodeBlock.of("$T.format(\"%s %s\", $S, $S)", String.class, "hello", "world");
```

**Comment by vlsi** [comment]
> I'm not in favor of introducing setSpecialChar() API either.

Can you please clarify what's wrong with that API?

> Anyone emitting percent in a CodeBlock would break

That is why I thought it is worth allowing to override the char:

```kotlin
var hello = CodeBlock.of("")
    .setSpecialChar('#')
    .add("#T.format(\"%s %s\", #S, #S)", String.class, "hello", "world");
```

**Comment by vlsi** [comment]
Ok. So far the only impacted use case for Kotlin is named template arguments.

What do you think of adding a note to readme like the following?

> If you use JavaPoet with Kotlin, you might want to create constants like `const val L = "\$L"; const val N = "\$N"; ...` so JavaPoet's string formatting works as expected.

---

I discovered yet another approach.
Note: I know Kotlin DSL is out of JavaPoet's scope, however, below might be interesting for those who use Kotlin+JavaPoet.

```kotlin
class StringTemplate {
    val args = mutableListOf<Any?>()

    private fun arg(mask: String, v: Any?) = args.run {
        add(v)
        "$$size$mask"
    }

    val TypeName.T: String get() = arg("T", this)
    val FieldSpec.T: String get() = arg("T", this.type)
    val MethodSpec.T: String get() = arg("T", this.returnType)

    val FieldSpec.N: String get() = arg("N", this)
    val MethodSpec.N: String get() = arg("N", this)
    val TypeSpec.N: String get() = arg("N", this)

    val String.N: String get() = arg("N", this)

    val Any?.L: String get() = arg("L", this)
    val Any?.S: String get() = arg("S", this)
}

fun cb(action: StringTemplate.() -> String): CodeBlock {
    val t = StringTemplate()
    val format = t.action()
    return CodeBlock.builder()
        .add(format, *t.args.toTypedArray())
        .build()
}
```

It enables to have templates that are easier to use than the ones with positional arguments.

For instance:

```kotlin
val hello = """Hello, "world", \n test"""
val j = FieldSpec.builder(Int::class.typeName, "j").build()

val codeBlock = cb { "System.out.println(${hello.S} + ${j.N})" }

println(codeBlock.toString())
```

==>

```
System.out.println("Hello, \"world\", \\n test" + j)
```

---

Here's one of my use cases.

```kotlin
// Default
beginControlFlow(
    "for(int $1N = $2L + $3N.nextInt($4L)/$5N; $1N > 0; $1N--)",
    jj_cnt, min, jj_random, max - min + 1, depthVars[this]
)

// StringTemplate
beginControlFlow(cb {
    val depthVar = depthVars[this@phase1ExpansionGenLoop]!!.N
    "for(int ${jj_cnt.N} = ${min.L} + ${jj_random.N}.nextInt(${max - min + 1})/$depthVar;" +
            " ${jj_cnt.N} > 0; ${jj_cnt.N}--)"
})
```

**Comment by Egorand** [comment]
Thanks! We're not planning to add any API to make JavaPoet more Kotlin-friendly, however I'd be open to adding a note to README. Wanna submit a PR?
