### ISSUE TITLE
Interface classes should not be required to be public

### ISSUE THREAD

**Issue by liach** [square/javapoet#767]
According to 
https://github.com/square/javapoet/blob/44622704248975ca398b90b4385005fdddeb35f9/src/main/java/com/squareup/javapoet/TypeSpec.java#L378
interfaces are enforced to be public.
However, this is not the case in java; package-private interfaces can be declared, such as [NetworkConnections in guava](https://github.com/google/guava/blob/31999ae6f56e71c341333afde90fcf66c13ce657/guava/src/com/google/common/graph/NetworkConnections.java#L30).

I wonder if there is a way to generate package-private interfaces, as that would greatly benefit my usage of javapoet.

Related to #532.

**Comment by octylFractal** [comment]
At least for top-level interfaces, this is already fine:
```java
var spec = TypeSpec.interfaceBuilder("Test")
        .build();
var writer = JavaFile.builder("test", spec)
        .build();
var cap = new StringBuilder();
writer.writeTo(cap);
System.err.println(cap.toString());
```
will generate
```java
package test;

interface Test {
}
```

**Comment by octylFractal** [comment]
And for nested interfaces, this is also already possible:
```java
var spec = TypeSpec.classBuilder("Outer")
        .addType(TypeSpec.interfaceBuilder("Inner")
                .build())
        .build();
var writer = JavaFile.builder("test", spec)
        .build();
var cap = new StringBuilder();
writer.writeTo(cap);
System.err.println(cap.toString());
```
will generate
```java
package test;

class Outer {
  interface Inner {
  }
}
```

**Comment by liach** [comment]
Hmm, must've been that I've used it incorrectly before somehow. Now my generated nested interfaces have proper visibilities (i.e. can be either public or package-private). Thanks!
