### ISSUE TITLE
Imports sometimes incorrect when inheriting nested type of same name

### ISSUE THREAD

**Issue by eamonnmcmanus** [square/javapoet#77]
If you are generating a subclass of a class like this...

``` java
// Parent.java
class Parent {
  static class Optional {}
}

// Generated Child.java
class Child extends Parent {
  java.util.Optional<String> optionalString() {...}
}
```

...then it is not correct to import java.util.Optional and abbreviate to "Optional<String> optionalString()", because the inherited nested Optional takes precedence over the import statement. Since JavaWriter typically doesn't know anything about Parent in this case, there should be some way of telling it to fully-qualify a type even if it would otherwise be inclined to import it.

This is an actual case that occurs with AutoValue in code at Google. (AutoValue doesn't use JavaWriter and can't as long as this bug remains.)

**Comment by adriancole** [comment]
In the dagger variant of JavaWriter, there's a concept of an originating element, which holds context about a generated type's parent.

That said, there was a bug in the dagger implementation, as this context was ignored for enclosed types. Thanks to @JakeWharton for pointing out this issue is very similar.

Anyway, here's the fix to dagger's JavaWriter and tests to go along with it.
https://github.com/google/dagger/pull/99

**Comment by JakeWharton** [comment]
We have originating element as well but at a much more granular level.
While that may be the fix for Dagger, you cannot assume anything about the
relationship of the originating element to the generated type since it's a
completely separate domain.

**Comment by adriancole** [comment]
I see what you mean: Originating Element is not the right concept to stick
to, even if it happened to have the type data I needed.
http://docs.oracle.com/javase/6/docs/api/javax/annotation/processing/Filer.html

Guess I know what I'm also doing tomorrow :P

**Comment by JakeWharton** [comment]
This needs some thought, but I think we have two choices:

 * A concept similar to the explicit imports where you can inform the `TypeWriter` of additional type structure. In this example you would iterate the type hierarchy of the element used to specify the superclass to inform nested types.
 * Make `ClassName` aware of nested types. I don't know how feasible this is, I'm just shooting from the hip here. This way when you create the `ClassName` from the `TypeMirror` you'd get all nested types as well.

I haven't thought about either of these at all. Just spitballing.

**Comment by swankjesse** [comment]
Right now we also explicitly import from `java.lang` because we don't know if the local package overrides those imports. Which means that 99% of the time, we're generating unnecessary imports.

I like the idea of using originating elements to detect the names of the classes in the same package. Detecting inheritance will be much more difficult; particularly because we make no requirement that the subclass is generated after the superclass.

**Comment by swankjesse** [comment]
Punting to 3.1 because it's difficult to do.

**Comment by ronshapiro** [comment]
I just ran into this issue in my JavaWriter -> JavaPoet migration for Dagger 2. @adriancole had a proposal for Dagger's JavaWriter in https://github.com/google/dagger/pull/99, would that be workable here?

**Comment by ronshapiro** [comment]
I'm running into this again with Dagger's experimental ahead-of-time subcomponents mode. Nothing particularly new, just different codegen tickling this bug again. 

The fix in many cases is simple, but it's unfortunate that we can't provide a better error to users besides generating code that doesn't compile.

**Comment by eamonnmcmanus** [comment]
One possibility would be to add a method to JavaFile that specifies simple names that should always be fully-qualified. They would never be imported and, in the case of `java.lang`, they would never be considered implicitly imported. So if you wrote `javaFileBuilder.alwaysQualify("Optional")` then every reference to `java.util.Optional` would be spelled as `java.util.Optional` even if JavaPoet is unaware of any other `Optional` that might be around. Likewise `javaFileBuilder.skipJavaLangImports(true).alwaysQualify("Thread")` would cause references to `java.lang.Thread` to be spelled as `java.lang.Thread` even though other `java.lang` references are unqualified.

Callers would then at least have the option of scanning the supertypes of a generated class to see what nested types there are, and adding those to the `alwaysQualify` list. That would fix the issue I outlined in the issue description. We could also have a convenience method that does exactly this, say `avoidClashesWIthNestedClasses(TypeElement)`.

**Comment by ZacSweers** [comment]
@eamonnmcmanus how would nested types such as `java.util.Map.Entry` work in that case?

**Comment by eamonnmcmanus** [comment]
The answer depends on what JavaPoet does today with nested classes. Does it import `java.util.Map.Entry` and then write `Entry` in the generated code? Or does it import `java.util.Map` and write `Map.Entry` in the code? The way to cause it to write the full `java.util.Map.Entry` would be `alwaysQualify("Entry")` in the first case and `alwaysQualify("Map")` in the second.

**Comment by ZacSweers** [comment]
I've opened a PR with the proposed implementation above in #734
