### ISSUE TITLE
Explicit receiver parameters

### ISSUE THREAD

**Issue by jasonobrien** [square/javapoet#787]
Explicit receiver parameters (annotated `this` parameters for instance methods and non-static inner class constructors) do not seem to be supported in `MethodSpec`.

```java
class SomeClass
{
  public void SomeMethod(@SomeAnnotation SomeClass this, int param) {}
}
```

https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.1

The simplest way to implement this is probably allowing `this` for parameter names in `MethodSpec.Builder#addParameter(ParameterSpec, String)`, which is currently only checked against `javax.lang.model.SourceVersion#isName(CharSequence)`.

Alternatively:

- `MethodSpec.Builder#receives(TypeName)` - order no longer matters.
- `MethodSpec.Builder#addReceiverAnnotation(AnnotationSpec)` - type is implicitly set (though maybe less resilient to future Java changes).

**Comment by JakeWharton** [comment]
I think I prefer the simplicity of special-casing "this" to be allowed.

**Comment by ronshapiro** [comment]
Just how common is this? because the code is generated, is there no way to sidestep this need?

**Comment by jasonobrien** [comment]
Need is a strong word - folks managed without them prior to Java 8, but you could say essentially the same thing for annotations in general.

Receiver parameters seem mostly used for static analysis tools (e.g. [CheckerFramework](https://checkerframework.org/api/org/checkerframework/checker/initialization/qual/UnderInitialization.html)). Suppressing the checks is probably the easiest workaround, in the generated classes and the non-generated classes that consume them.

I'm not sure how common they are, though.
