### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.google.guava:guava:jar

### ISSUE THREAD

**Issue by Bing-ok** [square/javapoet#797]
Hi, there are multiple versions of <b><i>com.google.guava:guava</i></b> in <b><i>javapoet-1.13.0</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>com.google.guava:guava:23.4-android</i></b> can be loaded, <b><i>com.google.guava:guava:18.0</i></b> and <b><i>com.google.guava:guava:23.5-jre</i></b> will be shadowed.

As <b><i>com.google.guava:guava:23.5-jre</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. com.google.common.collect.Streams: java.util.stream.Stream stream(java.lang.Iterable)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;com.squareup.javapoet.CodeWriter: void emitTypeVariables(java.util.List)&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.google.common.collect.LinkedListMultimap$1EntriesImpl: void forEach(java.util.function.Consumer)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt;com.google.common.collect.CollectSpliterators$1$lambda_tryAdvance_0__49: void accept(java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.CollectSpliterators$1: void lambda$tryAdvance$0(java.util.function.Consumer,java.util.function.Function,java.lang.Object)&gt; 
</br>&lt;com.google.common.collect.Iterables$1$stream__122: java.lang.Object apply(java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.Streams: java.util.stream.Stream stream(java.lang.Iterable)&gt; 
</details>

<b><i>2. com.google.common.collect.ImmutableMapValues: void lambda$forEach$0(java.util.function.Consumer,java.lang.Object,java.lang.Object)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt; com.squareup.javapoet.CodeWriter: void emitTypeVariables(java.util.List)>&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt; com.google.common.collect.LinkedListMultimap$1EntriesImpl: void forEach(java.util.function.Consumer)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt; com.google.common.collect.AbstractMapBasedMultimap$lambda_null_2__10: void accept(java.lang.Object)&gt;  
</br>&lt; com.google.common.collect.AbstractMapBasedMultimap: void lambda$null$2(java.util.function.BiConsumer,java.lang.Object,java.lang.Object)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt; com.google.common.collect.ImmutableMapValues$lambda_forEach_0__84: void accept(java.lang.Object,java.lang.Object)&gt;  
</br>&lt; com.google.common.collect.ImmutableMapValues: void lambda$forEach$0(java.util.function.Consumer,java.lang.Object,java.lang.Object)&gt; 
</details>

<b><i>3. ocom.google.common.collect.Multimaps$Keys: void lambda$forEach$0(java.util.function.Consumer,java.util.Map$Entry)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;com.squareup.javapoet.MethodSpec: java.lang.String toString()&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.squareup.javapoet.MethodSpec: void emit(com.squareup.javapoet.CodeWriter,java.lang.String,java.util.Set)&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.squareup.javapoet.CodeWriter: void popTypeVariables(java.util.List)&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.google.common.collect.ImmutableList: void forEach(java.util.function.Consumer)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt;com.google.common.collect.Multimaps$Keys$lambda_forEach_0__155: void accept(java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.Multimaps$Keys: void lambda$forEach$0(java.util.function.Consumer,java.util.Map$Entry)&gt; 
</details>

<b><i>4. ocom.google.common.collect.Multimaps$Keys: void lambda$forEach$0(java.util.function.Consumer,java.util.Map$Entry)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;com.squareup.javapoet.CodeWriter: void emitTypeVariables(java.util.List)&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.google.common.collect.LinkedListMultimap$1EntriesImpl: void forEach(java.util.function.Consumer)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt;com.google.common.collect.AbstractMapBasedMultimap$lambda_null_2__10: void accept(java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.AbstractMapBasedMultimap: void lambda$null$2(java.util.function.BiConsumer,java.lang.Object,java.lang.Object)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt;com.google.common.collect.ImmutableSortedMultiset$lambda_toImmutableSortedMultiset_2__110: void accept(java.lang.Object,java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.ImmutableSortedMultiset: void lambda$toImmutableSortedMultiset$2(java.util.function.Function,java.util.function.ToIntFunction,com.google.common.collect.Multiset,java.lang.Object)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt;com.google.common.collect.ImmutableSortedMultiset$lambda_toImmutableSortedMultiset_0__108: int applyAsInt(java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.ImmutableSortedMultiset: int lambda$toImmutableSortedMultiset$0(java.lang.Object)&gt;  
</details>

<b><i>5. com.google.common.collect.Streams: java.util.stream.DoubleStream lambda$concat$4(java.util.stream.DoubleStream)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;com.squareup.javapoet.MethodSpec: java.lang.String toString()&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.squareup.javapoet.MethodSpec: void emit(com.squareup.javapoet.CodeWriter,java.lang.String,java.util.Set)&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.squareup.javapoet.CodeWriter: void popTypeVariables(java.util.List)&gt; javapoet-javapoet-1.13.0\target\classes
</br>&lt;com.google.common.collect.ImmutableList: void forEach(java.util.function.Consumer)&gt; Repositories\com\google\guava\guava\23.4-android\guava-23.4-android.jar
</br>&lt;com.google.common.collect.CollectSpliterators$1$lambda_tryAdvance_0__49: void accept(java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.CollectSpliterators$1: void lambda$tryAdvance$0(java.util.function.Consumer,java.util.function.Function,java.lang.Object)&gt; 
</br>&lt;com.google.common.collect.Streams$lambda_concat_4__184: java.lang.Object apply(java.lang.Object)&gt;  
</br>&lt;com.google.common.collect.Streams: java.util.stream.DoubleStream lambda$concat$4(java.util.stream.DoubleStream)&gt; 
</details>

The above missing methods are actually referenced by <b><i>javapoet-1.13.0</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Upgrade direct dependency <b><i>com.google.guava:guava</i></b> from <b><i>23.4-android</i></b> to <b><i>24.0-jre</i></b>.
2. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library <b><i>com.google.guava:guava</i></b> to be <b><i>24.0-jre</i></b> in javapoet-1.13.0's pom file.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

Dependency tree----
<details>
<summary>click for details</summary>
</br>[INFO] com.squareup:javapoet:jar:1.13.0
</br>[INFO] +- com.google.truth:truth:jar:0.39:test
</br>[INFO] |  +- <b>com.google.guava:guava:jar:23.4-android:test</b>
</br>[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:1.3.9:test
</br>[INFO] |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.0.18:test - omitted for conflict with 2.1.3)
</br>[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:test
</br>[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:test
</br>[INFO] |  +- (junit:junit:jar:4.12:test - omitted for duplicate)
</br>[INFO] |  \- com.google.errorprone:error_prone_annotations:jar:2.1.3:test
</br>[INFO] +- com.google.testing.compile:compile-testing:jar:0.15:test
</br>[INFO] |  +- (junit:junit:jar:4.12:test - omitted for duplicate)
</br>[INFO] |  +- (com.google.truth:truth:jar:0.37:test - omitted for conflict with 0.39)
</br>[INFO] |  +- com.google.truth.extensions:truth-java8-extension:jar:0.37:test
</br>[INFO] |  |  \- (com.google.truth:truth:jar:0.37:test - omitted for conflict with 0.39)
</br>[INFO] |  +- <b>(com.google.guava:guava:jar:23.5-jre:test - omitted for conflict with 23.4-android)</b>
</br>[INFO] |  +- com.google.auto.value:auto-value:jar:1.5.3:test
</br>[INFO] |  +- (com.squareup:javapoet:jar:1.9.0:test - omitted for cycle)
</br>[INFO] |  +- com.google.auto:auto-common:jar:0.9:test
</br>[INFO] |  |  \- <b>(com.google.guava:guava:jar:23.5-jre:test - omitted for conflict with 23.4-android)</b>
</br>[INFO] |  \- com.sun:tools:jar:1.8.0_241:system
</br>[INFO] +- junit:junit:jar:4.12:test
</br>[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
</br>[INFO] +- com.google.jimfs:jimfs:jar:1.1:test
</br>[INFO] |  \- <b>(com.google.guava:guava:jar:18.0:test - omitted for conflict with 23.4-android)</b>
</br>[INFO] +- org.mockito:mockito-core:jar:2.13.0:test
</br>[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.7.9:test
</br>[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.7.9:test
</br>[INFO] |  \- org.objenesis:objenesis:jar:2.6:test
</br>[INFO] \- org.eclipse.jdt.core.compiler:ecj:jar:4.6.1:test
</details>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @Egorand

**Comment by JakeWharton** [comment]
The build isn't failing though, so I'm not quite sure I understand what the problem is in practice.

**Comment by tbroyer** [comment]
I bet some automated tooling, that also _forgot_ that Guava is only a scope=test dependency here.
