### ISSUE TITLE
The project's Javadoc is out of date

### ISSUE THREAD

**Issue by ogregoire** [square/javapoet#800]
The [Javadoc](https://square.github.io/javapoet/1.x/javapoet/) is out of date. It currently looks like it's pointing to the version 1.10 of the project while the version 1.13 has been released.

JavaPoet was released on June 18th, 2020 and the [gh-pages branch](https://github.com/square/javapoet/tree/gh-pages) has its last commit on January 27th, 2018.

Could you please update the Javadoc so that it's up to date for everybody?

**Comment by Egorand** [comment]
Updated, thanks for flagging!
