### ISSUE TITLE
Java 9 allows private methods on Interfaces. Javapoet's MethodSpec doesn't allow this

### ISSUE THREAD

**Issue by Randgalt** [square/javapoet#805]
```java
        MethodSpec methodSpec = MethodSpec.methodBuilder(name)
                .addModifiers(Modifier.PRIVATE)
                .addCode(codeBlock)
                .build();
```

The above will fail. Yet, on Java 9+ this is a legal combination of modifiers.

**Comment by JakeWharton** [comment]
Just an oversight due to the age of the codebase

**Comment by Randgalt** [comment]
The question, though, is how to handle it. Should it just always be allowed with the caveat that the Java file won't compile under Java 8? That would be a quick solution. Are there plans for Java 9+ feature support (e.g. records, etc.)?

**Comment by JakeWharton** [comment]
Yep we'll just always allow it. The compiler is the final source of truth. The validations which are present are to help you narrow down obvious failures as early as possible, but they're best effort.

We only support stable language features so records will have to wait until Java 16 or 17 when stable. As far as I remember the only new language features which are stable (aside from private methods in interfaces) are text blocks and switch expressions. I don't think we need to do anything to support either of those.

**Comment by Randgalt** [comment]
Any news on the PR?
