### ISSUE TITLE
How to generate KDocs/Java doc after adding doc using addKdoc

### ISSUE THREAD

**Issue by bhaktasatapathy** [square/javapoet#809]
By using addKdoc I am able to write javadoc for generated class and methods, But how can I make this doc part of Kdoc?
When I am using dokka to generate doc, then generated class and methods does not get listed.

I know it's not java poet issue but what is the point of having addKdoc api where we can not generate doc by using Kdoc/dokka?

**Comment by tbroyer** [comment]
There's no `addKdoc` in JavaPoet, did you mean to open this issue in KotlinPoet? https://github.com/square/kotlinpoet
