### ISSUE TITLE
hello! How to copy the java file code to the specified package path using javapoet and how to implement automatic package import in javapoet

### ISSUE THREAD

**Issue by cailiming1994** [square/javapoet#814]

**Comment by cailiming1994** [comment]
Is this the interface :
TypeSpectypeSpec = TypeSpec.classBuilder("").addInitializerBlock(CodeBlock.of("")).build();

**Comment by cailiming1994** [comment]
I want Copy the Java code to Specified package path and import the package automatically

JavaFile javaFile = JavaFile.builder(”com.xxx.xxx“, typeSpec).build();

**Comment by Egorand** [comment]
By "import the package" you mean just changing the package in the file once it's moved to a different package? Don't think you need JavaPoet for that, you can simply use Java's File API, or a shell script, depending on where your code runs.

Also, please ask usage questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/javapoet), this issue tracker is primarily for bug reports and feature requests. Thanks!

**Comment by cailiming1994** [comment]
ok，i see, thank you
