### ISSUE TITLE
Add .class argument during add statement

### ISSUE THREAD

**Issue by aleboulanger** [square/javapoet#815]
I'm trying to add a statement in a constructor which initialize a map and I have to add **Foo.class** as argument, for example:

```
import org.test.Foo

 private Map<String, Class<? extends Foo>> classes = new HashMap<>();

  public AnnotatedActionRegistry() {
    this.classes.put("foo", Foo.class); // Foo.class and not Foo
 }
```

Do you know if is it possible with the framework please ?

**Comment by JakeWharton** [comment]
You would emit `$T.class` and pass a `TypeName` corresponding to `Foo`.

**Comment by aleboulanger** [comment]
found with "$T.class" 👍
