### ISSUE TITLE
File formatting

### ISSUE THREAD

**Issue by AndyLeeeee** [square/javapoet#818]
Hi, I wander asking a question about the file format. The java file I created by Javapoet which is a wonderful tool is not in good format, for example, a line should contains a maximum of 120 characters. If the line exceeds 120 characters, the line will be folded automatically.
Can support automatic formatting in the future？If we can set the detail formatting mode which is even better.
Thanks a lot!

Merry Christmas!!!
Lee

**Comment by JakeWharton** [comment]
We have no plans to support this. You can run a formatter over the output before writing it to the Filer or file system.

That being said, Dagger used to do this and 40% of the annotation processor time was spent formatting the generated code. That's a _huge_ waste of time to put in the critical path of compilation, so only consider formatting if your generator runs out-of-band of normal compilation.
