### ISSUE TITLE
Using instanceof with generic class

### ISSUE THREAD

**Issue by hohserg1** [square/javapoet#824]
Such code:
```java
DeclaredType genericType = ...
 builder.nextControlFlow("else if (value instanceof $T)", genericType);
```
produce follow result:
```java
} else if (value instanceof Test.TestContainer<A, B, C>) {
```
expected:
```java
} else if (value instanceof Test.TestContainer) {
```

I got around this problem through:
```java
builder.nextControlFlow("else if (value instanceof $L)", ((TypeElement) genericType.asElement()).getQualifiedName());
```
but it's look spooky.
How to use instanceof with generic types correctly?

Version of JavaPoet is 1.13.0

**Comment by tbroyer** [comment]
If you have one around, you can use [`Types#erasure`](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/lang/model/util/Types.html#erasure(javax.lang.model.type.TypeMirror)), or simply `ClassName.get((TypeElement) genericType.asElement()))` or `((ParameterizedTypeName) TypeName.get(genericType)).rawType`.

I would personally try to go from `javax.lang.model.*` to JavaPoet's `TypeName` subclasses early, they're much easier to deal with.
