### ISSUE TITLE
Question: Is there any way to convert Java source or AST into JavaPoet code?

### ISSUE THREAD

**Issue by seanghay** [square/javapoet#843]
Or maybe AST -> JavaPoet.

I am doing a large codebase migration and I want minimize manual work. 

I want to: 
1. Java Source -> JavaPoet source
2. Modify JavaPoet source
3. JavaPoet source -> Java Source back

> StackOverflow is overrated 😄

**Comment by JakeWharton** [comment]
No. I recommend the Spoon library for this: https://spoon.gforge.inria.fr/

If you're feeling adventurous you could also use IntelliJ PSI which is what the IntelliJ IDEA editor uses to manipulate your code.

**Comment by seanghay** [comment]
Thanks @JakeWharton!
