### ISSUE TITLE
Attempt to recreate a file for type

### ISSUE THREAD

**Issue by smitalm** [square/javapoet#844]
I am generating source files with JavaPoet and it works great. However, i must do clean before every compilation, otherwise i get `Caused by: javax.annotation.processing.FilerException: Attempt to recreate a file for type`.

I tried calling `javaFile.toJavaFileObject().delete()` before writing to Filer, but it does nothing. 

I asked more detailed question on [StackOverflow](https://stackoverflow.com/questions/67905812/java-annotation-processing-with-javapoet-attempt-to-recreate-a-file-for-type)

**Comment by JakeWharton** [comment]
StackOverflow is the right place for this. You would see the same error if you wrote to the `Filer` without JavaPoet.
