### ISSUE TITLE
Unnamed module access with JDK 17

### ISSUE THREAD

**Issue by cdprete** [square/javapoet#864]
Hi.
I don't know how exactly your project is used in https://github.com/mapstruct/mapstruct-spring-extensions/issues/36 but I get the following error from the Maven compiler under JDK 17:
```
class com.squareup.javapoet.ArrayTypeName cannot be cast to class com.squareup.javapoet.ClassName (com.squareup.javapoet.ArrayTypeName and com.squareup.javapoet.ClassName are in unnamed module of loader java.net.URLClassLoader @712cfb63)
```

**Comment by JakeWharton** [comment]
It's not clear why this would be something that we have to (or even can) address. Seems like a but in that library where they assume all types are classes when in fact they can be arrays.
