### ISSUE TITLE
Can the javapoet generate constructor or getter or setter automatically?

### ISSUE THREAD

**Issue by kejiology** [square/javapoet#881]
just like intelliJ IDEA like this?
<img width="213" alt="image" src="https://user-images.githubusercontent.com/104211320/164728742-6d8eadb2-b1c0-45fd-8122-0366bc7b3135.png">

**Comment by kejiology** [comment]
I will try to add this feature.

**Comment by WangXiequn** [comment]
I will try to add this feature.

**Comment by JakeWharton** [comment]
No. You must always explicitly generate these yourself. You're free to create helper methods which take a spec builder and add a field/getter/setter combo with any options you want, but we don't want to maintain those for everyone.
