### ISSUE TITLE
ClassName.bestGuess function :  Case for classNameString "?" not handled

### ISSUE THREAD

**Issue by prakharporwal** [square/javapoet#940]
- for function say
```java
 @RequestMapping(value = "/add/{a}/{b}",method = RequestMethod.GET)
    public ResponseEntity<?> add(@PathVariable double a, @PathVariable double b){
        double ans =  booking.book(a, b);
        return ResponseEntity.ok(ans);
    }
```

ClassName.bestGuess throws NullPointer with `couldn't make a guess for ? `

StackTrace: 
```
java.lang.IllegalArgumentException: couldn't make a guess for ?
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.ClassName.bestGuess(ClassName.java:206)
```

**Comment by octylFractal** [comment]
That seems correct to me, `?` can't be a valid class name so it must fail.

**Comment by prakharporwal** [comment]
- But considering the function I attached the guess for it should be ?.
- Or is there some other function I should use for generics return type like `ResponseEntity<?>`

**Comment by octylFractal** [comment]
It would be represented as `ParameterizedTypeName.get(ClassName. get(ResponseEntity.class), WildcardTypeName.subtypeOf(Object.class))`.

**Comment by prakharporwal** [comment]
Yes. I meant should I use a different function to GuessType for such a case the Type here is dynamic and I can't decide when it is "?".
Should I use a 
```
if(type == "?")
        //do nothing
else
     ClassName.bestGuess(type)
```

or is there  a different function to use instead of ClassName.bestGuess which can detect for "?" also.

**Comment by octylFractal** [comment]
If you only have the `String` then yes, you have to handle it yourself. If you have a `Type` or `TypeMirror` you can use the methods on `TypeName`.

**Comment by JakeWharton** [comment]
Parsing a type from a string is complicated and is indeed why we don't offer an API for it. Also, generally, these types are not fully qualified which further complicates things.

For example: `Map<? extends @NonNull CharSequence, @C int @A [] @B []>>`. Valid, and not fun.
