### ISSUE TITLE
Need Help : Getting the ClassName from Array !  

### ISSUE THREAD

**Issue by prakharporwal** [square/javapoet#943]
- Is there a function I can use to get the class name of from a array class Name
- eg :  `com.example.SomeClassName[ ]`  =>  function()  =>  returns  `com.example.SomeClassName`

Looking function for a non-primitive type of Class.

**Comment by octylFractal** [comment]
Do you mean `ArrayTypeName`? If so, https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/ArrayTypeName.java#L31, and then you need to cast it.

**Comment by prakharporwal** [comment]
- I am actually trying to do the reverse of what ArrayTypeName.of() does to a TypeName Object .

**Comment by JakeWharton** [comment]
Then their solution is the right one. Just keep in mind the component type might not be a class. It could be another array type, a generic type, a type parameter, etc.

**Comment by prakharporwal** [comment]
@octylFractal @JakeWharton  Thanks for the solution I was able to achieve what I wanted.
