### ISSUE TITLE
Add support for asserting on selected option label(s)

### ISSUE THREAD

**Issue by mrokitka** [square/javapoet#976]
Assertions exist for select type locators for both value and values (for multiselect), but there is no assertion for selected labels.  It is unusual that you can select a value by label, but cannot perform an assertion based on the label.

Relevant docs:
https://playwright.dev/java/docs/input#select-options
https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-have-value
https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-have-values

I would propose that the following select assertions are added:

assertThat(locator).hasLabel()
assertThat(locator).hasLabels() - for multi-selects

**Comment by JakeWharton** [comment]
This is not the playwright project. You want https://github.com/microsoft/playwright probably.

**Comment by mrokitka** [comment]
My apologies, wrong window =)
