### ISSUE TITLE
Add support for diamond type names

### ISSUE THREAD

**Issue by ijioio** [square/javapoet#984]
As for now I haven't found any evidences that type names with diamond operator are supported. Please, correct me if I'm wrong.

If it's the case, here is what I really missing at the moment. Let's say, I have a following code:

```java
String name = "foo";
TypeName type = ParameterizedTypeName.get(ClassName.get(Foo.class), ClassName.get(Bar.class));
FieldSpec field = FieldSpec.builder(type, name)
    .addModifiers(Modifier.PRIVATE, Modifier.FINAL)
    .initializer("new $T()", type)
    .build()
```
that generates following snippet:

```java
private final Foo<Bar> foo = new Foo<Bar>();
```

I wish I can have a special `$` notation syntax to generate type with diamond operator. For example, instead of `$T` I can use `$D` to emit diamond operator form type, so the result will looks like this:

```java
private final Foo<Bar> foo = new Foo<>();
```

First of all, the resulting code will become more compact and clean. The second reason is a types with wildcards. Let's change the above example and use `WildcardTypeName` instead of `ParameterizedTypeName`:

```java
String name = "foo";
TypeName type = WildcardTypeName.subtypeOf(ParameterizedTypeName.get(ClassName.get(Foo.class), ClassName.get(Bar.class)));
FieldSpec field = FieldSpec.builder(type, name)
    .addModifiers(Modifier.PRIVATE, Modifier.FINAL)
    .initializer("new $T()", type)
    .build()
```

This time. it will generate following snippet:

```java
private final Foo<? extends Bar> foo = new Foo<? extends Bar>();
```

which is incorrect code, as wildcards are not allowed in constructors call. It should be either `new Foo<Bar>()` (that implies I need to construct/keep another type name variable) or `new Foo<>()`.

The last one will be significantly simplified if we have a special `$D` parameter and/or method to extract/create a special `DiamondTypeName` from `ParameterizedTypeName` and `WildcardTypeName`.

**Comment by JakeWharton** [comment]
In general I don't think we would do this because it's a bit too specialized and has multiple ways of working around the problem. In the past I've done `new $T<>()` and supplied only the raw type to the instantiation site. If the type is dynamic, you can conditionally check whether it's a `ParameterizedTypeName`, `WildcardTypeName`, or `ClassName` and extract the raw type programmatically. You could also have a function which returned a `CodeBlock`, did the conditional extraction, and created the `new $T<>` snippet which you could then return and use via `$L`.

**Comment by ijioio** [comment]
> and has multiple ways of working around the problem. 

I understand that we have a multiple workarounds, and I use one to do the trick, but it seems too much boilerplate for the language pure feature. I still have strong feeling it should be supported on the library level.

**Comment by JakeWharton** [comment]
In order to keep the library small, I don't think we're going to add this as a supported feature.

**Comment by liujianpc** [comment]
您好，本人已收到您的邮件！谢谢！      祝您工作顺利，生活愉快！
